/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError.js';
import {
    type CreateChatGroupRequest,
    CreateChatGroupRequestFromJSON,
    CreateChatGroupRequestToJSON,
} from '../models/CreateChatGroupRequest.js';
import {
    type DeveloperChatAvatarResponse,
    DeveloperChatAvatarResponseFromJSON,
    DeveloperChatAvatarResponseToJSON,
} from '../models/DeveloperChatAvatarResponse.js';
import {
    type DeveloperChatLinkPreview,
    DeveloperChatLinkPreviewFromJSON,
    DeveloperChatLinkPreviewToJSON,
} from '../models/DeveloperChatLinkPreview.js';
import {
    type DeveloperChatMessage,
    DeveloperChatMessageFromJSON,
    DeveloperChatMessageToJSON,
} from '../models/DeveloperChatMessage.js';
import {
    type DeveloperChatMessageListResponse,
    DeveloperChatMessageListResponseFromJSON,
    DeveloperChatMessageListResponseToJSON,
} from '../models/DeveloperChatMessageListResponse.js';
import {
    type DeveloperChatOkResponse,
    DeveloperChatOkResponseFromJSON,
    DeveloperChatOkResponseToJSON,
} from '../models/DeveloperChatOkResponse.js';
import {
    type DeveloperChatPresenceResponse,
    DeveloperChatPresenceResponseFromJSON,
    DeveloperChatPresenceResponseToJSON,
} from '../models/DeveloperChatPresenceResponse.js';
import {
    type DeveloperChatReactionResponse,
    DeveloperChatReactionResponseFromJSON,
    DeveloperChatReactionResponseToJSON,
} from '../models/DeveloperChatReactionResponse.js';
import {
    type DeveloperChatRequestResponse,
    DeveloperChatRequestResponseFromJSON,
    DeveloperChatRequestResponseToJSON,
} from '../models/DeveloperChatRequestResponse.js';
import {
    type DeveloperChatThread,
    DeveloperChatThreadFromJSON,
    DeveloperChatThreadToJSON,
} from '../models/DeveloperChatThread.js';
import {
    type DeveloperChatThreadListResponse,
    DeveloperChatThreadListResponseFromJSON,
    DeveloperChatThreadListResponseToJSON,
} from '../models/DeveloperChatThreadListResponse.js';
import {
    type DeveloperChatTitleResponse,
    DeveloperChatTitleResponseFromJSON,
    DeveloperChatTitleResponseToJSON,
} from '../models/DeveloperChatTitleResponse.js';
import {
    type DeveloperChatUnreadCountResponse,
    DeveloperChatUnreadCountResponseFromJSON,
    DeveloperChatUnreadCountResponseToJSON,
} from '../models/DeveloperChatUnreadCountResponse.js';
import {
    type InviteChatParticipantsRequest,
    InviteChatParticipantsRequestFromJSON,
    InviteChatParticipantsRequestToJSON,
} from '../models/InviteChatParticipantsRequest.js';
import {
    type MarkChatThreadReadRequest,
    MarkChatThreadReadRequestFromJSON,
    MarkChatThreadReadRequestToJSON,
} from '../models/MarkChatThreadReadRequest.js';
import {
    type ToggleChatMessageReactionRequest,
    ToggleChatMessageReactionRequestFromJSON,
    ToggleChatMessageReactionRequestToJSON,
} from '../models/ToggleChatMessageReactionRequest.js';
import {
    type UpdateChatGroupTitleRequest,
    UpdateChatGroupTitleRequestFromJSON,
    UpdateChatGroupTitleRequestToJSON,
} from '../models/UpdateChatGroupTitleRequest.js';

export interface AcceptChatRequestRequest {
    threadId: number;
}

export interface ArchiveChatThreadRequest {
    threadId: number;
}

export interface CreateChatGroupOperationRequest {
    createChatGroupRequest: CreateChatGroupRequest;
    idempotencyKey?: string;
}

export interface CreateChatMessageRequest {
    threadId: number;
    idempotencyKey?: string;
    attachments?: Array<Blob>;
    content?: string;
    replyToMessageId?: number;
}

export interface CreateChatRequestRequest {
    toUserId: number;
    idempotencyKey?: string;
    attachments?: Array<Blob>;
    content?: string;
}

export interface DeclineChatRequestRequest {
    threadId: number;
}

export interface GetChatLinkPreviewRequest {
    url: string;
}

export interface GetChatPresenceRequest {
    userIds: Set<number>;
}

export interface GetChatThreadRequest {
    threadId: number;
}

export interface InviteChatParticipantsOperationRequest {
    threadId: number;
    inviteChatParticipantsRequest: InviteChatParticipantsRequest;
}

export interface LeaveChatGroupRequest {
    threadId: number;
}

export interface ListChatMessagesRequest {
    threadId: number;
    cursor?: number;
    limit?: number;
}

export interface ListChatThreadsRequest {
    folder?: ListChatThreadsFolderEnum;
    limit?: number;
}

export interface MarkChatThreadReadOperationRequest {
    threadId: number;
    markChatThreadReadRequest: MarkChatThreadReadRequest;
}

export interface RemoveChatGroupAvatarRequest {
    threadId: number;
}

export interface RemoveChatParticipantRequest {
    threadId: number;
    userId: number;
}

export interface ToggleChatMessageReactionOperationRequest {
    messageId: number;
    toggleChatMessageReactionRequest: ToggleChatMessageReactionRequest;
}

export interface UnarchiveChatThreadRequest {
    threadId: number;
}

export interface UpdateChatGroupAvatarRequest {
    threadId: number;
    avatar: Blob;
}

export interface UpdateChatGroupTitleOperationRequest {
    threadId: number;
    updateChatGroupTitleRequest: UpdateChatGroupTitleRequest;
}

/**
 *
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Creates request options for acceptChatRequest without sending the request
     */
    async acceptChatRequestRequestOpts(requestParameters: AcceptChatRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling acceptChatRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/accept`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Accept an incoming direct-message request or pending group invitation for the authenticated caller after validating its current state and recipient ownership.
     * Accept a pending direct request
     */
    async acceptChatRequestRaw(requestParameters: AcceptChatRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.acceptChatRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Accept an incoming direct-message request or pending group invitation for the authenticated caller after validating its current state and recipient ownership.
     * Accept a pending direct request
     */
    async acceptChatRequest(requestParameters: AcceptChatRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.acceptChatRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for archiveChatThread without sending the request
     */
    async archiveChatThreadRequestOpts(requestParameters: ArchiveChatThreadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling archiveChatThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/archive`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Archive a caller-accessible conversation for the authenticated caller only. Repeating the operation leaves the conversation archived without affecting other participants.
     * Archive a thread
     */
    async archiveChatThreadRaw(requestParameters: ArchiveChatThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.archiveChatThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Archive a caller-accessible conversation for the authenticated caller only. Repeating the operation leaves the conversation archived without affecting other participants.
     * Archive a thread
     */
    async archiveChatThread(requestParameters: ArchiveChatThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.archiveChatThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createChatGroup without sending the request
     */
    async createChatGroupRequestOpts(requestParameters: CreateChatGroupOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createChatGroupRequest'] == null) {
            throw new runtime.RequiredError(
                'createChatGroupRequest',
                'Required parameter "createChatGroupRequest" was null or undefined when calling createChatGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/groups`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChatGroupRequestToJSON(requestParameters['createChatGroupRequest']),
        };
    }

    /**
     * Create a group conversation owned by an eligible creator or staff caller and invite a deduplicated set of existing users. Idempotency prevents duplicate groups on retry.
     * Create a group thread
     */
    async createChatGroupRaw(requestParameters: CreateChatGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatThread>> {
        const requestOptions = await this.createChatGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatThreadFromJSON(jsonValue));
    }

    /**
     * Create a group conversation owned by an eligible creator or staff caller and invite a deduplicated set of existing users. Idempotency prevents duplicate groups on retry.
     * Create a group thread
     */
    async createChatGroup(requestParameters: CreateChatGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatThread> {
        const response = await this.createChatGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createChatMessage without sending the request
     */
    async createChatMessageRequestOpts(requestParameters: CreateChatMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling createChatMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['attachments'] != null) {
            requestParameters['attachments'].forEach((element) => {
                formParams.append('attachments', element as any);
            })
        }

        if (requestParameters['content'] != null) {
            formParams.append('content', requestParameters['content'] as any);
        }

        if (requestParameters['replyToMessageId'] != null) {
            formParams.append('replyToMessageId', requestParameters['replyToMessageId'] as any);
        }


        let urlPath = `/api/chat/threads/{threadId}/messages`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Create a text, attachment, or reply message in a caller-accessible active conversation. Idempotency prevents duplicate messages and attachment records on retry.
     * Post a message to a thread
     */
    async createChatMessageRaw(requestParameters: CreateChatMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatMessage>> {
        const requestOptions = await this.createChatMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatMessageFromJSON(jsonValue));
    }

    /**
     * Create a text, attachment, or reply message in a caller-accessible active conversation. Idempotency prevents duplicate messages and attachment records on retry.
     * Post a message to a thread
     */
    async createChatMessage(requestParameters: CreateChatMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatMessage> {
        const response = await this.createChatMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createChatRequest without sending the request
     */
    async createChatRequestRequestOpts(requestParameters: CreateChatRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['toUserId'] == null) {
            throw new runtime.RequiredError(
                'toUserId',
                'Required parameter "toUserId" was null or undefined when calling createChatRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['attachments'] != null) {
            requestParameters['attachments'].forEach((element) => {
                formParams.append('attachments', element as any);
            })
        }

        if (requestParameters['content'] != null) {
            formParams.append('content', requestParameters['content'] as any);
        }

        if (requestParameters['toUserId'] != null) {
            formParams.append('toUserId', requestParameters['toUserId'] as any);
        }


        let urlPath = `/api/chat/requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Open or reuse a direct conversation with another available user and optionally send its first text and validated attachments. Idempotency prevents duplicate requests or messages on retry.
     * Create a direct chat request
     */
    async createChatRequestRaw(requestParameters: CreateChatRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatRequestResponse>> {
        const requestOptions = await this.createChatRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatRequestResponseFromJSON(jsonValue));
    }

    /**
     * Open or reuse a direct conversation with another available user and optionally send its first text and validated attachments. Idempotency prevents duplicate requests or messages on retry.
     * Create a direct chat request
     */
    async createChatRequest(requestParameters: CreateChatRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatRequestResponse> {
        const response = await this.createChatRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for declineChatRequest without sending the request
     */
    async declineChatRequestRequestOpts(requestParameters: DeclineChatRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling declineChatRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/decline`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Decline an incoming direct-message request or pending group invitation for the authenticated caller and archive that caller’s participation state.
     * Decline a pending direct request
     */
    async declineChatRequestRaw(requestParameters: DeclineChatRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.declineChatRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Decline an incoming direct-message request or pending group invitation for the authenticated caller and archive that caller’s participation state.
     * Decline a pending direct request
     */
    async declineChatRequest(requestParameters: DeclineChatRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.declineChatRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getChatLinkPreview without sending the request
     */
    async getChatLinkPreviewRequestOpts(requestParameters: GetChatLinkPreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling getChatLinkPreview().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/link-preview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolve a visibility-checked Arc en Ciel resource or guarded external URL into a compact preview suitable for composing a chat message without exposing private content.
     * Resolve a link preview for a URL
     */
    async getChatLinkPreviewRaw(requestParameters: GetChatLinkPreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatLinkPreview>> {
        const requestOptions = await this.getChatLinkPreviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatLinkPreviewFromJSON(jsonValue));
    }

    /**
     * Resolve a visibility-checked Arc en Ciel resource or guarded external URL into a compact preview suitable for composing a chat message without exposing private content.
     * Resolve a link preview for a URL
     */
    async getChatLinkPreview(requestParameters: GetChatLinkPreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatLinkPreview> {
        const response = await this.getChatLinkPreviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getChatPresence without sending the request
     */
    async getChatPresenceRequestOpts(requestParameters: GetChatPresenceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userIds'] == null) {
            throw new runtime.RequiredError(
                'userIds',
                'Required parameter "userIds" was null or undefined when calling getChatPresence().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userIds'] != null) {
            queryParameters['userIds'] = Array.from(requestParameters['userIds'])!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/presence`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return a bounded presence snapshot for explicitly requested user identifiers. Presence is caller-authenticated and clients must treat timestamps and online state as transient hints.
     * Get presence information for chat contacts
     */
    async getChatPresenceRaw(requestParameters: GetChatPresenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatPresenceResponse>> {
        const requestOptions = await this.getChatPresenceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatPresenceResponseFromJSON(jsonValue));
    }

    /**
     * Return a bounded presence snapshot for explicitly requested user identifiers. Presence is caller-authenticated and clients must treat timestamps and online state as transient hints.
     * Get presence information for chat contacts
     */
    async getChatPresence(requestParameters: GetChatPresenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatPresenceResponse> {
        const response = await this.getChatPresenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getChatThread without sending the request
     */
    async getChatThreadRequestOpts(requestParameters: GetChatThreadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getChatThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return one conversation in which the authenticated caller is an active participant, including caller-relative state, participants, and the latest message summary.
     * Get a chat thread by id
     */
    async getChatThreadRaw(requestParameters: GetChatThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatThread>> {
        const requestOptions = await this.getChatThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatThreadFromJSON(jsonValue));
    }

    /**
     * Return one conversation in which the authenticated caller is an active participant, including caller-relative state, participants, and the latest message summary.
     * Get a chat thread by id
     */
    async getChatThread(requestParameters: GetChatThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatThread> {
        const response = await this.getChatThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getChatUnreadCount without sending the request
     */
    async getChatUnreadCountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/unread-count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the authenticated caller’s number of unarchived conversations whose latest message was sent by another participant after the caller’s read marker.
     * Get unread chat count
     */
    async getChatUnreadCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatUnreadCountResponse>> {
        const requestOptions = await this.getChatUnreadCountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatUnreadCountResponseFromJSON(jsonValue));
    }

    /**
     * Return the authenticated caller’s number of unarchived conversations whose latest message was sent by another participant after the caller’s read marker.
     * Get unread chat count
     */
    async getChatUnreadCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatUnreadCountResponse> {
        const response = await this.getChatUnreadCountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for inviteChatParticipants without sending the request
     */
    async inviteChatParticipantsRequestOpts(requestParameters: InviteChatParticipantsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling inviteChatParticipants().'
            );
        }

        if (requestParameters['inviteChatParticipantsRequest'] == null) {
            throw new runtime.RequiredError(
                'inviteChatParticipantsRequest',
                'Required parameter "inviteChatParticipantsRequest" was null or undefined when calling inviteChatParticipants().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/invite`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InviteChatParticipantsRequestToJSON(requestParameters['inviteChatParticipantsRequest']),
        };
    }

    /**
     * Invite existing users to a caller-owned group conversation. Existing active participants remain active and prior left or declined participants return to pending state.
     * Invite a participant to a group thread
     */
    async inviteChatParticipantsRaw(requestParameters: InviteChatParticipantsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.inviteChatParticipantsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Invite existing users to a caller-owned group conversation. Existing active participants remain active and prior left or declined participants return to pending state.
     * Invite a participant to a group thread
     */
    async inviteChatParticipants(requestParameters: InviteChatParticipantsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.inviteChatParticipantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for leaveChatGroup without sending the request
     */
    async leaveChatGroupRequestOpts(requestParameters: LeaveChatGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling leaveChatGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/leave`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Leave a group conversation as a non-owner participant and archive the caller’s membership. Group owners must transfer or close ownership through supported product controls.
     * Leave a group thread
     */
    async leaveChatGroupRaw(requestParameters: LeaveChatGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.leaveChatGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Leave a group conversation as a non-owner participant and archive the caller’s membership. Group owners must transfer or close ownership through supported product controls.
     * Leave a group thread
     */
    async leaveChatGroup(requestParameters: LeaveChatGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.leaveChatGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listChatMessages without sending the request
     */
    async listChatMessagesRequestOpts(requestParameters: ListChatMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling listChatMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/messages`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List one caller-accessible conversation’s messages in chronological order using a bounded descending cursor, including signed attachments, replies, mentions, and reaction summaries.
     * List messages for a thread
     */
    async listChatMessagesRaw(requestParameters: ListChatMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatMessageListResponse>> {
        const requestOptions = await this.listChatMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatMessageListResponseFromJSON(jsonValue));
    }

    /**
     * List one caller-accessible conversation’s messages in chronological order using a bounded descending cursor, including signed attachments, replies, mentions, and reaction summaries.
     * List messages for a thread
     */
    async listChatMessages(requestParameters: ListChatMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatMessageListResponse> {
        const response = await this.listChatMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listChatThreads without sending the request
     */
    async listChatThreadsRequestOpts(requestParameters: ListChatThreadsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['folder'] != null) {
            queryParameters['folder'] = requestParameters['folder'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the authenticated caller’s visible inbox, incoming requests, outgoing requests, or archived conversations with participant-safe summaries and unread state.
     * List chat threads for the current user
     */
    async listChatThreadsRaw(requestParameters: ListChatThreadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatThreadListResponse>> {
        const requestOptions = await this.listChatThreadsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatThreadListResponseFromJSON(jsonValue));
    }

    /**
     * List the authenticated caller’s visible inbox, incoming requests, outgoing requests, or archived conversations with participant-safe summaries and unread state.
     * List chat threads for the current user
     */
    async listChatThreads(requestParameters: ListChatThreadsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatThreadListResponse> {
        const response = await this.listChatThreadsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markChatThreadRead without sending the request
     */
    async markChatThreadReadRequestOpts(requestParameters: MarkChatThreadReadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling markChatThreadRead().'
            );
        }

        if (requestParameters['markChatThreadReadRequest'] == null) {
            throw new runtime.RequiredError(
                'markChatThreadReadRequest',
                'Required parameter "markChatThreadReadRequest" was null or undefined when calling markChatThreadRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/read`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MarkChatThreadReadRequestToJSON(requestParameters['markChatThreadReadRequest']),
        };
    }

    /**
     * Advance the authenticated caller’s read marker to a supplied message in the conversation or to the latest current message when no identifier is supplied.
     * Mark a thread as read
     */
    async markChatThreadReadRaw(requestParameters: MarkChatThreadReadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.markChatThreadReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Advance the authenticated caller’s read marker to a supplied message in the conversation or to the latest current message when no identifier is supplied.
     * Mark a thread as read
     */
    async markChatThreadRead(requestParameters: MarkChatThreadReadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.markChatThreadReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeChatGroupAvatar without sending the request
     */
    async removeChatGroupAvatarRequestOpts(requestParameters: RemoveChatGroupAvatarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling removeChatGroupAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/avatar`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove the custom avatar from a group conversation owned by the authenticated caller. Repeating the operation leaves the avatar absent.
     * Remove a group avatar
     */
    async removeChatGroupAvatarRaw(requestParameters: RemoveChatGroupAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.removeChatGroupAvatarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Remove the custom avatar from a group conversation owned by the authenticated caller. Repeating the operation leaves the avatar absent.
     * Remove a group avatar
     */
    async removeChatGroupAvatar(requestParameters: RemoveChatGroupAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.removeChatGroupAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeChatParticipant without sending the request
     */
    async removeChatParticipantRequestOpts(requestParameters: RemoveChatParticipantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling removeChatParticipant().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeChatParticipant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/participants/{userId}`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a non-owner participant from a group conversation owned by the authenticated caller without exposing or changing unrelated participant state.
     * Remove a participant from a group thread
     */
    async removeChatParticipantRaw(requestParameters: RemoveChatParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.removeChatParticipantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Remove a non-owner participant from a group conversation owned by the authenticated caller without exposing or changing unrelated participant state.
     * Remove a participant from a group thread
     */
    async removeChatParticipant(requestParameters: RemoveChatParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.removeChatParticipantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toggleChatMessageReaction without sending the request
     */
    async toggleChatMessageReactionRequestOpts(requestParameters: ToggleChatMessageReactionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling toggleChatMessageReaction().'
            );
        }

        if (requestParameters['toggleChatMessageReactionRequest'] == null) {
            throw new runtime.RequiredError(
                'toggleChatMessageReactionRequest',
                'Required parameter "toggleChatMessageReactionRequest" was null or undefined when calling toggleChatMessageReaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/messages/{messageId}/reactions`;
        urlPath = urlPath.replace('{messageId}', encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleChatMessageReactionRequestToJSON(requestParameters['toggleChatMessageReactionRequest']),
        };
    }

    /**
     * Toggle the authenticated caller’s validated emote reaction on an accessible message and return the complete caller-relative reaction summary. This toggle is not retry-safe.
     * Toggle a reaction for a message
     */
    async toggleChatMessageReactionRaw(requestParameters: ToggleChatMessageReactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatReactionResponse>> {
        const requestOptions = await this.toggleChatMessageReactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatReactionResponseFromJSON(jsonValue));
    }

    /**
     * Toggle the authenticated caller’s validated emote reaction on an accessible message and return the complete caller-relative reaction summary. This toggle is not retry-safe.
     * Toggle a reaction for a message
     */
    async toggleChatMessageReaction(requestParameters: ToggleChatMessageReactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatReactionResponse> {
        const response = await this.toggleChatMessageReactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unarchiveChatThread without sending the request
     */
    async unarchiveChatThreadRequestOpts(requestParameters: UnarchiveChatThreadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling unarchiveChatThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/unarchive`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove the authenticated caller’s archive marker from an accessible conversation. Repeating the operation leaves it unarchived without changing other participants.
     * Unarchive a thread
     */
    async unarchiveChatThreadRaw(requestParameters: UnarchiveChatThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatOkResponse>> {
        const requestOptions = await this.unarchiveChatThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatOkResponseFromJSON(jsonValue));
    }

    /**
     * Remove the authenticated caller’s archive marker from an accessible conversation. Repeating the operation leaves it unarchived without changing other participants.
     * Unarchive a thread
     */
    async unarchiveChatThread(requestParameters: UnarchiveChatThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatOkResponse> {
        const response = await this.unarchiveChatThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateChatGroupAvatar without sending the request
     */
    async updateChatGroupAvatarRequestOpts(requestParameters: UpdateChatGroupAvatarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateChatGroupAvatar().'
            );
        }

        if (requestParameters['avatar'] == null) {
            throw new runtime.RequiredError(
                'avatar',
                'Required parameter "avatar" was null or undefined when calling updateChatGroupAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['avatar'] != null) {
            formParams.append('avatar', requestParameters['avatar'] as any);
        }


        let urlPath = `/api/chat/threads/{threadId}/avatar`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload and replace the validated avatar of a group conversation owned by the authenticated caller. Clients must not automatically retry this multipart mutation.
     * Upload or replace a group avatar
     */
    async updateChatGroupAvatarRaw(requestParameters: UpdateChatGroupAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatAvatarResponse>> {
        const requestOptions = await this.updateChatGroupAvatarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatAvatarResponseFromJSON(jsonValue));
    }

    /**
     * Upload and replace the validated avatar of a group conversation owned by the authenticated caller. Clients must not automatically retry this multipart mutation.
     * Upload or replace a group avatar
     */
    async updateChatGroupAvatar(requestParameters: UpdateChatGroupAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatAvatarResponse> {
        const response = await this.updateChatGroupAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateChatGroupTitle without sending the request
     */
    async updateChatGroupTitleRequestOpts(requestParameters: UpdateChatGroupTitleOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateChatGroupTitle().'
            );
        }

        if (requestParameters['updateChatGroupTitleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateChatGroupTitleRequest',
                'Required parameter "updateChatGroupTitleRequest" was null or undefined when calling updateChatGroupTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chat/threads/{threadId}/title`;
        urlPath = urlPath.replace('{threadId}', encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateChatGroupTitleRequestToJSON(requestParameters['updateChatGroupTitleRequest']),
        };
    }

    /**
     * Replace or clear the display title of a group conversation owned by the authenticated caller while preserving all participant and message state.
     * Update a group thread title
     */
    async updateChatGroupTitleRaw(requestParameters: UpdateChatGroupTitleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperChatTitleResponse>> {
        const requestOptions = await this.updateChatGroupTitleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperChatTitleResponseFromJSON(jsonValue));
    }

    /**
     * Replace or clear the display title of a group conversation owned by the authenticated caller while preserving all participant and message state.
     * Update a group thread title
     */
    async updateChatGroupTitle(requestParameters: UpdateChatGroupTitleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperChatTitleResponse> {
        const response = await this.updateChatGroupTitleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListChatThreadsFolderEnum = {
    Inbox: 'inbox',
    RequestsIn: 'requests_in',
    RequestsOut: 'requests_out',
    Archived: 'archived',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListChatThreadsFolderEnum = typeof ListChatThreadsFolderEnum[keyof typeof ListChatThreadsFolderEnum];
