/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type AddCollectionCollaboratorRequest,
    AddCollectionCollaboratorRequestFromJSON,
    AddCollectionCollaboratorRequestToJSON,
} from '../models/AddCollectionCollaboratorRequest.js';
import {
    type AddCollectionItemsRequest,
    AddCollectionItemsRequestFromJSON,
    AddCollectionItemsRequestToJSON,
} from '../models/AddCollectionItemsRequest.js';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError.js';
import {
    type CollectionCollaboratorSummary,
    CollectionCollaboratorSummaryFromJSON,
    CollectionCollaboratorSummaryToJSON,
} from '../models/CollectionCollaboratorSummary.js';
import {
    type CollectionContributionRequest,
    CollectionContributionRequestFromJSON,
    CollectionContributionRequestToJSON,
} from '../models/CollectionContributionRequest.js';
import {
    type CollectionDetail,
    CollectionDetailFromJSON,
    CollectionDetailToJSON,
} from '../models/CollectionDetail.js';
import {
    type CollectionPage,
    CollectionPageFromJSON,
    CollectionPageToJSON,
} from '../models/CollectionPage.js';
import {
    type CreateCollectionRequest,
    CreateCollectionRequestFromJSON,
    CreateCollectionRequestToJSON,
} from '../models/CreateCollectionRequest.js';
import {
    type DeveloperCollectionContributionDecisionResponse,
    DeveloperCollectionContributionDecisionResponseFromJSON,
    DeveloperCollectionContributionDecisionResponseToJSON,
} from '../models/DeveloperCollectionContributionDecisionResponse.js';
import {
    type DeveloperCollectionCoverUploadResponse,
    DeveloperCollectionCoverUploadResponseFromJSON,
    DeveloperCollectionCoverUploadResponseToJSON,
} from '../models/DeveloperCollectionCoverUploadResponse.js';
import {
    type DeveloperCollectionIdentity,
    DeveloperCollectionIdentityFromJSON,
    DeveloperCollectionIdentityToJSON,
} from '../models/DeveloperCollectionIdentity.js';
import {
    type DeveloperCollectionItemsMutationResponse,
    DeveloperCollectionItemsMutationResponseFromJSON,
    DeveloperCollectionItemsMutationResponseToJSON,
} from '../models/DeveloperCollectionItemsMutationResponse.js';
import {
    type ReorderCollectionItemsRequest,
    ReorderCollectionItemsRequestFromJSON,
    ReorderCollectionItemsRequestToJSON,
} from '../models/ReorderCollectionItemsRequest.js';
import {
    type RequestCollectionContributionRequest,
    RequestCollectionContributionRequestFromJSON,
    RequestCollectionContributionRequestToJSON,
} from '../models/RequestCollectionContributionRequest.js';
import {
    type ResequenceCollectionItemsRequest,
    ResequenceCollectionItemsRequestFromJSON,
    ResequenceCollectionItemsRequestToJSON,
} from '../models/ResequenceCollectionItemsRequest.js';
import {
    type RespondCollectionContributionRequestRequest,
    RespondCollectionContributionRequestRequestFromJSON,
    RespondCollectionContributionRequestRequestToJSON,
} from '../models/RespondCollectionContributionRequestRequest.js';
import {
    type UpdateCollectionRequest,
    UpdateCollectionRequestFromJSON,
    UpdateCollectionRequestToJSON,
} from '../models/UpdateCollectionRequest.js';

export interface AddCollectionCollaboratorOperationRequest {
    collectionId: number;
    addCollectionCollaboratorRequest: AddCollectionCollaboratorRequest;
}

export interface AddCollectionItemsOperationRequest {
    collectionId: number;
    addCollectionItemsRequest: AddCollectionItemsRequest;
}

export interface CancelCollectionContributionRequestRequest {
    collectionId: number;
}

export interface CreateCollectionOperationRequest {
    createCollectionRequest: CreateCollectionRequest;
    idempotencyKey?: string;
}

export interface DeleteCollectionRequest {
    collectionId: number;
}

export interface GetCollectionRequest {
    collectionId: string;
    includeItems?: GetCollectionIncludeItemsEnum;
    modelLimit?: number;
    modelOffset?: number;
    imageLimit?: number;
    imageOffset?: number;
}

export interface LeaveCollectionRequest {
    collectionId: number;
}

export interface ListCollectionContributionRequestsRequest {
    collectionId: number;
}

export interface ListCollectionsRequest {
    type?: ListCollectionsTypeEnum;
    search?: string;
    sort?: ListCollectionsSortEnum;
    collaborative?: ListCollectionsCollaborativeEnum;
    ownerId?: number;
    scope?: ListCollectionsScopeEnum;
    membership?: ListCollectionsMembershipEnum;
    self?: ListCollectionsSelfEnum;
    visibility?: ListCollectionsVisibilityEnum;
    userId?: number;
    relationship?: ListCollectionsRelationshipEnum;
    page?: number;
    limit?: number;
}

export interface RemoveCollectionCollaboratorRequest {
    collectionId: number;
    collaboratorId: number;
}

export interface RemoveCollectionItemRequest {
    collectionId: number;
    itemId: number;
}

export interface ReorderCollectionItemsOperationRequest {
    collectionId: number;
    reorderCollectionItemsRequest: ReorderCollectionItemsRequest;
}

export interface RequestCollectionContributionOperationRequest {
    collectionId: number;
    requestCollectionContributionRequest?: RequestCollectionContributionRequest;
}

export interface ResequenceCollectionItemsOperationRequest {
    collectionId: number;
    resequenceCollectionItemsRequest?: ResequenceCollectionItemsRequest;
}

export interface RespondCollectionContributionRequestOperationRequest {
    collectionId: number;
    requestId: number;
    respondCollectionContributionRequestRequest: RespondCollectionContributionRequestRequest;
}

export interface UpdateCollectionOperationRequest {
    collectionId: number;
    updateCollectionRequest: UpdateCollectionRequest;
}

export interface UploadCollectionCoverRequest {
    coverImage: Blob;
    idempotencyKey?: string;
}

/**
 *
 */
export class CollectionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addCollectionCollaborator without sending the request
     */
    async addCollectionCollaboratorRequestOpts(requestParameters: AddCollectionCollaboratorOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling addCollectionCollaborator().'
            );
        }

        if (requestParameters['addCollectionCollaboratorRequest'] == null) {
            throw new runtime.RequiredError(
                'addCollectionCollaboratorRequest',
                'Required parameter "addCollectionCollaboratorRequest" was null or undefined when calling addCollectionCollaborator().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/collaborators`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddCollectionCollaboratorRequestToJSON(requestParameters['addCollectionCollaboratorRequest']),
        };
    }

    /**
     * Add or update a collection collaborator with an explicit role while preserving owner and manager authorization rules. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Add or update a collaborator
     */
    async addCollectionCollaboratorRaw(requestParameters: AddCollectionCollaboratorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionCollaboratorSummary>> {
        const requestOptions = await this.addCollectionCollaboratorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionCollaboratorSummaryFromJSON(jsonValue));
    }

    /**
     * Add or update a collection collaborator with an explicit role while preserving owner and manager authorization rules. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Add or update a collaborator
     */
    async addCollectionCollaborator(requestParameters: AddCollectionCollaboratorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionCollaboratorSummary> {
        const response = await this.addCollectionCollaboratorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addCollectionItems without sending the request
     */
    async addCollectionItemsRequestOpts(requestParameters: AddCollectionItemsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling addCollectionItems().'
            );
        }

        if (requestParameters['addCollectionItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'addCollectionItemsRequest',
                'Required parameter "addCollectionItemsRequest" was null or undefined when calling addCollectionItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/items`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddCollectionItemsRequestToJSON(requestParameters['addCollectionItemsRequest']),
        };
    }

    /**
     * Add a bounded set of visible model or image identifiers to a collection and report added, skipped, and rejected identifiers. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Add items to a collection
     */
    async addCollectionItemsRaw(requestParameters: AddCollectionItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperCollectionItemsMutationResponse>> {
        const requestOptions = await this.addCollectionItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperCollectionItemsMutationResponseFromJSON(jsonValue));
    }

    /**
     * Add a bounded set of visible model or image identifiers to a collection and report added, skipped, and rejected identifiers. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Add items to a collection
     */
    async addCollectionItems(requestParameters: AddCollectionItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperCollectionItemsMutationResponse> {
        const response = await this.addCollectionItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cancelCollectionContributionRequest without sending the request
     */
    async cancelCollectionContributionRequestRequestOpts(requestParameters: CancelCollectionContributionRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling cancelCollectionContributionRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/contribution-requests/self`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel the caller’s pending contribution request for one collection without changing collaborator access. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Cancel the current user\'s pending collaboration request
     */
    async cancelCollectionContributionRequestRaw(requestParameters: CancelCollectionContributionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelCollectionContributionRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel the caller’s pending contribution request for one collection without changing collaborator access. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Cancel the current user\'s pending collaboration request
     */
    async cancelCollectionContributionRequest(requestParameters: CancelCollectionContributionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelCollectionContributionRequestRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createCollection without sending the request
     */
    async createCollectionRequestOpts(requestParameters: CreateCollectionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'createCollectionRequest',
                'Required parameter "createCollectionRequest" was null or undefined when calling createCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCollectionRequestToJSON(requestParameters['createCollectionRequest']),
        };
    }

    /**
     * Create a model or image collection with a generated slug, caller ownership, visibility, cover, and collaboration preferences. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Create a new collection
     */
    async createCollectionRaw(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperCollectionIdentity>> {
        const requestOptions = await this.createCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperCollectionIdentityFromJSON(jsonValue));
    }

    /**
     * Create a model or image collection with a generated slug, caller ownership, visibility, cover, and collaboration preferences. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Create a new collection
     */
    async createCollection(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperCollectionIdentity> {
        const response = await this.createCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCollection without sending the request
     */
    async deleteCollectionRequestOpts(requestParameters: DeleteCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling deleteCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a caller-managed collection and its association records without deleting the referenced models or images. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Delete a collection
     */
    async deleteCollectionRaw(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a caller-managed collection and its association records without deleting the referenced models or images. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Delete a collection
     */
    async deleteCollection(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCollectionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCollection without sending the request
     */
    async getCollectionRequestOpts(requestParameters: GetCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling getCollection().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeItems'] != null) {
            queryParameters['includeItems'] = requestParameters['includeItems'];
        }

        if (requestParameters['modelLimit'] != null) {
            queryParameters['modelLimit'] = requestParameters['modelLimit'];
        }

        if (requestParameters['modelOffset'] != null) {
            queryParameters['modelOffset'] = requestParameters['modelOffset'];
        }

        if (requestParameters['imageLimit'] != null) {
            queryParameters['imageLimit'] = requestParameters['imageLimit'];
        }

        if (requestParameters['imageOffset'] != null) {
            queryParameters['imageOffset'] = requestParameters['imageOffset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return one collection visible to the caller with optional paged model and image items, collaborator summaries, counts, and caller-specific permissions. Private collections remain limited to members and privileged staff.
     * Fetch a single collection
     */
    async getCollectionRaw(requestParameters: GetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionDetail>> {
        const requestOptions = await this.getCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDetailFromJSON(jsonValue));
    }

    /**
     * Return one collection visible to the caller with optional paged model and image items, collaborator summaries, counts, and caller-specific permissions. Private collections remain limited to members and privileged staff.
     * Fetch a single collection
     */
    async getCollection(requestParameters: GetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionDetail> {
        const response = await this.getCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for leaveCollection without sending the request
     */
    async leaveCollectionRequestOpts(requestParameters: LeaveCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling leaveCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/collaborators/self`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove the caller’s own non-owner collaborator relationship from a collection without altering its items. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Leave a collection as collaborator
     */
    async leaveCollectionRaw(requestParameters: LeaveCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.leaveCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove the caller’s own non-owner collaborator relationship from a collection without altering its items. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Leave a collection as collaborator
     */
    async leaveCollection(requestParameters: LeaveCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.leaveCollectionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listCollectionContributionRequests without sending the request
     */
    async listCollectionContributionRequestsRequestOpts(requestParameters: ListCollectionContributionRequestsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling listCollectionContributionRequests().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/contribution-requests`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List contribution requests for a collection the authenticated caller may manage. The operation never exposes requests to anonymous callers, ordinary non-manager members, or API keys without the CollectionsRead scope.
     * List pending contribution requests
     */
    async listCollectionContributionRequestsRaw(requestParameters: ListCollectionContributionRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CollectionContributionRequest>>> {
        const requestOptions = await this.listCollectionContributionRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CollectionContributionRequestFromJSON));
    }

    /**
     * List contribution requests for a collection the authenticated caller may manage. The operation never exposes requests to anonymous callers, ordinary non-manager members, or API keys without the CollectionsRead scope.
     * List pending contribution requests
     */
    async listCollectionContributionRequests(requestParameters: ListCollectionContributionRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CollectionContributionRequest>> {
        const response = await this.listCollectionContributionRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCollections without sending the request
     */
    async listCollectionsRequestOpts(requestParameters: ListCollectionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['collaborative'] != null) {
            queryParameters['collaborative'] = requestParameters['collaborative'];
        }

        if (requestParameters['ownerId'] != null) {
            queryParameters['ownerId'] = requestParameters['ownerId'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['membership'] != null) {
            queryParameters['membership'] = requestParameters['membership'];
        }

        if (requestParameters['self'] != null) {
            queryParameters['self'] = requestParameters['self'];
        }

        if (requestParameters['visibility'] != null) {
            queryParameters['visibility'] = requestParameters['visibility'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['relationship'] != null) {
            queryParameters['relationship'] = requestParameters['relationship'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List collections visible to the caller with bounded pagination, discovery filters, relationship filters, item counts, and public owner metadata. Private and manageable views require the corresponding authenticated membership.
     * List collections
     */
    async listCollectionsRaw(requestParameters: ListCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionPage>> {
        const requestOptions = await this.listCollectionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionPageFromJSON(jsonValue));
    }

    /**
     * List collections visible to the caller with bounded pagination, discovery filters, relationship filters, item counts, and public owner metadata. Private and manageable views require the corresponding authenticated membership.
     * List collections
     */
    async listCollections(requestParameters: ListCollectionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionPage> {
        const response = await this.listCollectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeCollectionCollaborator without sending the request
     */
    async removeCollectionCollaboratorRequestOpts(requestParameters: RemoveCollectionCollaboratorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling removeCollectionCollaborator().'
            );
        }

        if (requestParameters['collaboratorId'] == null) {
            throw new runtime.RequiredError(
                'collaboratorId',
                'Required parameter "collaboratorId" was null or undefined when calling removeCollectionCollaborator().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/collaborators/{collaboratorId}`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));
        urlPath = urlPath.replace('{collaboratorId}', encodeURIComponent(String(requestParameters['collaboratorId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove one non-owner collaborator after manager authorization while preserving the collection and referenced content. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Remove a collaborator from a collection
     */
    async removeCollectionCollaboratorRaw(requestParameters: RemoveCollectionCollaboratorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeCollectionCollaboratorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove one non-owner collaborator after manager authorization while preserving the collection and referenced content. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Remove a collaborator from a collection
     */
    async removeCollectionCollaborator(requestParameters: RemoveCollectionCollaboratorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeCollectionCollaboratorRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for removeCollectionItem without sending the request
     */
    async removeCollectionItemRequestOpts(requestParameters: RemoveCollectionItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling removeCollectionItem().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling removeCollectionItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/items/{itemId}`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));
        urlPath = urlPath.replace('{itemId}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove one model or image association from a caller-managed collection without deleting the referenced resource. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Remove an item from a collection
     */
    async removeCollectionItemRaw(requestParameters: RemoveCollectionItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeCollectionItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove one model or image association from a caller-managed collection without deleting the referenced resource. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Remove an item from a collection
     */
    async removeCollectionItem(requestParameters: RemoveCollectionItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeCollectionItemRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for reorderCollectionItems without sending the request
     */
    async reorderCollectionItemsRequestOpts(requestParameters: ReorderCollectionItemsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling reorderCollectionItems().'
            );
        }

        if (requestParameters['reorderCollectionItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'reorderCollectionItemsRequest',
                'Required parameter "reorderCollectionItemsRequest" was null or undefined when calling reorderCollectionItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/items/order`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderCollectionItemsRequestToJSON(requestParameters['reorderCollectionItemsRequest']),
        };
    }

    /**
     * Apply explicit sequence values to existing collection items after validating that every identifier belongs to the collection. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Override the item ordering for a collection
     */
    async reorderCollectionItemsRaw(requestParameters: ReorderCollectionItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.reorderCollectionItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Apply explicit sequence values to existing collection items after validating that every identifier belongs to the collection. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Override the item ordering for a collection
     */
    async reorderCollectionItems(requestParameters: ReorderCollectionItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reorderCollectionItemsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for requestCollectionContribution without sending the request
     */
    async requestCollectionContributionRequestOpts(requestParameters: RequestCollectionContributionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling requestCollectionContribution().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/contribution-requests`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestCollectionContributionRequestToJSON(requestParameters['requestCollectionContributionRequest']),
        };
    }

    /**
     * Create or return the caller’s contribution request for a collection that currently accepts community contributors. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Request collaborator access for a collection
     */
    async requestCollectionContributionRaw(requestParameters: RequestCollectionContributionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionContributionRequest>> {
        const requestOptions = await this.requestCollectionContributionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionContributionRequestFromJSON(jsonValue));
    }

    /**
     * Create or return the caller’s contribution request for a collection that currently accepts community contributors. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Request collaborator access for a collection
     */
    async requestCollectionContribution(requestParameters: RequestCollectionContributionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionContributionRequest> {
        const response = await this.requestCollectionContributionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resequenceCollectionItems without sending the request
     */
    async resequenceCollectionItemsRequestOpts(requestParameters: ResequenceCollectionItemsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling resequenceCollectionItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/items/resequence`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResequenceCollectionItemsRequestToJSON(requestParameters['resequenceCollectionItemsRequest']),
        };
    }

    /**
     * Reassign collection item sequence values from their current order to restore a compact deterministic ordering. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Reapply an automatic ordering to existing collection items
     */
    async resequenceCollectionItemsRaw(requestParameters: ResequenceCollectionItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.resequenceCollectionItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reassign collection item sequence values from their current order to restore a compact deterministic ordering. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Reapply an automatic ordering to existing collection items
     */
    async resequenceCollectionItems(requestParameters: ResequenceCollectionItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resequenceCollectionItemsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for respondCollectionContributionRequest without sending the request
     */
    async respondCollectionContributionRequestRequestOpts(requestParameters: RespondCollectionContributionRequestOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling respondCollectionContributionRequest().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling respondCollectionContributionRequest().'
            );
        }

        if (requestParameters['respondCollectionContributionRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'respondCollectionContributionRequestRequest',
                'Required parameter "respondCollectionContributionRequestRequest" was null or undefined when calling respondCollectionContributionRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}/contribution-requests/{requestId}`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RespondCollectionContributionRequestRequestToJSON(requestParameters['respondCollectionContributionRequestRequest']),
        };
    }

    /**
     * Approve or decline one pending contribution request and return the resulting request and optional collaborator. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Approve or decline a contribution request
     */
    async respondCollectionContributionRequestRaw(requestParameters: RespondCollectionContributionRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperCollectionContributionDecisionResponse>> {
        const requestOptions = await this.respondCollectionContributionRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperCollectionContributionDecisionResponseFromJSON(jsonValue));
    }

    /**
     * Approve or decline one pending contribution request and return the resulting request and optional collaborator. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Approve or decline a contribution request
     */
    async respondCollectionContributionRequest(requestParameters: RespondCollectionContributionRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperCollectionContributionDecisionResponse> {
        const response = await this.respondCollectionContributionRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCollection without sending the request
     */
    async updateCollectionRequestOpts(requestParameters: UpdateCollectionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling updateCollection().'
            );
        }

        if (requestParameters['updateCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCollectionRequest',
                'Required parameter "updateCollectionRequest" was null or undefined when calling updateCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/{collectionId}`;
        urlPath = urlPath.replace('{collectionId}', encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCollectionRequestToJSON(requestParameters['updateCollectionRequest']),
        };
    }

    /**
     * Update supported collection metadata, visibility, slug, cover, collaboration flag, and item placement. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Update collection metadata
     */
    async updateCollectionRaw(requestParameters: UpdateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperCollectionIdentity>> {
        const requestOptions = await this.updateCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperCollectionIdentityFromJSON(jsonValue));
    }

    /**
     * Update supported collection metadata, visibility, slug, cover, collaboration flag, and item placement. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Update collection metadata
     */
    async updateCollection(requestParameters: UpdateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperCollectionIdentity> {
        const response = await this.updateCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadCollectionCover without sending the request
     */
    async uploadCollectionCoverRequestOpts(requestParameters: UploadCollectionCoverRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['coverImage'] == null) {
            throw new runtime.RequiredError(
                'coverImage',
                'Required parameter "coverImage" was null or undefined when calling uploadCollectionCover().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['coverImage'] != null) {
            formParams.append('coverImage', requestParameters['coverImage'] as any);
        }


        let urlPath = `/api/collections/cover`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload one validated collection-cover image and return the managed relative path plus its safety rating. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Upload and analyse a provisional collection cover
     */
    async uploadCollectionCoverRaw(requestParameters: UploadCollectionCoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperCollectionCoverUploadResponse>> {
        const requestOptions = await this.uploadCollectionCoverRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperCollectionCoverUploadResponseFromJSON(jsonValue));
    }

    /**
     * Upload one validated collection-cover image and return the managed relative path plus its safety rating. The documented owner/staff checks, API-key scope, rate policy, and retry classification apply to every call.
     * Upload and analyse a provisional collection cover
     */
    async uploadCollectionCover(requestParameters: UploadCollectionCoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperCollectionCoverUploadResponse> {
        const response = await this.uploadCollectionCoverRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetCollectionIncludeItemsEnum = {
    True: 'true',
    False: 'false',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GetCollectionIncludeItemsEnum = typeof GetCollectionIncludeItemsEnum[keyof typeof GetCollectionIncludeItemsEnum];
/**
 * @export
 */
export const ListCollectionsTypeEnum = {
    Model: 'MODEL',
    Image: 'IMAGE',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsTypeEnum = typeof ListCollectionsTypeEnum[keyof typeof ListCollectionsTypeEnum];
/**
 * @export
 */
export const ListCollectionsSortEnum = {
    Newest: 'newest',
    Updated: 'updated',
    Items: 'items',
    Collaborators: 'collaborators',
    Alpha: 'alpha',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsSortEnum = typeof ListCollectionsSortEnum[keyof typeof ListCollectionsSortEnum];
/**
 * @export
 */
export const ListCollectionsCollaborativeEnum = {
    True: 'true',
    False: 'false',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsCollaborativeEnum = typeof ListCollectionsCollaborativeEnum[keyof typeof ListCollectionsCollaborativeEnum];
/**
 * @export
 */
export const ListCollectionsScopeEnum = {
    Public: 'public',
    Manageable: 'manageable',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsScopeEnum = typeof ListCollectionsScopeEnum[keyof typeof ListCollectionsScopeEnum];
/**
 * @export
 */
export const ListCollectionsMembershipEnum = {
    Any: 'any',
    Owner: 'owner',
    Collaborator: 'collaborator',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsMembershipEnum = typeof ListCollectionsMembershipEnum[keyof typeof ListCollectionsMembershipEnum];
/**
 * @export
 */
export const ListCollectionsSelfEnum = {
    Favorited: 'favorited',
    Followed: 'followed',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsSelfEnum = typeof ListCollectionsSelfEnum[keyof typeof ListCollectionsSelfEnum];
/**
 * @export
 */
export const ListCollectionsVisibilityEnum = {
    Public: 'PUBLIC',
    Unlisted: 'UNLISTED',
    Private: 'PRIVATE',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsVisibilityEnum = typeof ListCollectionsVisibilityEnum[keyof typeof ListCollectionsVisibilityEnum];
/**
 * @export
 */
export const ListCollectionsRelationshipEnum = {
    Any: 'any',
    Owner: 'owner',
    Collaborator: 'collaborator',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ListCollectionsRelationshipEnum = typeof ListCollectionsRelationshipEnum[keyof typeof ListCollectionsRelationshipEnum];
