/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError.js';
import {
    type CreateWebhookEndpoint201Response,
    CreateWebhookEndpoint201ResponseFromJSON,
    CreateWebhookEndpoint201ResponseToJSON,
} from '../models/CreateWebhookEndpoint201Response.js';
import {
    type CreateWebhookEndpointRequest,
    CreateWebhookEndpointRequestFromJSON,
    CreateWebhookEndpointRequestToJSON,
} from '../models/CreateWebhookEndpointRequest.js';
import {
    type DeveloperWebhookDeliveryResponse,
    DeveloperWebhookDeliveryResponseFromJSON,
    DeveloperWebhookDeliveryResponseToJSON,
} from '../models/DeveloperWebhookDeliveryResponse.js';
import {
    type DeveloperWebhookEndpointResponse,
    DeveloperWebhookEndpointResponseFromJSON,
    DeveloperWebhookEndpointResponseToJSON,
} from '../models/DeveloperWebhookEndpointResponse.js';
import {
    type ListWebhookDeliveries200Response,
    ListWebhookDeliveries200ResponseFromJSON,
    ListWebhookDeliveries200ResponseToJSON,
} from '../models/ListWebhookDeliveries200Response.js';
import {
    type ListWebhookEndpoints200Response,
    ListWebhookEndpoints200ResponseFromJSON,
    ListWebhookEndpoints200ResponseToJSON,
} from '../models/ListWebhookEndpoints200Response.js';
import {
    type ListWebhookEventTypes200Response,
    ListWebhookEventTypes200ResponseFromJSON,
    ListWebhookEventTypes200ResponseToJSON,
} from '../models/ListWebhookEventTypes200Response.js';
import {
    type RotateWebhookSecret200Response,
    RotateWebhookSecret200ResponseFromJSON,
    RotateWebhookSecret200ResponseToJSON,
} from '../models/RotateWebhookSecret200Response.js';
import {
    type TestWebhookEndpoint202Response,
    TestWebhookEndpoint202ResponseFromJSON,
    TestWebhookEndpoint202ResponseToJSON,
} from '../models/TestWebhookEndpoint202Response.js';
import {
    type UpdateWebhookEndpointRequest,
    UpdateWebhookEndpointRequestFromJSON,
    UpdateWebhookEndpointRequestToJSON,
} from '../models/UpdateWebhookEndpointRequest.js';

export interface CreateWebhookEndpointOperationRequest {
    createWebhookEndpointRequest: CreateWebhookEndpointRequest;
    idempotencyKey?: string;
}

export interface DeleteWebhookEndpointRequest {
    endpointId: string;
}

export interface GetWebhookDeliveryRequest {
    deliveryId: string;
}

export interface GetWebhookEndpointRequest {
    endpointId: string;
}

export interface ListWebhookDeliveriesRequest {
    endpointId: string;
    cursor?: string;
    limit?: number;
}

export interface RetryWebhookDeliveryRequest {
    deliveryId: string;
}

export interface RotateWebhookSecretRequest {
    endpointId: string;
}

export interface TestWebhookEndpointRequest {
    endpointId: string;
}

export interface UpdateWebhookEndpointOperationRequest {
    endpointId: string;
    updateWebhookEndpointRequest: UpdateWebhookEndpointRequest;
}

export interface VerifyWebhookEndpointRequest {
    endpointId: string;
}

/**
 *
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWebhookEndpoint without sending the request
     */
    async createWebhookEndpointRequestOpts(requestParameters: CreateWebhookEndpointOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWebhookEndpointRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebhookEndpointRequest',
                'Required parameter "createWebhookEndpointRequest" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookEndpointRequestToJSON(requestParameters['createWebhookEndpointRequest']),
        };
    }

    /**
     * Create a disabled endpoint for an HTTPS port-443 receiver. The signing secret is returned exactly once; store it before completing URL verification.
     * Create an unverified webhook endpoint
     */
    async createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWebhookEndpoint201Response>> {
        const requestOptions = await this.createWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWebhookEndpoint201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a disabled endpoint for an HTTPS port-443 receiver. The signing secret is returned exactly once; store it before completing URL verification.
     * Create an unverified webhook endpoint
     */
    async createWebhookEndpoint(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWebhookEndpoint201Response> {
        const response = await this.createWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWebhookEndpoint without sending the request
     */
    async deleteWebhookEndpointRequestOpts(requestParameters: DeleteWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one caller-owned endpoint and its retained delivery history. Repeating the logical deletion is safe for clients.
     * Delete one owned webhook endpoint
     */
    async deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete one caller-owned endpoint and its retained delivery history. Repeating the logical deletion is safe for clients.
     * Delete one owned webhook endpoint
     */
    async deleteWebhookEndpoint(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWebhookEndpointRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getWebhookDelivery without sending the request
     */
    async getWebhookDeliveryRequestOpts(requestParameters: GetWebhookDeliveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling getWebhookDelivery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/deliveries/{deliveryId}`;
        urlPath = urlPath.replace('{deliveryId}', encodeURIComponent(String(requestParameters['deliveryId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Inspect one caller-owned delivery, its event envelope, attempts, status code, and bounded response snippet.
     * Get one owned delivery and its event
     */
    async getWebhookDeliveryRaw(requestParameters: GetWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperWebhookDeliveryResponse>> {
        const requestOptions = await this.getWebhookDeliveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperWebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Inspect one caller-owned delivery, its event envelope, attempts, status code, and bounded response snippet.
     * Get one owned delivery and its event
     */
    async getWebhookDelivery(requestParameters: GetWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperWebhookDeliveryResponse> {
        const response = await this.getWebhookDeliveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebhookEndpoint without sending the request
     */
    async getWebhookEndpointRequestOpts(requestParameters: GetWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling getWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read one caller-owned endpoint and its bounded health state without exposing signing secrets.
     * Get one owned webhook endpoint
     */
    async getWebhookEndpointRaw(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperWebhookEndpointResponse>> {
        const requestOptions = await this.getWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperWebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Read one caller-owned endpoint and its bounded health state without exposing signing secrets.
     * Get one owned webhook endpoint
     */
    async getWebhookEndpoint(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperWebhookEndpointResponse> {
        const response = await this.getWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookDeliveries without sending the request
     */
    async listWebhookDeliveriesRequestOpts(requestParameters: ListWebhookDeliveriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling listWebhookDeliveries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}/deliveries`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List 30-day delivery history for one caller-owned endpoint using an opaque cursor. Response bodies are truncated and must not be treated as a receiver log.
     * List deliveries for one owned endpoint
     */
    async listWebhookDeliveriesRaw(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWebhookDeliveries200Response>> {
        const requestOptions = await this.listWebhookDeliveriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWebhookDeliveries200ResponseFromJSON(jsonValue));
    }

    /**
     * List 30-day delivery history for one caller-owned endpoint using an opaque cursor. Response bodies are truncated and must not be treated as a receiver log.
     * List deliveries for one owned endpoint
     */
    async listWebhookDeliveries(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWebhookDeliveries200Response> {
        const response = await this.listWebhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookEndpoints without sending the request
     */
    async listWebhookEndpointsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webhook endpoints owned by the authenticated caller. Signing-secret material and every other user’s endpoints are always excluded.
     * List owned webhook endpoints
     */
    async listWebhookEndpointsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWebhookEndpoints200Response>> {
        const requestOptions = await this.listWebhookEndpointsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWebhookEndpoints200ResponseFromJSON(jsonValue));
    }

    /**
     * List webhook endpoints owned by the authenticated caller. Signing-secret material and every other user’s endpoints are always excluded.
     * List owned webhook endpoints
     */
    async listWebhookEndpoints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWebhookEndpoints200Response> {
        const response = await this.listWebhookEndpointsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookEventTypes without sending the request
     */
    async listWebhookEventTypesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/event-types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the public event names and payload versions supported by Developer Webhooks. Discover this catalog instead of using undocumented staff event names.
     * List supported webhook event types
     */
    async listWebhookEventTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWebhookEventTypes200Response>> {
        const requestOptions = await this.listWebhookEventTypesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWebhookEventTypes200ResponseFromJSON(jsonValue));
    }

    /**
     * List the public event names and payload versions supported by Developer Webhooks. Discover this catalog instead of using undocumented staff event names.
     * List supported webhook event types
     */
    async listWebhookEventTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWebhookEventTypes200Response> {
        const response = await this.listWebhookEventTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retryWebhookDelivery without sending the request
     */
    async retryWebhookDeliveryRequestOpts(requestParameters: RetryWebhookDeliveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling retryWebhookDelivery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/deliveries/{deliveryId}/retry`;
        urlPath = urlPath.replace('{deliveryId}', encodeURIComponent(String(requestParameters['deliveryId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return one failed caller-owned delivery to the queue. Receivers must deduplicate by event or delivery identifier because delivery is at least once.
     * Retry one failed owned delivery
     */
    async retryWebhookDeliveryRaw(requestParameters: RetryWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperWebhookDeliveryResponse>> {
        const requestOptions = await this.retryWebhookDeliveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperWebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Return one failed caller-owned delivery to the queue. Receivers must deduplicate by event or delivery identifier because delivery is at least once.
     * Retry one failed owned delivery
     */
    async retryWebhookDelivery(requestParameters: RetryWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperWebhookDeliveryResponse> {
        const response = await this.retryWebhookDeliveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateWebhookSecret without sending the request
     */
    async rotateWebhookSecretRequestOpts(requestParameters: RotateWebhookSecretRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling rotateWebhookSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}/rotate-secret`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Generate a new one-time signing secret while retaining the previous signature for a 24-hour overlap. Do not retry automatically after an ambiguous response.
     * Rotate the signing secret with 24-hour overlap
     */
    async rotateWebhookSecretRaw(requestParameters: RotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RotateWebhookSecret200Response>> {
        const requestOptions = await this.rotateWebhookSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RotateWebhookSecret200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate a new one-time signing secret while retaining the previous signature for a 24-hour overlap. Do not retry automatically after an ambiguous response.
     * Rotate the signing secret with 24-hour overlap
     */
    async rotateWebhookSecret(requestParameters: RotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RotateWebhookSecret200Response> {
        const response = await this.rotateWebhookSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for testWebhookEndpoint without sending the request
     */
    async testWebhookEndpointRequestOpts(requestParameters: TestWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling testWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}/test`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Queue a signed webhook.test delivery through the normal dispatcher so receivers can validate headers and duplicate handling.
     * Queue a signed test delivery
     */
    async testWebhookEndpointRaw(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TestWebhookEndpoint202Response>> {
        const requestOptions = await this.testWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TestWebhookEndpoint202ResponseFromJSON(jsonValue));
    }

    /**
     * Queue a signed webhook.test delivery through the normal dispatcher so receivers can validate headers and duplicate handling.
     * Queue a signed test delivery
     */
    async testWebhookEndpoint(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TestWebhookEndpoint202Response> {
        const response = await this.testWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWebhookEndpoint without sending the request
     */
    async updateWebhookEndpointRequestOpts(requestParameters: UpdateWebhookEndpointOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        if (requestParameters['updateWebhookEndpointRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWebhookEndpointRequest',
                'Required parameter "updateWebhookEndpointRequest" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWebhookEndpointRequestToJSON(requestParameters['updateWebhookEndpointRequest']),
        };
    }

    /**
     * Update endpoint metadata, subscriptions, state, or URL. A URL change disables the endpoint and requires a fresh verification challenge.
     * Update one owned webhook endpoint
     */
    async updateWebhookEndpointRaw(requestParameters: UpdateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperWebhookEndpointResponse>> {
        const requestOptions = await this.updateWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperWebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Update endpoint metadata, subscriptions, state, or URL. A URL change disables the endpoint and requires a fresh verification challenge.
     * Update one owned webhook endpoint
     */
    async updateWebhookEndpoint(requestParameters: UpdateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperWebhookEndpointResponse> {
        const response = await this.updateWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyWebhookEndpoint without sending the request
     */
    async verifyWebhookEndpointRequestOpts(requestParameters: VerifyWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling verifyWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/webhooks/endpoints/{endpointId}/verify`;
        urlPath = urlPath.replace('{endpointId}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Send a one-time URL-verification challenge. The receiver must return the exact challenge in a successful JSON response before deliveries are enabled.
     * Verify ownership and reachability using a challenge
     */
    async verifyWebhookEndpointRaw(requestParameters: VerifyWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeveloperWebhookEndpointResponse>> {
        const requestOptions = await this.verifyWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeveloperWebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Send a one-time URL-verification challenge. The receiver must return the exact challenge in a successful JSON response before deliveries are enabled.
     * Verify ownership and reachability using a challenge
     */
    async verifyWebhookEndpoint(requestParameters: VerifyWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeveloperWebhookEndpointResponse> {
        const response = await this.verifyWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
