/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Article used by the Arc en Ciel API contract.
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * Bumped At accepted or returned by this contract.
     * @type {Date}
     * @memberof Article
     */
    bumpedAt?: Date;
    /**
     * Sanitized rich HTML article body. Existing legacy Markdown remains render-compatible during migration.
     * @type {string}
     * @memberof Article
     */
    content?: string;
    /**
     * Content Bumped At accepted or returned by this contract.
     * @type {Date}
     * @memberof Article
     */
    contentBumpedAt?: Date;
    /**
     * Created At accepted or returned by this contract.
     * @type {Date}
     * @memberof Article
     */
    createdAt?: Date;
    /**
     * Id accepted or returned by this contract.
     * @type {number}
     * @memberof Article
     */
    id?: number;
    /**
     * Tags accepted or returned by this contract.
     * @type {Array<string>}
     * @memberof Article
     */
    tags?: Array<string>;
    /**
     * Thumbnail File accepted or returned by this contract.
     * @type {string}
     * @memberof Article
     */
    thumbnailFile?: string;
    /**
     * Title accepted or returned by this contract.
     * @type {string}
     * @memberof Article
     */
    title?: string;
    /**
     * Updated At accepted or returned by this contract.
     * @type {Date}
     * @memberof Article
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): value is Article {
    return true;
}

export function ArticleFromJSON(json: any): Article {
    return ArticleFromJSONTyped(json, false);
}

export function ArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Article {
    if (json == null) {
        return json;
    }
    return {

        'bumpedAt': json['bumpedAt'] == null ? undefined : (new Date(json['bumpedAt'])),
        'content': json['content'] == null ? undefined : json['content'],
        'contentBumpedAt': json['contentBumpedAt'] == null ? undefined : (new Date(json['contentBumpedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'thumbnailFile': json['thumbnailFile'] == null ? undefined : json['thumbnailFile'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ArticleToJSON(json: any): Article {
    return ArticleToJSONTyped(json, false);
}

export function ArticleToJSONTyped(value?: Article | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'bumpedAt': value['bumpedAt'] == null ? value['bumpedAt'] : value['bumpedAt'].toISOString(),
        'content': value['content'],
        'contentBumpedAt': value['contentBumpedAt'] == null ? value['contentBumpedAt'] : value['contentBumpedAt'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'id': value['id'],
        'tags': value['tags'],
        'thumbnailFile': value['thumbnailFile'],
        'title': value['title'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}
