/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Collab Collection Summary used by the Arc en Ciel API contract.
 * @export
 * @interface CollabCollectionSummary
 */
export interface CollabCollectionSummary {
    /**
     * Cover Image accepted or returned by this contract.
     * @type {string}
     * @memberof CollabCollectionSummary
     */
    coverImage?: string | null;
    /**
     * Cover Image Rating accepted or returned by this contract.
     * @type {string}
     * @memberof CollabCollectionSummary
     */
    coverImageRating?: string | null;
    /**
     * Id accepted or returned by this contract.
     * @type {number}
     * @memberof CollabCollectionSummary
     */
    id: number;
    /**
     * Model Count accepted or returned by this contract.
     * @type {number}
     * @memberof CollabCollectionSummary
     */
    modelCount: number;
    /**
     * Name accepted or returned by this contract.
     * @type {string}
     * @memberof CollabCollectionSummary
     */
    name: string;
    /**
     * Slug accepted or returned by this contract.
     * @type {string}
     * @memberof CollabCollectionSummary
     */
    slug: string;
    /**
     * Visibility accepted or returned by this contract.
     * @type {CollabCollectionSummaryVisibilityEnum}
     * @memberof CollabCollectionSummary
     */
    visibility: CollabCollectionSummaryVisibilityEnum;
}


/**
 * @export
 */
export const CollabCollectionSummaryVisibilityEnum = {
    Public: 'PUBLIC',
    Unlisted: 'UNLISTED',
    Private: 'PRIVATE',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type CollabCollectionSummaryVisibilityEnum = typeof CollabCollectionSummaryVisibilityEnum[keyof typeof CollabCollectionSummaryVisibilityEnum];


/**
 * Check if a given object implements the CollabCollectionSummary interface.
 */
export function instanceOfCollabCollectionSummary(value: object): value is CollabCollectionSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('modelCount' in value) || value['modelCount'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function CollabCollectionSummaryFromJSON(json: any): CollabCollectionSummary {
    return CollabCollectionSummaryFromJSONTyped(json, false);
}

export function CollabCollectionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollabCollectionSummary {
    if (json == null) {
        return json;
    }
    return {

        'coverImage': json['coverImage'] === undefined ? undefined : json['coverImage'] === null ? null : json['coverImage'],
        'coverImageRating': json['coverImageRating'] === undefined ? undefined : json['coverImageRating'] === null ? null : json['coverImageRating'],
        'id': json['id'],
        'modelCount': json['modelCount'],
        'name': json['name'],
        'slug': json['slug'],
        'visibility': json['visibility'],
    };
}

export function CollabCollectionSummaryToJSON(json: any): CollabCollectionSummary {
    return CollabCollectionSummaryToJSONTyped(json, false);
}

export function CollabCollectionSummaryToJSONTyped(value?: CollabCollectionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'coverImage': value['coverImage'],
        'coverImageRating': value['coverImageRating'],
        'id': value['id'],
        'modelCount': value['modelCount'],
        'name': value['name'],
        'slug': value['slug'],
        'visibility': value['visibility'],
    };
}
