/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CollectionItemPage } from './CollectionItemPage.js';
import {
    CollectionItemPageFromJSON,
    CollectionItemPageFromJSONTyped,
    CollectionItemPageToJSON,
    CollectionItemPageToJSONTyped,
} from './CollectionItemPage.js';

/**
 * Fields describing collection pagination in Developer API requests and responses.
 * @export
 * @interface CollectionPagination
 */
export interface CollectionPagination {
    /**
     *
     * @type {CollectionItemPage}
     * @memberof CollectionPagination
     */
    images: CollectionItemPage;
    /**
     *
     * @type {CollectionItemPage}
     * @memberof CollectionPagination
     */
    models: CollectionItemPage;
}

/**
 * Check if a given object implements the CollectionPagination interface.
 */
export function instanceOfCollectionPagination(value: object): value is CollectionPagination {
    if (!('images' in value) || value['images'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    return true;
}

export function CollectionPaginationFromJSON(json: any): CollectionPagination {
    return CollectionPaginationFromJSONTyped(json, false);
}

export function CollectionPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionPagination {
    if (json == null) {
        return json;
    }
    return {

        'images': CollectionItemPageFromJSON(json['images']),
        'models': CollectionItemPageFromJSON(json['models']),
    };
}

export function CollectionPaginationToJSON(json: any): CollectionPagination {
    return CollectionPaginationToJSONTyped(json, false);
}

export function CollectionPaginationToJSONTyped(value?: CollectionPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'images': CollectionItemPageToJSON(value['images']),
        'models': CollectionItemPageToJSON(value['models']),
    };
}
