/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Applied Range accepted or returned by this contract.
 * @export
 * @interface CreatorStatsAppliedRange
 */
export interface CreatorStatsAppliedRange {
    /**
     * Inclusive applied range end.
     * @type {Date}
     * @memberof CreatorStatsAppliedRange
     */
    end: Date;
    /**
     * Inclusive applied range start.
     * @type {Date}
     * @memberof CreatorStatsAppliedRange
     */
    start: Date;
}

/**
 * Check if a given object implements the CreatorStatsAppliedRange interface.
 */
export function instanceOfCreatorStatsAppliedRange(value: object): value is CreatorStatsAppliedRange {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function CreatorStatsAppliedRangeFromJSON(json: any): CreatorStatsAppliedRange {
    return CreatorStatsAppliedRangeFromJSONTyped(json, false);
}

export function CreatorStatsAppliedRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorStatsAppliedRange {
    if (json == null) {
        return json;
    }
    return {

        'end': (new Date(json['end'])),
        'start': (new Date(json['start'])),
    };
}

export function CreatorStatsAppliedRangeToJSON(json: any): CreatorStatsAppliedRange {
    return CreatorStatsAppliedRangeToJSONTyped(json, false);
}

export function CreatorStatsAppliedRangeToJSONTyped(value?: CreatorStatsAppliedRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'end': value['end'].toISOString(),
        'start': value['start'].toISOString(),
    };
}
