/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CreateGeneratorJobRequestExtraSeed
 * A1111-like secondary seed (subseed equivalent) used for noise variation.
 * @export
 */
export type CreateGeneratorJobRequestExtraSeed = number | string;

export function CreateGeneratorJobRequestExtraSeedFromJSON(json: any): CreateGeneratorJobRequestExtraSeed {
    return CreateGeneratorJobRequestExtraSeedFromJSONTyped(json, false);
}

export function CreateGeneratorJobRequestExtraSeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGeneratorJobRequestExtraSeed {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function CreateGeneratorJobRequestExtraSeedToJSON(json: any): any {
    return CreateGeneratorJobRequestExtraSeedToJSONTyped(json, false);
}

export function CreateGeneratorJobRequestExtraSeedToJSONTyped(value?: CreateGeneratorJobRequestExtraSeed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}
