/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request payload used by the Arc en Ciel API contract.
 * @export
 * @interface CreateWebhookEndpointRequest
 */
export interface CreateWebhookEndpointRequest {
    /**
     * Event Types accepted or returned by this contract.
     * @type {Set<string>}
     * @memberof CreateWebhookEndpointRequest
     */
    eventTypes: Set<string>;
    /**
     * Name accepted or returned by this contract.
     * @type {string}
     * @memberof CreateWebhookEndpointRequest
     */
    name: string;
    /**
     * Url accepted or returned by this contract.
     * @type {string}
     * @memberof CreateWebhookEndpointRequest
     */
    url: string;
}

/**
 * Check if a given object implements the CreateWebhookEndpointRequest interface.
 */
export function instanceOfCreateWebhookEndpointRequest(value: object): value is CreateWebhookEndpointRequest {
    if (!('eventTypes' in value) || value['eventTypes'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpointRequestFromJSON(json: any): CreateWebhookEndpointRequest {
    return CreateWebhookEndpointRequestFromJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpointRequest {
    if (json == null) {
        return json;
    }
    return {

        'eventTypes': new Set(json['eventTypes']),
        'name': json['name'],
        'url': json['url'],
    };
}

export function CreateWebhookEndpointRequestToJSON(json: any): CreateWebhookEndpointRequest {
    return CreateWebhookEndpointRequestToJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestToJSONTyped(value?: CreateWebhookEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'eventTypes': Array.from(value['eventTypes'] as Set<any>),
        'name': value['name'],
        'url': value['url'],
    };
}
