/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface CreateChatGroupRequest
 */
export interface CreateChatGroupRequest {
    /**
     * Optional group display title.
     * @type {string}
     * @memberof CreateChatGroupRequest
     */
    title?: string | null;
    /**
     * Existing users to invite as pending members.
     * @type {Set<number>}
     * @memberof CreateChatGroupRequest
     */
    userIds?: Set<number>;
}

/**
 * Check if a given object implements the CreateChatGroupRequest interface.
 */
export function instanceOfCreateChatGroupRequest(value: object): value is CreateChatGroupRequest {
    return true;
}

export function CreateChatGroupRequestFromJSON(json: any): CreateChatGroupRequest {
    return CreateChatGroupRequestFromJSONTyped(json, false);
}

export function CreateChatGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatGroupRequest {
    if (json == null) {
        return json;
    }
    return {

        'title': json['title'] === undefined ? undefined : json['title'] === null ? null : json['title'],
        'userIds': json['userIds'] == null ? undefined : new Set(json['userIds']),
    };
}

export function CreateChatGroupRequestToJSON(json: any): CreateChatGroupRequest {
    return CreateChatGroupRequestToJSONTyped(json, false);
}

export function CreateChatGroupRequestToJSONTyped(value?: CreateChatGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'title': value['title'],
        'userIds': value['userIds'] == null ? undefined : Array.from(value['userIds'] as Set<any>),
    };
}
