/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Regions item used by the Arc en Ciel API contract.
 * @export
 * @interface CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner
 */
export interface CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner {
    /**
     * Relative staging path (`generator/...`) to a PNG mask with an alpha channel.
     * @type {string}
     * @memberof CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner
     */
    maskPath: string;
    /**
     * Prompt accepted or returned by this contract.
     * @type {string}
     * @memberof CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner
     */
    prompt: string;
    /**
     * Weight accepted or returned by this contract.
     * @type {number}
     * @memberof CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner
     */
    weight?: number;
}

/**
 * Check if a given object implements the CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner interface.
 */
export function instanceOfCreateGeneratorCompareRunRequestAttentionCoupleRegionsInner(value: object): value is CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner {
    if (!('maskPath' in value) || value['maskPath'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function CreateGeneratorCompareRunRequestAttentionCoupleRegionsInnerFromJSON(json: any): CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner {
    return CreateGeneratorCompareRunRequestAttentionCoupleRegionsInnerFromJSONTyped(json, false);
}

export function CreateGeneratorCompareRunRequestAttentionCoupleRegionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner {
    if (json == null) {
        return json;
    }
    return {

        'maskPath': json['maskPath'],
        'prompt': json['prompt'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function CreateGeneratorCompareRunRequestAttentionCoupleRegionsInnerToJSON(json: any): CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner {
    return CreateGeneratorCompareRunRequestAttentionCoupleRegionsInnerToJSONTyped(json, false);
}

export function CreateGeneratorCompareRunRequestAttentionCoupleRegionsInnerToJSONTyped(value?: CreateGeneratorCompareRunRequestAttentionCoupleRegionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'maskPath': value['maskPath'],
        'prompt': value['prompt'],
        'weight': value['weight'],
    };
}
