/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Upscale Profiles item used by the Arc en Ciel API contract.
 * @export
 * @interface CreateGeneratorJobRequestUpscaleProfilesInner
 */
export interface CreateGeneratorJobRequestUpscaleProfilesInner {
    /**
     * Denoise strength for the refinement pass. x4 upscalers require a target `scaleFactor`.
     * @type {number}
     * @memberof CreateGeneratorJobRequestUpscaleProfilesInner
     */
    denoise?: number;
    /**
     * Compatibility alias for `modelName`.
     * @type {string}
     * @memberof CreateGeneratorJobRequestUpscaleProfilesInner
     */
    model?: string;
    /**
     * Model Name accepted or returned by this contract.
     * @type {string}
     * @memberof CreateGeneratorJobRequestUpscaleProfilesInner
     */
    modelName?: string;
    /**
     * Compatibility alias for `modelName`.
     * @type {string}
     * @memberof CreateGeneratorJobRequestUpscaleProfilesInner
     */
    upscaleModelName?: string;
}

/**
 * Check if a given object implements the CreateGeneratorJobRequestUpscaleProfilesInner interface.
 */
export function instanceOfCreateGeneratorJobRequestUpscaleProfilesInner(value: object): value is CreateGeneratorJobRequestUpscaleProfilesInner {
    return true;
}

export function CreateGeneratorJobRequestUpscaleProfilesInnerFromJSON(json: any): CreateGeneratorJobRequestUpscaleProfilesInner {
    return CreateGeneratorJobRequestUpscaleProfilesInnerFromJSONTyped(json, false);
}

export function CreateGeneratorJobRequestUpscaleProfilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGeneratorJobRequestUpscaleProfilesInner {
    if (json == null) {
        return json;
    }
    return {

        'denoise': json['denoise'] == null ? undefined : json['denoise'],
        'model': json['model'] == null ? undefined : json['model'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
        'upscaleModelName': json['upscaleModelName'] == null ? undefined : json['upscaleModelName'],
    };
}

export function CreateGeneratorJobRequestUpscaleProfilesInnerToJSON(json: any): CreateGeneratorJobRequestUpscaleProfilesInner {
    return CreateGeneratorJobRequestUpscaleProfilesInnerToJSONTyped(json, false);
}

export function CreateGeneratorJobRequestUpscaleProfilesInnerToJSONTyped(value?: CreateGeneratorJobRequestUpscaleProfilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'denoise': value['denoise'],
        'model': value['model'],
        'modelName': value['modelName'],
        'upscaleModelName': value['upscaleModelName'],
    };
}
