/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CreateGeneratorCompareRunRequestSeed
 * Shared seed. Omit or send `-1` to randomize once for the whole compare run.
 * @export
 */
export type CreateGeneratorCompareRunRequestSeed = number | string;

export function CreateGeneratorCompareRunRequestSeedFromJSON(json: any): CreateGeneratorCompareRunRequestSeed {
    return CreateGeneratorCompareRunRequestSeedFromJSONTyped(json, false);
}

export function CreateGeneratorCompareRunRequestSeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGeneratorCompareRunRequestSeed {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    return {} as any;
}

export function CreateGeneratorCompareRunRequestSeedToJSON(json: any): any {
    return CreateGeneratorCompareRunRequestSeedToJSONTyped(json, false);
}

export function CreateGeneratorCompareRunRequestSeedToJSONTyped(value?: CreateGeneratorCompareRunRequestSeed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    return {};
}
