/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Reactions accepted or returned by this contract.
 * @export
 * @interface CreatorStatsResponseReactions
 */
export interface CreatorStatsResponseReactions {
    /**
     * Dislikes accepted or returned by this contract.
     * @type {number}
     * @memberof CreatorStatsResponseReactions
     */
    dislikes: number;
    /**
     * Hearts accepted or returned by this contract.
     * @type {number}
     * @memberof CreatorStatsResponseReactions
     */
    hearts: number;
    /**
     * Likes accepted or returned by this contract.
     * @type {number}
     * @memberof CreatorStatsResponseReactions
     */
    likes: number;
}

/**
 * Check if a given object implements the CreatorStatsResponseReactions interface.
 */
export function instanceOfCreatorStatsResponseReactions(value: object): value is CreatorStatsResponseReactions {
    if (!('dislikes' in value) || value['dislikes'] === undefined) return false;
    if (!('hearts' in value) || value['hearts'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    return true;
}

export function CreatorStatsResponseReactionsFromJSON(json: any): CreatorStatsResponseReactions {
    return CreatorStatsResponseReactionsFromJSONTyped(json, false);
}

export function CreatorStatsResponseReactionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorStatsResponseReactions {
    if (json == null) {
        return json;
    }
    return {

        'dislikes': json['dislikes'],
        'hearts': json['hearts'],
        'likes': json['likes'],
    };
}

export function CreatorStatsResponseReactionsToJSON(json: any): CreatorStatsResponseReactions {
    return CreatorStatsResponseReactionsToJSONTyped(json, false);
}

export function CreatorStatsResponseReactionsToJSONTyped(value?: CreatorStatsResponseReactions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'dislikes': value['dislikes'],
        'hearts': value['hearts'],
        'likes': value['likes'],
    };
}
