/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface DeveloperChatPresenceEntry
 */
export interface DeveloperChatPresenceEntry {
    /**
     *
     * @type {Date}
     * @memberof DeveloperChatPresenceEntry
     */
    lastSeenAt: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof DeveloperChatPresenceEntry
     */
    online: boolean;
}

/**
 * Check if a given object implements the DeveloperChatPresenceEntry interface.
 */
export function instanceOfDeveloperChatPresenceEntry(value: object): value is DeveloperChatPresenceEntry {
    if (!('lastSeenAt' in value) || value['lastSeenAt'] === undefined) return false;
    if (!('online' in value) || value['online'] === undefined) return false;
    return true;
}

export function DeveloperChatPresenceEntryFromJSON(json: any): DeveloperChatPresenceEntry {
    return DeveloperChatPresenceEntryFromJSONTyped(json, false);
}

export function DeveloperChatPresenceEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperChatPresenceEntry {
    if (json == null) {
        return json;
    }
    return {

        'lastSeenAt': (json['lastSeenAt'] == null ? null : new Date(json['lastSeenAt'])),
        'online': json['online'],
    };
}

export function DeveloperChatPresenceEntryToJSON(json: any): DeveloperChatPresenceEntry {
    return DeveloperChatPresenceEntryToJSONTyped(json, false);
}

export function DeveloperChatPresenceEntryToJSONTyped(value?: DeveloperChatPresenceEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'lastSeenAt': value['lastSeenAt'] == null ? value['lastSeenAt'] : value['lastSeenAt'].toISOString(),
        'online': value['online'],
    };
}
