/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface DeveloperNotificationComment
 */
export interface DeveloperNotificationComment {
    /**
     *
     * @type {number}
     * @memberof DeveloperNotificationComment
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof DeveloperNotificationComment
     */
    targetId: number;
    /**
     *
     * @type {string}
     * @memberof DeveloperNotificationComment
     */
    targetType: string;
}

/**
 * Check if a given object implements the DeveloperNotificationComment interface.
 */
export function instanceOfDeveloperNotificationComment(value: object): value is DeveloperNotificationComment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    if (!('targetType' in value) || value['targetType'] === undefined) return false;
    return true;
}

export function DeveloperNotificationCommentFromJSON(json: any): DeveloperNotificationComment {
    return DeveloperNotificationCommentFromJSONTyped(json, false);
}

export function DeveloperNotificationCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperNotificationComment {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'targetId': json['targetId'],
        'targetType': json['targetType'],
    };
}

export function DeveloperNotificationCommentToJSON(json: any): DeveloperNotificationComment {
    return DeveloperNotificationCommentToJSONTyped(json, false);
}

export function DeveloperNotificationCommentToJSONTyped(value?: DeveloperNotificationComment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'targetId': value['targetId'],
        'targetType': value['targetType'],
    };
}
