/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Developer Webhook Event Type used by the Arc en Ciel API contract.
 * @export
 * @interface DeveloperWebhookEventType
 */
export interface DeveloperWebhookEventType {
    /**
     * Description accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEventType
     */
    description: string;
    /**
     * Type accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEventType
     */
    type: string;
    /**
     * Version accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEventType
     */
    version: string;
}

/**
 * Check if a given object implements the DeveloperWebhookEventType interface.
 */
export function instanceOfDeveloperWebhookEventType(value: object): value is DeveloperWebhookEventType {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DeveloperWebhookEventTypeFromJSON(json: any): DeveloperWebhookEventType {
    return DeveloperWebhookEventTypeFromJSONTyped(json, false);
}

export function DeveloperWebhookEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperWebhookEventType {
    if (json == null) {
        return json;
    }
    return {

        'description': json['description'],
        'type': json['type'],
        'version': json['version'],
    };
}

export function DeveloperWebhookEventTypeToJSON(json: any): DeveloperWebhookEventType {
    return DeveloperWebhookEventTypeToJSONTyped(json, false);
}

export function DeveloperWebhookEventTypeToJSONTyped(value?: DeveloperWebhookEventType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'description': value['description'],
        'type': value['type'],
        'version': value['version'],
    };
}
