/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Developer Webhook Endpoint used by the Arc en Ciel API contract.
 * @export
 * @interface DeveloperWebhookEndpoint
 */
export interface DeveloperWebhookEndpoint {
    /**
     * Auto Disabled At accepted or returned by this contract.
     * @type {Date}
     * @memberof DeveloperWebhookEndpoint
     */
    autoDisabledAt?: Date | null;
    /**
     * Consecutive Failure Count accepted or returned by this contract.
     * @type {number}
     * @memberof DeveloperWebhookEndpoint
     */
    consecutiveFailureCount: number;
    /**
     * Created At accepted or returned by this contract.
     * @type {Date}
     * @memberof DeveloperWebhookEndpoint
     */
    createdAt: Date;
    /**
     * Enabled accepted or returned by this contract.
     * @type {boolean}
     * @memberof DeveloperWebhookEndpoint
     */
    enabled: boolean;
    /**
     * Event Types accepted or returned by this contract.
     * @type {Array<string>}
     * @memberof DeveloperWebhookEndpoint
     */
    eventTypes: Array<string>;
    /**
     * Id accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEndpoint
     */
    id: string;
    /**
     * Last Delivered At accepted or returned by this contract.
     * @type {Date}
     * @memberof DeveloperWebhookEndpoint
     */
    lastDeliveredAt?: Date | null;
    /**
     * Last Error accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEndpoint
     */
    lastError?: string | null;
    /**
     * Name accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEndpoint
     */
    name: string;
    /**
     * Secret Last Rotated At accepted or returned by this contract.
     * @type {Date}
     * @memberof DeveloperWebhookEndpoint
     */
    secretLastRotatedAt?: Date;
    /**
     * Updated At accepted or returned by this contract.
     * @type {Date}
     * @memberof DeveloperWebhookEndpoint
     */
    updatedAt: Date;
    /**
     * Url accepted or returned by this contract.
     * @type {string}
     * @memberof DeveloperWebhookEndpoint
     */
    url: string;
    /**
     * Verified At accepted or returned by this contract.
     * @type {Date}
     * @memberof DeveloperWebhookEndpoint
     */
    verifiedAt?: Date | null;
}

/**
 * Check if a given object implements the DeveloperWebhookEndpoint interface.
 */
export function instanceOfDeveloperWebhookEndpoint(value: object): value is DeveloperWebhookEndpoint {
    if (!('consecutiveFailureCount' in value) || value['consecutiveFailureCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('eventTypes' in value) || value['eventTypes'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DeveloperWebhookEndpointFromJSON(json: any): DeveloperWebhookEndpoint {
    return DeveloperWebhookEndpointFromJSONTyped(json, false);
}

export function DeveloperWebhookEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperWebhookEndpoint {
    if (json == null) {
        return json;
    }
    return {

        'autoDisabledAt': json['autoDisabledAt'] === undefined ? undefined : json['autoDisabledAt'] === null ? null : (new Date(json['autoDisabledAt'])),
        'consecutiveFailureCount': json['consecutiveFailureCount'],
        'createdAt': (new Date(json['createdAt'])),
        'enabled': json['enabled'],
        'eventTypes': json['eventTypes'],
        'id': json['id'],
        'lastDeliveredAt': json['lastDeliveredAt'] === undefined ? undefined : json['lastDeliveredAt'] === null ? null : (new Date(json['lastDeliveredAt'])),
        'lastError': json['lastError'] === undefined ? undefined : json['lastError'] === null ? null : json['lastError'],
        'name': json['name'],
        'secretLastRotatedAt': json['secretLastRotatedAt'] == null ? undefined : (new Date(json['secretLastRotatedAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'url': json['url'],
        'verifiedAt': json['verifiedAt'] === undefined ? undefined : json['verifiedAt'] === null ? null : (new Date(json['verifiedAt'])),
    };
}

export function DeveloperWebhookEndpointToJSON(json: any): DeveloperWebhookEndpoint {
    return DeveloperWebhookEndpointToJSONTyped(json, false);
}

export function DeveloperWebhookEndpointToJSONTyped(value?: DeveloperWebhookEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'autoDisabledAt': value['autoDisabledAt'] == null ? value['autoDisabledAt'] : value['autoDisabledAt'].toISOString(),
        'consecutiveFailureCount': value['consecutiveFailureCount'],
        'createdAt': value['createdAt'].toISOString(),
        'enabled': value['enabled'],
        'eventTypes': value['eventTypes'],
        'id': value['id'],
        'lastDeliveredAt': value['lastDeliveredAt'] == null ? value['lastDeliveredAt'] : value['lastDeliveredAt'].toISOString(),
        'lastError': value['lastError'],
        'name': value['name'],
        'secretLastRotatedAt': value['secretLastRotatedAt'] == null ? value['secretLastRotatedAt'] : value['secretLastRotatedAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'url': value['url'],
        'verifiedAt': value['verifiedAt'] == null ? value['verifiedAt'] : value['verifiedAt'].toISOString(),
    };
}
