/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DeveloperChatDirectStateResponse } from './DeveloperChatDirectStateResponse.js';
import {
    instanceOfDeveloperChatDirectStateResponse,
    DeveloperChatDirectStateResponseFromJSON,
    DeveloperChatDirectStateResponseFromJSONTyped,
    DeveloperChatDirectStateResponseToJSON,
} from './DeveloperChatDirectStateResponse.js';
import type { DeveloperChatMessage } from './DeveloperChatMessage.js';
import {
    instanceOfDeveloperChatMessage,
    DeveloperChatMessageFromJSON,
    DeveloperChatMessageFromJSONTyped,
    DeveloperChatMessageToJSON,
} from './DeveloperChatMessage.js';
import type { DeveloperChatThread } from './DeveloperChatThread.js';
import {
    instanceOfDeveloperChatThread,
    DeveloperChatThreadFromJSON,
    DeveloperChatThreadFromJSONTyped,
    DeveloperChatThreadToJSON,
} from './DeveloperChatThread.js';

/**
 * @type DeveloperChatRequestResponse
 * An existing direct-state summary, a newly or previously resolved thread, or a newly created message when the convenience route sends into an active thread.
 * @export
 */
export type DeveloperChatRequestResponse = DeveloperChatDirectStateResponse | DeveloperChatMessage | DeveloperChatThread;

export function DeveloperChatRequestResponseFromJSON(json: any): DeveloperChatRequestResponse {
    return DeveloperChatRequestResponseFromJSONTyped(json, false);
}

export function DeveloperChatRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperChatRequestResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDeveloperChatDirectStateResponse(json)) {
        return DeveloperChatDirectStateResponseFromJSONTyped(json, true);
    }
    if (instanceOfDeveloperChatMessage(json)) {
        return DeveloperChatMessageFromJSONTyped(json, true);
    }
    if (instanceOfDeveloperChatThread(json)) {
        return DeveloperChatThreadFromJSONTyped(json, true);
    }
    return {} as any;
}

export function DeveloperChatRequestResponseToJSON(json: any): any {
    return DeveloperChatRequestResponseToJSONTyped(json, false);
}

export function DeveloperChatRequestResponseToJSONTyped(value?: DeveloperChatRequestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDeveloperChatDirectStateResponse(value)) {
        return DeveloperChatDirectStateResponseToJSON(value as DeveloperChatDirectStateResponse);
    }
    if (instanceOfDeveloperChatMessage(value)) {
        return DeveloperChatMessageToJSON(value as DeveloperChatMessage);
    }
    if (instanceOfDeveloperChatThread(value)) {
        return DeveloperChatThreadToJSON(value as DeveloperChatThread);
    }
    return {};
}
