/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, public and personal profiles, visible media, social interactions, notifications, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 423 response for api models model Id versions version Id download download Name used by the Arc en Ciel API contract.
 * @export
 * @interface DownloadModelVersionWithFilename423Response
 */
export interface DownloadModelVersionWithFilename423Response {
    /**
     * Error accepted or returned by this contract.
     * @type {string}
     * @memberof DownloadModelVersionWithFilename423Response
     */
    error?: string;
}

/**
 * Check if a given object implements the DownloadModelVersionWithFilename423Response interface.
 */
export function instanceOfDownloadModelVersionWithFilename423Response(value: object): value is DownloadModelVersionWithFilename423Response {
    return true;
}

export function DownloadModelVersionWithFilename423ResponseFromJSON(json: any): DownloadModelVersionWithFilename423Response {
    return DownloadModelVersionWithFilename423ResponseFromJSONTyped(json, false);
}

export function DownloadModelVersionWithFilename423ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadModelVersionWithFilename423Response {
    if (json == null) {
        return json;
    }
    return {

        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function DownloadModelVersionWithFilename423ResponseToJSON(json: any): DownloadModelVersionWithFilename423Response {
    return DownloadModelVersionWithFilename423ResponseToJSONTyped(json, false);
}

export function DownloadModelVersionWithFilename423ResponseToJSONTyped(value?: DownloadModelVersionWithFilename423Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': value['error'],
    };
}
