/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type GeneratorJobRemixRequestSeed
 * Seed associated with this generator job remix request; preserve server-returned values when passing them to another operation.
 * @export
 */
export type GeneratorJobRemixRequestSeed = number | string;

export function GeneratorJobRemixRequestSeedFromJSON(json: any): GeneratorJobRemixRequestSeed {
    return GeneratorJobRemixRequestSeedFromJSONTyped(json, false);
}

export function GeneratorJobRemixRequestSeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobRemixRequestSeed {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    return {} as any;
}

export function GeneratorJobRemixRequestSeedToJSON(json: any): any {
    return GeneratorJobRemixRequestSeedToJSONTyped(json, false);
}

export function GeneratorJobRemixRequestSeedToJSONTyped(value?: GeneratorJobRemixRequestSeed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    return {};
}
