/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorJobProgressDetail } from './GeneratorJobProgressDetail.js';
import {
    GeneratorJobProgressDetailFromJSON,
    GeneratorJobProgressDetailFromJSONTyped,
    GeneratorJobProgressDetailToJSON,
    GeneratorJobProgressDetailToJSONTyped,
} from './GeneratorJobProgressDetail.js';

/**
 * Generator Job Progress used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorJobProgress
 */
export interface GeneratorJobProgress {
    /**
     *
     * @type {GeneratorJobProgressDetail}
     * @memberof GeneratorJobProgress
     */
    detail?: GeneratorJobProgressDetail | null;
    /**
     * Eta Ms accepted or returned by this contract.
     * @type {number}
     * @memberof GeneratorJobProgress
     */
    etaMs?: number | null;
    /**
     * Percent accepted or returned by this contract.
     * @type {number}
     * @memberof GeneratorJobProgress
     */
    percent: number;
    /**
     * Phase accepted or returned by this contract.
     * @type {GeneratorJobProgressPhaseEnum}
     * @memberof GeneratorJobProgress
     */
    phase: GeneratorJobProgressPhaseEnum;
    /**
     * Unix epoch timestamp in milliseconds.
     * @type {number}
     * @memberof GeneratorJobProgress
     */
    updatedAt: number;
}


/**
 * @export
 */
export const GeneratorJobProgressPhaseEnum = {
    Queued: 'queued',
    Warmup: 'warmup',
    Generating: 'generating',
    Refining: 'refining',
    Upscaling: 'upscaling',
    Finalizing: 'finalizing',
    Completed: 'completed',
    Failed: 'failed',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorJobProgressPhaseEnum = typeof GeneratorJobProgressPhaseEnum[keyof typeof GeneratorJobProgressPhaseEnum];


/**
 * Check if a given object implements the GeneratorJobProgress interface.
 */
export function instanceOfGeneratorJobProgress(value: object): value is GeneratorJobProgress {
    if (!('percent' in value) || value['percent'] === undefined) return false;
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GeneratorJobProgressFromJSON(json: any): GeneratorJobProgress {
    return GeneratorJobProgressFromJSONTyped(json, false);
}

export function GeneratorJobProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobProgress {
    if (json == null) {
        return json;
    }
    return {

        'detail': json['detail'] === undefined ? undefined : json['detail'] === null ? null : GeneratorJobProgressDetailFromJSON(json['detail']),
        'etaMs': json['etaMs'] === undefined ? undefined : json['etaMs'] === null ? null : json['etaMs'],
        'percent': json['percent'],
        'phase': json['phase'],
        'updatedAt': json['updatedAt'],
    };
}

export function GeneratorJobProgressToJSON(json: any): GeneratorJobProgress {
    return GeneratorJobProgressToJSONTyped(json, false);
}

export function GeneratorJobProgressToJSONTyped(value?: GeneratorJobProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'detail': GeneratorJobProgressDetailToJSON(value['detail']),
        'etaMs': value['etaMs'],
        'percent': value['percent'],
        'phase': value['phase'],
        'updatedAt': value['updatedAt'],
    };
}
