/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Regions item used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorJobRemixRequestAttentionCoupleRegionsInner
 */
export interface GeneratorJobRemixRequestAttentionCoupleRegionsInner {
    /**
     * PNG mask path under `generator/` with alpha transparency (must include transparent + opaque alpha values).
     * @type {string}
     * @memberof GeneratorJobRemixRequestAttentionCoupleRegionsInner
     */
    maskPath: string;
    /**
     * Prompt accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorJobRemixRequestAttentionCoupleRegionsInner
     */
    prompt: string;
    /**
     * Weight accepted or returned by this contract.
     * @type {number}
     * @memberof GeneratorJobRemixRequestAttentionCoupleRegionsInner
     */
    weight?: number;
}

/**
 * Check if a given object implements the GeneratorJobRemixRequestAttentionCoupleRegionsInner interface.
 */
export function instanceOfGeneratorJobRemixRequestAttentionCoupleRegionsInner(value: object): value is GeneratorJobRemixRequestAttentionCoupleRegionsInner {
    if (!('maskPath' in value) || value['maskPath'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GeneratorJobRemixRequestAttentionCoupleRegionsInnerFromJSON(json: any): GeneratorJobRemixRequestAttentionCoupleRegionsInner {
    return GeneratorJobRemixRequestAttentionCoupleRegionsInnerFromJSONTyped(json, false);
}

export function GeneratorJobRemixRequestAttentionCoupleRegionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobRemixRequestAttentionCoupleRegionsInner {
    if (json == null) {
        return json;
    }
    return {

        'maskPath': json['maskPath'],
        'prompt': json['prompt'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function GeneratorJobRemixRequestAttentionCoupleRegionsInnerToJSON(json: any): GeneratorJobRemixRequestAttentionCoupleRegionsInner {
    return GeneratorJobRemixRequestAttentionCoupleRegionsInnerToJSONTyped(json, false);
}

export function GeneratorJobRemixRequestAttentionCoupleRegionsInnerToJSONTyped(value?: GeneratorJobRemixRequestAttentionCoupleRegionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'maskPath': value['maskPath'],
        'prompt': value['prompt'],
        'weight': value['weight'],
    };
}
