/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing generator video prompt preset in Developer API requests and responses.
 * @export
 * @interface GeneratorVideoPromptPreset
 */
export interface GeneratorVideoPromptPreset {
    /**
     * Preset identifier submitted with a job.
     * @type {GeneratorVideoPromptPresetIdEnum}
     * @memberof GeneratorVideoPromptPreset
     */
    id: GeneratorVideoPromptPresetIdEnum;
    /**
     * Human-readable preset name.
     * @type {string}
     * @memberof GeneratorVideoPromptPreset
     */
    label: string;
    /**
     * Server-maintained starting prompt.
     * @type {string}
     * @memberof GeneratorVideoPromptPreset
     */
    prompt: string;
}


/**
 * @export
 */
export const GeneratorVideoPromptPresetIdEnum = {
    CinematicScene: 'cinematic-scene',
    ProductOrbit: 'product-orbit',
    ImageAnimation: 'image-animation',
    FrameTransition: 'frame-transition',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorVideoPromptPresetIdEnum = typeof GeneratorVideoPromptPresetIdEnum[keyof typeof GeneratorVideoPromptPresetIdEnum];


/**
 * Check if a given object implements the GeneratorVideoPromptPreset interface.
 */
export function instanceOfGeneratorVideoPromptPreset(value: object): value is GeneratorVideoPromptPreset {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GeneratorVideoPromptPresetFromJSON(json: any): GeneratorVideoPromptPreset {
    return GeneratorVideoPromptPresetFromJSONTyped(json, false);
}

export function GeneratorVideoPromptPresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoPromptPreset {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'label': json['label'],
        'prompt': json['prompt'],
    };
}

export function GeneratorVideoPromptPresetToJSON(json: any): GeneratorVideoPromptPreset {
    return GeneratorVideoPromptPresetToJSONTyped(json, false);
}

export function GeneratorVideoPromptPresetToJSONTyped(value?: GeneratorVideoPromptPreset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'label': value['label'],
        'prompt': value['prompt'],
    };
}
