/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Checkpoints item used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorOptionsResponseModelDetailsCheckpointsInner
 */
export interface GeneratorOptionsResponseModelDetailsCheckpointsInner {
    /**
     * Base Model accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsCheckpointsInner
     */
    baseModel?: string | null;
    /**
     * Display Name accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsCheckpointsInner
     */
    displayName?: string | null;
    /**
     * Name accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsCheckpointsInner
     */
    name: string;
    /**
     * Precision accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsCheckpointsInner
     */
    precision?: string | null;
}

/**
 * Check if a given object implements the GeneratorOptionsResponseModelDetailsCheckpointsInner interface.
 */
export function instanceOfGeneratorOptionsResponseModelDetailsCheckpointsInner(value: object): value is GeneratorOptionsResponseModelDetailsCheckpointsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GeneratorOptionsResponseModelDetailsCheckpointsInnerFromJSON(json: any): GeneratorOptionsResponseModelDetailsCheckpointsInner {
    return GeneratorOptionsResponseModelDetailsCheckpointsInnerFromJSONTyped(json, false);
}

export function GeneratorOptionsResponseModelDetailsCheckpointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorOptionsResponseModelDetailsCheckpointsInner {
    if (json == null) {
        return json;
    }
    return {

        'baseModel': json['baseModel'] === undefined ? undefined : json['baseModel'] === null ? null : json['baseModel'],
        'displayName': json['displayName'] === undefined ? undefined : json['displayName'] === null ? null : json['displayName'],
        'name': json['name'],
        'precision': json['precision'] === undefined ? undefined : json['precision'] === null ? null : json['precision'],
    };
}

export function GeneratorOptionsResponseModelDetailsCheckpointsInnerToJSON(json: any): GeneratorOptionsResponseModelDetailsCheckpointsInner {
    return GeneratorOptionsResponseModelDetailsCheckpointsInnerToJSONTyped(json, false);
}

export function GeneratorOptionsResponseModelDetailsCheckpointsInnerToJSONTyped(value?: GeneratorOptionsResponseModelDetailsCheckpointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'baseModel': value['baseModel'],
        'displayName': value['displayName'],
        'name': value['name'],
        'precision': value['precision'],
    };
}
