/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorQuotaBudgetBucket } from './GeneratorQuotaBudgetBucket.js';
import {
    GeneratorQuotaBudgetBucketFromJSON,
    GeneratorQuotaBudgetBucketFromJSONTyped,
    GeneratorQuotaBudgetBucketToJSON,
    GeneratorQuotaBudgetBucketToJSONTyped,
} from './GeneratorQuotaBudgetBucket.js';

/**
 * Budgets accepted or returned by this contract.
 * @export
 * @interface GeneratorQuotaBudgets
 */
export interface GeneratorQuotaBudgets {
    /**
     *
     * @type {GeneratorQuotaBudgetBucket}
     * @memberof GeneratorQuotaBudgets
     */
    gpuMs: GeneratorQuotaBudgetBucket;
    /**
     * Profile accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorQuotaBudgets
     */
    profile: string;
    /**
     *
     * @type {GeneratorQuotaBudgetBucket}
     * @memberof GeneratorQuotaBudgets
     */
    vramMb: GeneratorQuotaBudgetBucket;
}

/**
 * Check if a given object implements the GeneratorQuotaBudgets interface.
 */
export function instanceOfGeneratorQuotaBudgets(value: object): value is GeneratorQuotaBudgets {
    if (!('gpuMs' in value) || value['gpuMs'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('vramMb' in value) || value['vramMb'] === undefined) return false;
    return true;
}

export function GeneratorQuotaBudgetsFromJSON(json: any): GeneratorQuotaBudgets {
    return GeneratorQuotaBudgetsFromJSONTyped(json, false);
}

export function GeneratorQuotaBudgetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorQuotaBudgets {
    if (json == null) {
        return json;
    }
    return {

        'gpuMs': GeneratorQuotaBudgetBucketFromJSON(json['gpuMs']),
        'profile': json['profile'],
        'vramMb': GeneratorQuotaBudgetBucketFromJSON(json['vramMb']),
    };
}

export function GeneratorQuotaBudgetsToJSON(json: any): GeneratorQuotaBudgets {
    return GeneratorQuotaBudgetsToJSONTyped(json, false);
}

export function GeneratorQuotaBudgetsToJSONTyped(value?: GeneratorQuotaBudgets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'gpuMs': GeneratorQuotaBudgetBucketToJSON(value['gpuMs']),
        'profile': value['profile'],
        'vramMb': GeneratorQuotaBudgetBucketToJSON(value['vramMb']),
    };
}
