/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Structured outputs item details for this outputs.
 * @export
 * @interface GeneratorJobOutputsInner
 */
export interface GeneratorJobOutputsInner {
    /**
     * Client-visible filename for this outputs item; do not use it as a resource identifier or filesystem path without sanitizing it.
     * @type {string}
     * @memberof GeneratorJobOutputsInner
     */
    filename: string;
    /**
     * Subfolder associated with this outputs item; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorJobOutputsInner
     */
    subfolder: string;
    /**
     * Discriminator identifying the kind of outputs item; clients should tolerate future values.
     * @type {string}
     * @memberof GeneratorJobOutputsInner
     */
    type?: string | null;
}

/**
 * Check if a given object implements the GeneratorJobOutputsInner interface.
 */
export function instanceOfGeneratorJobOutputsInner(value: object): value is GeneratorJobOutputsInner {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('subfolder' in value) || value['subfolder'] === undefined) return false;
    return true;
}

export function GeneratorJobOutputsInnerFromJSON(json: any): GeneratorJobOutputsInner {
    return GeneratorJobOutputsInnerFromJSONTyped(json, false);
}

export function GeneratorJobOutputsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobOutputsInner {
    if (json == null) {
        return json;
    }
    return {

        'filename': json['filename'],
        'subfolder': json['subfolder'],
        'type': json['type'] === undefined ? undefined : json['type'] === null ? null : json['type'],
    };
}

export function GeneratorJobOutputsInnerToJSON(json: any): GeneratorJobOutputsInner {
    return GeneratorJobOutputsInnerToJSONTyped(json, false);
}

export function GeneratorJobOutputsInnerToJSONTyped(value?: GeneratorJobOutputsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'filename': value['filename'],
        'subfolder': value['subfolder'],
        'type': value['type'],
    };
}
