/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing generator video safety review in Developer API requests and responses.
 * @export
 * @interface GeneratorVideoSafetyReview
 */
export interface GeneratorVideoSafetyReview {
    /**
     * Reviewing staff account ID.
     * @type {number}
     * @memberof GeneratorVideoSafetyReview
     */
    actorId: number | null;
    /**
     * Reviewing staff role.
     * @type {string}
     * @memberof GeneratorVideoSafetyReview
     */
    actorRole: string | null;
    /**
     * Whether automated rescans may replace this review.
     * @type {boolean}
     * @memberof GeneratorVideoSafetyReview
     */
    locked: boolean;
    /**
     * Private moderator note.
     * @type {string}
     * @memberof GeneratorVideoSafetyReview
     */
    note: string | null;
    /**
     * Moderator-selected or free-form safety reason.
     * @type {string}
     * @memberof GeneratorVideoSafetyReview
     */
    reason: string | null;
    /**
     * Review time in Unix milliseconds.
     * @type {number}
     * @memberof GeneratorVideoSafetyReview
     */
    reviewedAt: number | null;
    /**
     * Moderator-selected safety status.
     * @type {GeneratorVideoSafetyReviewStatusEnum}
     * @memberof GeneratorVideoSafetyReview
     */
    status: GeneratorVideoSafetyReviewStatusEnum | null;
}


/**
 * @export
 */
export const GeneratorVideoSafetyReviewStatusEnum = {
    Ok: 'ok',
    PendingReview: 'pending_review',
    Quarantined: 'quarantined',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorVideoSafetyReviewStatusEnum = typeof GeneratorVideoSafetyReviewStatusEnum[keyof typeof GeneratorVideoSafetyReviewStatusEnum];


/**
 * Check if a given object implements the GeneratorVideoSafetyReview interface.
 */
export function instanceOfGeneratorVideoSafetyReview(value: object): value is GeneratorVideoSafetyReview {
    if (!('actorId' in value) || value['actorId'] === undefined) return false;
    if (!('actorRole' in value) || value['actorRole'] === undefined) return false;
    if (!('locked' in value) || value['locked'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('reviewedAt' in value) || value['reviewedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GeneratorVideoSafetyReviewFromJSON(json: any): GeneratorVideoSafetyReview {
    return GeneratorVideoSafetyReviewFromJSONTyped(json, false);
}

export function GeneratorVideoSafetyReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoSafetyReview {
    if (json == null) {
        return json;
    }
    return {

        'actorId': json['actorId'],
        'actorRole': json['actorRole'],
        'locked': json['locked'],
        'note': json['note'],
        'reason': json['reason'],
        'reviewedAt': json['reviewedAt'],
        'status': json['status'],
    };
}

export function GeneratorVideoSafetyReviewToJSON(json: any): GeneratorVideoSafetyReview {
    return GeneratorVideoSafetyReviewToJSONTyped(json, false);
}

export function GeneratorVideoSafetyReviewToJSONTyped(value?: GeneratorVideoSafetyReview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'actorId': value['actorId'],
        'actorRole': value['actorRole'],
        'locked': value['locked'],
        'note': value['note'],
        'reason': value['reason'],
        'reviewedAt': value['reviewedAt'],
        'status': value['status'],
    };
}
