/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorVideoEstimateRange } from './GeneratorVideoEstimateRange.js';
import {
    GeneratorVideoEstimateRangeFromJSON,
    GeneratorVideoEstimateRangeFromJSONTyped,
    GeneratorVideoEstimateRangeToJSON,
    GeneratorVideoEstimateRangeToJSONTyped,
} from './GeneratorVideoEstimateRange.js';

/**
 * Fields describing generator video resolution bucket option in Developer API requests and responses.
 * @export
 * @interface GeneratorVideoResolutionBucketOption
 */
export interface GeneratorVideoResolutionBucketOption {
    /**
     *
     * @type {GeneratorVideoEstimateRange}
     * @memberof GeneratorVideoResolutionBucketOption
     */
    estimate: GeneratorVideoEstimateRange;
    /**
     * Human-readable quality label.
     * @type {string}
     * @memberof GeneratorVideoResolutionBucketOption
     */
    label: string;
    /**
     * Nominal short-edge resolution bucket.
     * @type {GeneratorVideoResolutionBucketOptionValueEnum}
     * @memberof GeneratorVideoResolutionBucketOption
     */
    value: GeneratorVideoResolutionBucketOptionValueEnum;
}


/**
 * @export
 */
export const GeneratorVideoResolutionBucketOptionValueEnum = {
    NUMBER_384: 384,
    NUMBER_512: 512,
    NUMBER_640: 640,
    NUMBER_768: 768,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type GeneratorVideoResolutionBucketOptionValueEnum = typeof GeneratorVideoResolutionBucketOptionValueEnum[keyof typeof GeneratorVideoResolutionBucketOptionValueEnum];


/**
 * Check if a given object implements the GeneratorVideoResolutionBucketOption interface.
 */
export function instanceOfGeneratorVideoResolutionBucketOption(value: object): value is GeneratorVideoResolutionBucketOption {
    if (!('estimate' in value) || value['estimate'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function GeneratorVideoResolutionBucketOptionFromJSON(json: any): GeneratorVideoResolutionBucketOption {
    return GeneratorVideoResolutionBucketOptionFromJSONTyped(json, false);
}

export function GeneratorVideoResolutionBucketOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoResolutionBucketOption {
    if (json == null) {
        return json;
    }
    return {

        'estimate': GeneratorVideoEstimateRangeFromJSON(json['estimate']),
        'label': json['label'],
        'value': json['value'],
    };
}

export function GeneratorVideoResolutionBucketOptionToJSON(json: any): GeneratorVideoResolutionBucketOption {
    return GeneratorVideoResolutionBucketOptionToJSONTyped(json, false);
}

export function GeneratorVideoResolutionBucketOptionToJSONTyped(value?: GeneratorVideoResolutionBucketOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'estimate': GeneratorVideoEstimateRangeToJSON(value['estimate']),
        'label': value['label'],
        'value': value['value'],
    };
}
