/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Upscale item used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorOptionsResponseModelDetailsUpscaleInner
 */
export interface GeneratorOptionsResponseModelDetailsUpscaleInner {
    /**
     * Base Model accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsUpscaleInner
     */
    baseModel?: string | null;
    /**
     * Display Name accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsUpscaleInner
     */
    displayName?: string | null;
    /**
     * Name accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsUpscaleInner
     */
    name: string;
    /**
     * Precision accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsUpscaleInner
     */
    precision?: string | null;
}

/**
 * Check if a given object implements the GeneratorOptionsResponseModelDetailsUpscaleInner interface.
 */
export function instanceOfGeneratorOptionsResponseModelDetailsUpscaleInner(value: object): value is GeneratorOptionsResponseModelDetailsUpscaleInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GeneratorOptionsResponseModelDetailsUpscaleInnerFromJSON(json: any): GeneratorOptionsResponseModelDetailsUpscaleInner {
    return GeneratorOptionsResponseModelDetailsUpscaleInnerFromJSONTyped(json, false);
}

export function GeneratorOptionsResponseModelDetailsUpscaleInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorOptionsResponseModelDetailsUpscaleInner {
    if (json == null) {
        return json;
    }
    return {

        'baseModel': json['baseModel'] === undefined ? undefined : json['baseModel'] === null ? null : json['baseModel'],
        'displayName': json['displayName'] === undefined ? undefined : json['displayName'] === null ? null : json['displayName'],
        'name': json['name'],
        'precision': json['precision'] === undefined ? undefined : json['precision'] === null ? null : json['precision'],
    };
}

export function GeneratorOptionsResponseModelDetailsUpscaleInnerToJSON(json: any): GeneratorOptionsResponseModelDetailsUpscaleInner {
    return GeneratorOptionsResponseModelDetailsUpscaleInnerToJSONTyped(json, false);
}

export function GeneratorOptionsResponseModelDetailsUpscaleInnerToJSONTyped(value?: GeneratorOptionsResponseModelDetailsUpscaleInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'baseModel': value['baseModel'],
        'displayName': value['displayName'],
        'name': value['name'],
        'precision': value['precision'],
    };
}
