/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Generator Video Legacy Resolution used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorVideoLegacyResolution
 */
export interface GeneratorVideoLegacyResolution {
    /**
     * Legacy canvas height.
     * @type {number}
     * @memberof GeneratorVideoLegacyResolution
     */
    height: number;
    /**
     * Legacy preset identifier.
     * @type {string}
     * @memberof GeneratorVideoLegacyResolution
     */
    id: string;
    /**
     * Legacy preset label.
     * @type {string}
     * @memberof GeneratorVideoLegacyResolution
     */
    label: string;
    /**
     * Legacy canvas width.
     * @type {number}
     * @memberof GeneratorVideoLegacyResolution
     */
    width: number;
}

/**
 * Check if a given object implements the GeneratorVideoLegacyResolution interface.
 */
export function instanceOfGeneratorVideoLegacyResolution(value: object): value is GeneratorVideoLegacyResolution {
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function GeneratorVideoLegacyResolutionFromJSON(json: any): GeneratorVideoLegacyResolution {
    return GeneratorVideoLegacyResolutionFromJSONTyped(json, false);
}

export function GeneratorVideoLegacyResolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoLegacyResolution {
    if (json == null) {
        return json;
    }
    return {

        'height': json['height'],
        'id': json['id'],
        'label': json['label'],
        'width': json['width'],
    };
}

export function GeneratorVideoLegacyResolutionToJSON(json: any): GeneratorVideoLegacyResolution {
    return GeneratorVideoLegacyResolutionToJSONTyped(json, false);
}

export function GeneratorVideoLegacyResolutionToJSONTyped(value?: GeneratorVideoLegacyResolution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'height': value['height'],
        'id': value['id'],
        'label': value['label'],
        'width': value['width'],
    };
}
