/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreateGeneratorJobRequestLorasInner } from './CreateGeneratorJobRequestLorasInner.js';
import {
    CreateGeneratorJobRequestLorasInnerFromJSON,
    CreateGeneratorJobRequestLorasInnerFromJSONTyped,
    CreateGeneratorJobRequestLorasInnerToJSON,
    CreateGeneratorJobRequestLorasInnerToJSONTyped,
} from './CreateGeneratorJobRequestLorasInner.js';
import type { GeneratorJobRemixRequestPromptControl } from './GeneratorJobRemixRequestPromptControl.js';
import {
    GeneratorJobRemixRequestPromptControlFromJSON,
    GeneratorJobRemixRequestPromptControlFromJSONTyped,
    GeneratorJobRemixRequestPromptControlToJSON,
    GeneratorJobRemixRequestPromptControlToJSONTyped,
} from './GeneratorJobRemixRequestPromptControl.js';
import type { GeneratorJobRemixRequestUpscaleProfilesInner } from './GeneratorJobRemixRequestUpscaleProfilesInner.js';
import {
    GeneratorJobRemixRequestUpscaleProfilesInnerFromJSON,
    GeneratorJobRemixRequestUpscaleProfilesInnerFromJSONTyped,
    GeneratorJobRemixRequestUpscaleProfilesInnerToJSON,
    GeneratorJobRemixRequestUpscaleProfilesInnerToJSONTyped,
} from './GeneratorJobRemixRequestUpscaleProfilesInner.js';
import type { GeneratorJobRemixRequestAttentionCouple } from './GeneratorJobRemixRequestAttentionCouple.js';
import {
    GeneratorJobRemixRequestAttentionCoupleFromJSON,
    GeneratorJobRemixRequestAttentionCoupleFromJSONTyped,
    GeneratorJobRemixRequestAttentionCoupleToJSON,
    GeneratorJobRemixRequestAttentionCoupleToJSONTyped,
} from './GeneratorJobRemixRequestAttentionCouple.js';
import type { GeneratorJobRemixRequestControlnetsInner } from './GeneratorJobRemixRequestControlnetsInner.js';
import {
    GeneratorJobRemixRequestControlnetsInnerFromJSON,
    GeneratorJobRemixRequestControlnetsInnerFromJSONTyped,
    GeneratorJobRemixRequestControlnetsInnerToJSON,
    GeneratorJobRemixRequestControlnetsInnerToJSONTyped,
} from './GeneratorJobRemixRequestControlnetsInner.js';
import type { GeneratorAdetailerConfig } from './GeneratorAdetailerConfig.js';
import {
    GeneratorAdetailerConfigFromJSON,
    GeneratorAdetailerConfigFromJSONTyped,
    GeneratorAdetailerConfigToJSON,
    GeneratorAdetailerConfigToJSONTyped,
} from './GeneratorAdetailerConfig.js';
import type { GeneratorJobRemixRequestExtraSeed } from './GeneratorJobRemixRequestExtraSeed.js';
import {
    GeneratorJobRemixRequestExtraSeedFromJSON,
    GeneratorJobRemixRequestExtraSeedFromJSONTyped,
    GeneratorJobRemixRequestExtraSeedToJSON,
    GeneratorJobRemixRequestExtraSeedToJSONTyped,
} from './GeneratorJobRemixRequestExtraSeed.js';
import type { GeneratorJobRemixRequestSeed } from './GeneratorJobRemixRequestSeed.js';
import {
    GeneratorJobRemixRequestSeedFromJSON,
    GeneratorJobRemixRequestSeedFromJSONTyped,
    GeneratorJobRemixRequestSeedToJSON,
    GeneratorJobRemixRequestSeedToJSONTyped,
} from './GeneratorJobRemixRequestSeed.js';

/**
 * Same override fields as `POST /api/generator/jobs`.
 * @export
 * @interface GeneratorJobRemixRequest
 */
export interface GeneratorJobRemixRequest {
    /**
     *
     * @type {GeneratorAdetailerConfig}
     * @memberof GeneratorJobRemixRequest
     */
    adetailer?: GeneratorAdetailerConfig;
    /**
     * Adetailer Detection Order associated with this generator job remix request; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     * @deprecated
     */
    adetailerDetectionOrder?: string;
    /**
     * Adetailer Negative associated with this generator job remix request; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     * @deprecated
     */
    adetailerNegative?: string;
    /**
     * Adetailer Positive associated with this generator job remix request; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     * @deprecated
     */
    adetailerPositive?: string;
    /**
     *
     * @type {GeneratorJobRemixRequestAttentionCouple}
     * @memberof GeneratorJobRemixRequest
     */
    attentionCouple?: GeneratorJobRemixRequestAttentionCouple;
    /**
     * `txt2img` only.
     * Must be `1` when upscale/hires is enabled.
     *
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    batchSize?: number;
    /**
     * Numeric cfg reported for this generator job remix request.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    cfg?: number;
    /**
     * Ordered controlnets entries included with this generator job remix request; an empty list means none are available.
     * @type {Array<GeneratorJobRemixRequestControlnetsInner>}
     * @memberof GeneratorJobRemixRequest
     */
    controlnets?: Array<GeneratorJobRemixRequestControlnetsInner>;
    /**
     * Numeric denoise reported for this generator job remix request.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    denoise?: number;
    /**
     *
     * @type {GeneratorJobRemixRequestExtraSeed}
     * @memberof GeneratorJobRemixRequest
     */
    extraSeed?: GeneratorJobRemixRequestExtraSeed;
    /**
     * Numeric extra seed strength reported for this generator job remix request. Minimum: 0. Maximum: 1.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    extraSeedStrength?: number;
    /**
     * Numeric height reported for this generator job remix request.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    height?: number;
    /**
     * Server-provided path for the image path associated with this generator job remix request; treat it as opaque.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    imagePath?: string;
    /**
     * Human-readable lora name for this generator job remix request; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    loraName?: string;
    /**
     * Ordered loras entries included with this generator job remix request; an empty list means none are available.
     * @type {Array<CreateGeneratorJobRequestLorasInner>}
     * @memberof GeneratorJobRemixRequest
     */
    loras?: Array<CreateGeneratorJobRequestLorasInner>;
    /**
     * Structured metadata details for this generator job remix request.
     * @type {{ [key: string]: any; }}
     * @memberof GeneratorJobRemixRequest
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * Mode associated with this generator job remix request; preserve server-returned values when passing them to another operation. Supported values: `txt2img`, `img2img`, `inpaint`.
     * @type {GeneratorJobRemixRequestModeEnum}
     * @memberof GeneratorJobRemixRequest
     */
    mode?: GeneratorJobRemixRequestModeEnum;
    /**
     * Human-readable model name for this generator job remix request; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    modelName?: string;
    /**
     * Negative Prompt text associated with generation of this generator job remix request; availability depends on visibility and privacy rules.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    negativePrompt?: string;
    /**
     * Stable identifier for the preset; use it in subsequent API calls instead of a display name.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    presetId?: number;
    /**
     * Prompt text associated with generation of this generator job remix request; availability depends on visibility and privacy rules.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    prompt: string;
    /**
     *
     * @type {GeneratorJobRemixRequestPromptControl}
     * @memberof GeneratorJobRemixRequest
     */
    promptControl?: GeneratorJobRemixRequestPromptControl;
    /**
     * Numeric retention days reported for this generator job remix request.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    retentionDays?: number;
    /**
     * Numeric rf shift reported for this generator job remix request. Minimum: 1. Maximum: 15.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    rfShift?: number;
    /**
     * Human-readable sampler name for this generator job remix request; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    samplerName?: string;
    /**
     * Upscale factor target. Applied only when `upscaleProfiles` (or legacy `upscaleModelName`) is set; otherwise treated as `1`.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    scaleFactor?: number;
    /**
     * Scheduler associated with this generator job remix request; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    scheduler?: string;
    /**
     * Human-readable scheduler name for this generator job remix request; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     * @deprecated
     */
    schedulerName?: string;
    /**
     *
     * @type {GeneratorJobRemixRequestSeed}
     * @memberof GeneratorJobRemixRequest
     */
    seed?: GeneratorJobRemixRequestSeed;
    /**
     * Whether sfw mode applies to this generator job remix request.
     * @type {boolean}
     * @memberof GeneratorJobRemixRequest
     */
    sfwMode?: boolean;
    /**
     * Numeric steps reported for this generator job remix request.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    steps?: number;
    /**
     * Ordered tags entries included with this generator job remix request; an empty list means none are available.
     * @type {Array<string>}
     * @memberof GeneratorJobRemixRequest
     */
    tags?: Array<string>;
    /**
     * Ordered upscale profiles entries included with this generator job remix request; an empty list means none are available.
     * @type {Array<GeneratorJobRemixRequestUpscaleProfilesInner>}
     * @memberof GeneratorJobRemixRequest
     */
    upscaleProfiles?: Array<GeneratorJobRemixRequestUpscaleProfilesInner>;
    /**
     * Human-readable vae name for this generator job remix request; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorJobRemixRequest
     */
    vaeName?: string;
    /**
     * Numeric width reported for this generator job remix request.
     * @type {number}
     * @memberof GeneratorJobRemixRequest
     */
    width?: number;
}


/**
 * @export
 */
export const GeneratorJobRemixRequestModeEnum = {
    Txt2img: 'txt2img',
    Img2img: 'img2img',
    Inpaint: 'inpaint',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorJobRemixRequestModeEnum = typeof GeneratorJobRemixRequestModeEnum[keyof typeof GeneratorJobRemixRequestModeEnum];


/**
 * Check if a given object implements the GeneratorJobRemixRequest interface.
 */
export function instanceOfGeneratorJobRemixRequest(value: object): value is GeneratorJobRemixRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GeneratorJobRemixRequestFromJSON(json: any): GeneratorJobRemixRequest {
    return GeneratorJobRemixRequestFromJSONTyped(json, false);
}

export function GeneratorJobRemixRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobRemixRequest {
    if (json == null) {
        return json;
    }
    return {

        'adetailer': json['adetailer'] == null ? undefined : GeneratorAdetailerConfigFromJSON(json['adetailer']),
        'adetailerDetectionOrder': json['adetailerDetectionOrder'] == null ? undefined : json['adetailerDetectionOrder'],
        'adetailerNegative': json['adetailerNegative'] == null ? undefined : json['adetailerNegative'],
        'adetailerPositive': json['adetailerPositive'] == null ? undefined : json['adetailerPositive'],
        'attentionCouple': json['attentionCouple'] == null ? undefined : GeneratorJobRemixRequestAttentionCoupleFromJSON(json['attentionCouple']),
        'batchSize': json['batchSize'] == null ? undefined : json['batchSize'],
        'cfg': json['cfg'] == null ? undefined : json['cfg'],
        'controlnets': json['controlnets'] == null ? undefined : ((json['controlnets'] as Array<any>).map(GeneratorJobRemixRequestControlnetsInnerFromJSON)),
        'denoise': json['denoise'] == null ? undefined : json['denoise'],
        'extraSeed': json['extraSeed'] == null ? undefined : GeneratorJobRemixRequestExtraSeedFromJSON(json['extraSeed']),
        'extraSeedStrength': json['extraSeedStrength'] == null ? undefined : json['extraSeedStrength'],
        'height': json['height'] == null ? undefined : json['height'],
        'imagePath': json['imagePath'] == null ? undefined : json['imagePath'],
        'loraName': json['loraName'] == null ? undefined : json['loraName'],
        'loras': json['loras'] == null ? undefined : ((json['loras'] as Array<any>).map(CreateGeneratorJobRequestLorasInnerFromJSON)),
        'metadata': json['metadata'] === undefined ? undefined : json['metadata'] === null ? null : json['metadata'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
        'negativePrompt': json['negativePrompt'] == null ? undefined : json['negativePrompt'],
        'presetId': json['presetId'] == null ? undefined : json['presetId'],
        'prompt': json['prompt'],
        'promptControl': json['promptControl'] == null ? undefined : GeneratorJobRemixRequestPromptControlFromJSON(json['promptControl']),
        'retentionDays': json['retentionDays'] == null ? undefined : json['retentionDays'],
        'rfShift': json['rfShift'] == null ? undefined : json['rfShift'],
        'samplerName': json['samplerName'] == null ? undefined : json['samplerName'],
        'scaleFactor': json['scaleFactor'] == null ? undefined : json['scaleFactor'],
        'scheduler': json['scheduler'] == null ? undefined : json['scheduler'],
        'schedulerName': json['schedulerName'] == null ? undefined : json['schedulerName'],
        'seed': json['seed'] == null ? undefined : GeneratorJobRemixRequestSeedFromJSON(json['seed']),
        'sfwMode': json['sfwMode'] == null ? undefined : json['sfwMode'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'upscaleProfiles': json['upscaleProfiles'] == null ? undefined : ((json['upscaleProfiles'] as Array<any>).map(GeneratorJobRemixRequestUpscaleProfilesInnerFromJSON)),
        'vaeName': json['vaeName'] == null ? undefined : json['vaeName'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function GeneratorJobRemixRequestToJSON(json: any): GeneratorJobRemixRequest {
    return GeneratorJobRemixRequestToJSONTyped(json, false);
}

export function GeneratorJobRemixRequestToJSONTyped(value?: GeneratorJobRemixRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'adetailer': GeneratorAdetailerConfigToJSON(value['adetailer']),
        'adetailerDetectionOrder': value['adetailerDetectionOrder'],
        'adetailerNegative': value['adetailerNegative'],
        'adetailerPositive': value['adetailerPositive'],
        'attentionCouple': GeneratorJobRemixRequestAttentionCoupleToJSON(value['attentionCouple']),
        'batchSize': value['batchSize'],
        'cfg': value['cfg'],
        'controlnets': value['controlnets'] == null ? undefined : ((value['controlnets'] as Array<any>).map(GeneratorJobRemixRequestControlnetsInnerToJSON)),
        'denoise': value['denoise'],
        'extraSeed': GeneratorJobRemixRequestExtraSeedToJSON(value['extraSeed']),
        'extraSeedStrength': value['extraSeedStrength'],
        'height': value['height'],
        'imagePath': value['imagePath'],
        'loraName': value['loraName'],
        'loras': value['loras'] == null ? undefined : ((value['loras'] as Array<any>).map(CreateGeneratorJobRequestLorasInnerToJSON)),
        'metadata': value['metadata'],
        'mode': value['mode'],
        'modelName': value['modelName'],
        'negativePrompt': value['negativePrompt'],
        'presetId': value['presetId'],
        'prompt': value['prompt'],
        'promptControl': GeneratorJobRemixRequestPromptControlToJSON(value['promptControl']),
        'retentionDays': value['retentionDays'],
        'rfShift': value['rfShift'],
        'samplerName': value['samplerName'],
        'scaleFactor': value['scaleFactor'],
        'scheduler': value['scheduler'],
        'schedulerName': value['schedulerName'],
        'seed': GeneratorJobRemixRequestSeedToJSON(value['seed']),
        'sfwMode': value['sfwMode'],
        'steps': value['steps'],
        'tags': value['tags'],
        'upscaleProfiles': value['upscaleProfiles'] == null ? undefined : ((value['upscaleProfiles'] as Array<any>).map(GeneratorJobRemixRequestUpscaleProfilesInnerToJSON)),
        'vaeName': value['vaeName'],
        'width': value['width'],
    };
}
