/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorVideoPublicMetadata } from './GeneratorVideoPublicMetadata.js';
import {
    GeneratorVideoPublicMetadataFromJSON,
    GeneratorVideoPublicMetadataFromJSONTyped,
    GeneratorVideoPublicMetadataToJSON,
    GeneratorVideoPublicMetadataToJSONTyped,
} from './GeneratorVideoPublicMetadata.js';
import type { GeneratorVideoSafetySnapshot } from './GeneratorVideoSafetySnapshot.js';
import {
    GeneratorVideoSafetySnapshotFromJSON,
    GeneratorVideoSafetySnapshotFromJSONTyped,
    GeneratorVideoSafetySnapshotToJSON,
    GeneratorVideoSafetySnapshotToJSONTyped,
} from './GeneratorVideoSafetySnapshot.js';

/**
 * Generator Video Job used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorVideoJob
 */
export interface GeneratorVideoJob {
    /**
     * Server-owned guidance value.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    cfg: number;
    /**
     * Terminal completion time.
     * @type {Date}
     * @memberof GeneratorVideoJob
     */
    completedAt: Date | null;
    /**
     * Creation time.
     * @type {Date}
     * @memberof GeneratorVideoJob
     */
    createdAt: Date;
    /**
     * Credits reserved by this job.
     * @type {GeneratorVideoJobCreditCostEnum}
     * @memberof GeneratorVideoJob
     */
    creditCost: GeneratorVideoJobCreditCostEnum;
    /**
     * Authenticated MP4 attachment URL when available and viewable.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    downloadUrl: string | null;
    /**
     * Expected playback duration.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    durationSeconds: number;
    /**
     * Viewer-safe terminal error.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    error: string | null;
    /**
     * Estimated milliseconds from now until completion.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    estimatedCompletionMs: number | null;
    /**
     * Estimated time until completion, including queue delay.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    estimatedRemainingMs: number | null;
    /**
     * Estimated render duration.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    estimatedRenderMs: number | null;
    /**
     * Generated-output expiration time.
     * @type {Date}
     * @memberof GeneratorVideoJob
     */
    expiresAt: Date | null;
    /**
     * Download, validation, and moderation time.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    finalizationMs: number | null;
    /**
     * Authenticated source-frame preview URL.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    firstFrameUrl: string | null;
    /**
     * Output FPS.
     * @type {GeneratorVideoJobFpsEnum}
     * @memberof GeneratorVideoJob
     */
    fps: GeneratorVideoJobFpsEnum;
    /**
     * Requested frame count.
     * @type {GeneratorVideoJobFramesEnum}
     * @memberof GeneratorVideoJob
     */
    frames: GeneratorVideoJobFramesEnum;
    /**
     * Whether the job has a source image.
     * @type {boolean}
     * @memberof GeneratorVideoJob
     */
    hasFirstFrame: boolean;
    /**
     * Whether the job has an ending-frame image.
     * @type {boolean}
     * @memberof GeneratorVideoJob
     */
    hasLastFrame: boolean;
    /**
     * Resolved output height.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    height: number;
    /**
     * Video job ID.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    id: string;
    /**
     * Authenticated ending-frame preview URL.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    lastFrameUrl: string | null;
    /**
     *
     * @type {GeneratorVideoPublicMetadata}
     * @memberof GeneratorVideoJob
     */
    metadata: GeneratorVideoPublicMetadata;
    /**
     * Generation mode.
     * @type {GeneratorVideoJobModeEnum}
     * @memberof GeneratorVideoJob
     */
    mode: GeneratorVideoJobModeEnum;
    /**
     * Submitted or server-default negative prompt.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    negativePrompt: string | null;
    /**
     * Final MP4 size.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    outputBytes: number | null;
    /**
     * Media playback duration, not generation time.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    outputDurationSeconds: number;
    /**
     * Authenticated inline MP4 URL when available and viewable.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    outputUrl: string | null;
    /**
     * Current one-based queue position.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    position: number | null;
    /**
     * Worker processing time.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    processingMs: number | null;
    /**
     * Normalized job progress.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    progress: number;
    /**
     * Viewer-safe current phase.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    progressMessage: string | null;
    /**
     * Submitted positive prompt.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    prompt: string;
    /**
     * Selected prompt-preset ID.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    promptPreset: string | null;
    /**
     * Estimated wait before rendering begins.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    queueEtaMs: number | null;
    /**
     * Time from creation until worker start.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    queueWaitMs: number | null;
    /**
     * Remote rendering time.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    remoteRenderMs: number | null;
    /**
     *
     * @type {GeneratorVideoSafetySnapshot}
     * @memberof GeneratorVideoJob
     */
    safety: GeneratorVideoSafetySnapshot;
    /**
     * Server-owned sampler name.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    samplerName: string;
    /**
     * Server-owned scheduler name.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    scheduler: string;
    /**
     * Decimal generation seed.
     * @type {string}
     * @memberof GeneratorVideoJob
     */
    seed: string;
    /**
     * Worker start time.
     * @type {Date}
     * @memberof GeneratorVideoJob
     */
    startedAt: Date | null;
    /**
     * Current job lifecycle status.
     * @type {GeneratorVideoJobStatusEnum}
     * @memberof GeneratorVideoJob
     */
    status: GeneratorVideoJobStatusEnum;
    /**
     * Sampling steps.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    steps: number;
    /**
     * Normalized sampled-frame tags.
     * @type {Array<string>}
     * @memberof GeneratorVideoJob
     */
    taggerTags: Array<string>;
    /**
     * Total creation-to-completion time.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    totalElapsedMs: number | null;
    /**
     * Resolved output width.
     * @type {number}
     * @memberof GeneratorVideoJob
     */
    width: number;
}


/**
 * @export
 */
export const GeneratorVideoJobCreditCostEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type GeneratorVideoJobCreditCostEnum = typeof GeneratorVideoJobCreditCostEnum[keyof typeof GeneratorVideoJobCreditCostEnum];

/**
 * @export
 */
export const GeneratorVideoJobFpsEnum = {
    NUMBER_24: 24,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type GeneratorVideoJobFpsEnum = typeof GeneratorVideoJobFpsEnum[keyof typeof GeneratorVideoJobFpsEnum];

/**
 * @export
 */
export const GeneratorVideoJobFramesEnum = {
    NUMBER_124: 124,
    NUMBER_243: 243,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type GeneratorVideoJobFramesEnum = typeof GeneratorVideoJobFramesEnum[keyof typeof GeneratorVideoJobFramesEnum];

/**
 * @export
 */
export const GeneratorVideoJobModeEnum = {
    Txt2video: 'txt2video',
    Image2video: 'image2video',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorVideoJobModeEnum = typeof GeneratorVideoJobModeEnum[keyof typeof GeneratorVideoJobModeEnum];

/**
 * @export
 */
export const GeneratorVideoJobStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Finalizing: 'finalizing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorVideoJobStatusEnum = typeof GeneratorVideoJobStatusEnum[keyof typeof GeneratorVideoJobStatusEnum];


/**
 * Check if a given object implements the GeneratorVideoJob interface.
 */
export function instanceOfGeneratorVideoJob(value: object): value is GeneratorVideoJob {
    if (!('cfg' in value) || value['cfg'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('creditCost' in value) || value['creditCost'] === undefined) return false;
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    if (!('durationSeconds' in value) || value['durationSeconds'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('estimatedCompletionMs' in value) || value['estimatedCompletionMs'] === undefined) return false;
    if (!('estimatedRemainingMs' in value) || value['estimatedRemainingMs'] === undefined) return false;
    if (!('estimatedRenderMs' in value) || value['estimatedRenderMs'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('finalizationMs' in value) || value['finalizationMs'] === undefined) return false;
    if (!('firstFrameUrl' in value) || value['firstFrameUrl'] === undefined) return false;
    if (!('fps' in value) || value['fps'] === undefined) return false;

    if (value['fps'] !== 24) return false;
    if (!('frames' in value) || value['frames'] === undefined) return false;
    if (!('hasFirstFrame' in value) || value['hasFirstFrame'] === undefined) return false;
    if (!('hasLastFrame' in value) || value['hasLastFrame'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastFrameUrl' in value) || value['lastFrameUrl'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('negativePrompt' in value) || value['negativePrompt'] === undefined) return false;
    if (!('outputBytes' in value) || value['outputBytes'] === undefined) return false;
    if (!('outputDurationSeconds' in value) || value['outputDurationSeconds'] === undefined) return false;
    if (!('outputUrl' in value) || value['outputUrl'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('processingMs' in value) || value['processingMs'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('progressMessage' in value) || value['progressMessage'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('promptPreset' in value) || value['promptPreset'] === undefined) return false;
    if (!('queueEtaMs' in value) || value['queueEtaMs'] === undefined) return false;
    if (!('queueWaitMs' in value) || value['queueWaitMs'] === undefined) return false;
    if (!('remoteRenderMs' in value) || value['remoteRenderMs'] === undefined) return false;
    if (!('safety' in value) || value['safety'] === undefined) return false;
    if (!('samplerName' in value) || value['samplerName'] === undefined) return false;
    if (!('scheduler' in value) || value['scheduler'] === undefined) return false;
    if (!('seed' in value) || value['seed'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    if (!('taggerTags' in value) || value['taggerTags'] === undefined) return false;
    if (!('totalElapsedMs' in value) || value['totalElapsedMs'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function GeneratorVideoJobFromJSON(json: any): GeneratorVideoJob {
    return GeneratorVideoJobFromJSONTyped(json, false);
}

export function GeneratorVideoJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoJob {
    if (json == null) {
        return json;
    }
    return {

        'cfg': json['cfg'],
        'completedAt': (json['completedAt'] == null ? null : new Date(json['completedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'creditCost': json['creditCost'],
        'downloadUrl': json['downloadUrl'],
        'durationSeconds': json['durationSeconds'],
        'error': json['error'],
        'estimatedCompletionMs': json['estimatedCompletionMs'],
        'estimatedRemainingMs': json['estimatedRemainingMs'],
        'estimatedRenderMs': json['estimatedRenderMs'],
        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
        'finalizationMs': json['finalizationMs'],
        'firstFrameUrl': json['firstFrameUrl'],
        'fps': json['fps'],
        'frames': json['frames'],
        'hasFirstFrame': json['hasFirstFrame'],
        'hasLastFrame': json['hasLastFrame'],
        'height': json['height'],
        'id': json['id'],
        'lastFrameUrl': json['lastFrameUrl'],
        'metadata': GeneratorVideoPublicMetadataFromJSON(json['metadata']),
        'mode': json['mode'],
        'negativePrompt': json['negativePrompt'],
        'outputBytes': json['outputBytes'],
        'outputDurationSeconds': json['outputDurationSeconds'],
        'outputUrl': json['outputUrl'],
        'position': json['position'],
        'processingMs': json['processingMs'],
        'progress': json['progress'],
        'progressMessage': json['progressMessage'],
        'prompt': json['prompt'],
        'promptPreset': json['promptPreset'],
        'queueEtaMs': json['queueEtaMs'],
        'queueWaitMs': json['queueWaitMs'],
        'remoteRenderMs': json['remoteRenderMs'],
        'safety': GeneratorVideoSafetySnapshotFromJSON(json['safety']),
        'samplerName': json['samplerName'],
        'scheduler': json['scheduler'],
        'seed': json['seed'],
        'startedAt': (json['startedAt'] == null ? null : new Date(json['startedAt'])),
        'status': json['status'],
        'steps': json['steps'],
        'taggerTags': json['taggerTags'],
        'totalElapsedMs': json['totalElapsedMs'],
        'width': json['width'],
    };
}

export function GeneratorVideoJobToJSON(json: any): GeneratorVideoJob {
    return GeneratorVideoJobToJSONTyped(json, false);
}

export function GeneratorVideoJobToJSONTyped(value?: GeneratorVideoJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cfg': value['cfg'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'creditCost': value['creditCost'],
        'downloadUrl': value['downloadUrl'],
        'durationSeconds': value['durationSeconds'],
        'error': value['error'],
        'estimatedCompletionMs': value['estimatedCompletionMs'],
        'estimatedRemainingMs': value['estimatedRemainingMs'],
        'estimatedRenderMs': value['estimatedRenderMs'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'finalizationMs': value['finalizationMs'],
        'firstFrameUrl': value['firstFrameUrl'],
        'fps': value['fps'],
        'frames': value['frames'],
        'hasFirstFrame': value['hasFirstFrame'],
        'hasLastFrame': value['hasLastFrame'],
        'height': value['height'],
        'id': value['id'],
        'lastFrameUrl': value['lastFrameUrl'],
        'metadata': GeneratorVideoPublicMetadataToJSON(value['metadata']),
        'mode': value['mode'],
        'negativePrompt': value['negativePrompt'],
        'outputBytes': value['outputBytes'],
        'outputDurationSeconds': value['outputDurationSeconds'],
        'outputUrl': value['outputUrl'],
        'position': value['position'],
        'processingMs': value['processingMs'],
        'progress': value['progress'],
        'progressMessage': value['progressMessage'],
        'prompt': value['prompt'],
        'promptPreset': value['promptPreset'],
        'queueEtaMs': value['queueEtaMs'],
        'queueWaitMs': value['queueWaitMs'],
        'remoteRenderMs': value['remoteRenderMs'],
        'safety': GeneratorVideoSafetySnapshotToJSON(value['safety']),
        'samplerName': value['samplerName'],
        'scheduler': value['scheduler'],
        'seed': value['seed'],
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'status': value['status'],
        'steps': value['steps'],
        'taggerTags': value['taggerTags'],
        'totalElapsedMs': value['totalElapsedMs'],
        'width': value['width'],
    };
}
