/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Generator Upload Response used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorUploadResponse
 */
export interface GeneratorUploadResponse {
    /**
     * Expires At accepted or returned by this contract.
     * @type {Date}
     * @memberof GeneratorUploadResponse
     */
    expiresAt: Date | null;
    /**
     * Mime Type accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorUploadResponse
     */
    mimeType: string;
    /**
     * Original Name accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorUploadResponse
     */
    originalName: string;
    /**
     * Path accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorUploadResponse
     */
    path: string;
    /**
     * Size accepted or returned by this contract.
     * @type {number}
     * @memberof GeneratorUploadResponse
     */
    size: number;
    /**
     * Ttl Seconds accepted or returned by this contract.
     * @type {number}
     * @memberof GeneratorUploadResponse
     */
    ttlSeconds: number;
}

/**
 * Check if a given object implements the GeneratorUploadResponse interface.
 */
export function instanceOfGeneratorUploadResponse(value: object): value is GeneratorUploadResponse {
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('originalName' in value) || value['originalName'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('ttlSeconds' in value) || value['ttlSeconds'] === undefined) return false;
    return true;
}

export function GeneratorUploadResponseFromJSON(json: any): GeneratorUploadResponse {
    return GeneratorUploadResponseFromJSONTyped(json, false);
}

export function GeneratorUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorUploadResponse {
    if (json == null) {
        return json;
    }
    return {

        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
        'mimeType': json['mimeType'],
        'originalName': json['originalName'],
        'path': json['path'],
        'size': json['size'],
        'ttlSeconds': json['ttlSeconds'],
    };
}

export function GeneratorUploadResponseToJSON(json: any): GeneratorUploadResponse {
    return GeneratorUploadResponseToJSONTyped(json, false);
}

export function GeneratorUploadResponseToJSONTyped(value?: GeneratorUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'mimeType': value['mimeType'],
        'originalName': value['originalName'],
        'path': value['path'],
        'size': value['size'],
        'ttlSeconds': value['ttlSeconds'],
    };
}
