/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing generator video create base in Developer API requests and responses.
 * @export
 * @interface GeneratorVideoCreateBase
 */
export interface GeneratorVideoCreateBase {
    /**
     * Request synchronized audio when the capability is available.
     * @type {boolean}
     * @memberof GeneratorVideoCreateBase
     */
    audioEnabled?: boolean;
    /**
     * Optional negative prompt; the server default is used when omitted.
     * @type {string}
     * @memberof GeneratorVideoCreateBase
     */
    negativePrompt?: string;
    /**
     * Positive video prompt.
     * @type {string}
     * @memberof GeneratorVideoCreateBase
     */
    prompt: string;
    /**
     * Optional server-provided prompt-preset ID.
     * @type {GeneratorVideoCreateBasePromptPresetEnum}
     * @memberof GeneratorVideoCreateBase
     */
    promptPreset?: GeneratorVideoCreateBasePromptPresetEnum | null;
    /**
     * Optional safe non-negative decimal seed; generated when omitted.
     * @type {string}
     * @memberof GeneratorVideoCreateBase
     */
    seed?: string;
    /**
     * Apply stricter generator-only output moderation; mandatory minor-safety checks always apply.
     * @type {boolean}
     * @memberof GeneratorVideoCreateBase
     */
    sfwMode?: boolean;
    /**
     * Sampling steps.
     * @type {number}
     * @memberof GeneratorVideoCreateBase
     */
    steps?: number;
}


/**
 * @export
 */
export const GeneratorVideoCreateBasePromptPresetEnum = {
    CinematicScene: 'cinematic-scene',
    ProductOrbit: 'product-orbit',
    ImageAnimation: 'image-animation',
    FrameTransition: 'frame-transition',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorVideoCreateBasePromptPresetEnum = typeof GeneratorVideoCreateBasePromptPresetEnum[keyof typeof GeneratorVideoCreateBasePromptPresetEnum];


/**
 * Check if a given object implements the GeneratorVideoCreateBase interface.
 */
export function instanceOfGeneratorVideoCreateBase(value: object): value is GeneratorVideoCreateBase {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GeneratorVideoCreateBaseFromJSON(json: any): GeneratorVideoCreateBase {
    return GeneratorVideoCreateBaseFromJSONTyped(json, false);
}

export function GeneratorVideoCreateBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoCreateBase {
    if (json == null) {
        return json;
    }
    return {

        'audioEnabled': json['audioEnabled'] == null ? undefined : json['audioEnabled'],
        'negativePrompt': json['negativePrompt'] == null ? undefined : json['negativePrompt'],
        'prompt': json['prompt'],
        'promptPreset': json['promptPreset'] === undefined ? undefined : json['promptPreset'] === null ? null : json['promptPreset'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'sfwMode': json['sfwMode'] == null ? undefined : json['sfwMode'],
        'steps': json['steps'] == null ? undefined : json['steps'],
    };
}

export function GeneratorVideoCreateBaseToJSON(json: any): GeneratorVideoCreateBase {
    return GeneratorVideoCreateBaseToJSONTyped(json, false);
}

export function GeneratorVideoCreateBaseToJSONTyped(value?: GeneratorVideoCreateBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'audioEnabled': value['audioEnabled'],
        'negativePrompt': value['negativePrompt'],
        'prompt': value['prompt'],
        'promptPreset': value['promptPreset'],
        'seed': value['seed'],
        'sfwMode': value['sfwMode'],
        'steps': value['steps'],
    };
}
