/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Prompt Control state used for this job.
 * @export
 * @interface GeneratorJobPromptControl
 */
export interface GeneratorJobPromptControl {
    /**
     * Whether enabled applies to this prompt control.
     * @type {boolean}
     * @memberof GeneratorJobPromptControl
     */
    enabled?: boolean;
    /**
     * Mode associated with this prompt control; preserve server-returned values when passing them to another operation. Supported values: `manual`, `auto`, `disabled`.
     * @type {GeneratorJobPromptControlModeEnum}
     * @memberof GeneratorJobPromptControl
     */
    mode?: GeneratorJobPromptControlModeEnum;
    /**
     * Source associated with this prompt control; preserve server-returned values when passing them to another operation. Supported values: `explicit`, `auto`.
     * @type {GeneratorJobPromptControlSourceEnum}
     * @memberof GeneratorJobPromptControl
     */
    source?: GeneratorJobPromptControlSourceEnum;
}


/**
 * @export
 */
export const GeneratorJobPromptControlModeEnum = {
    Manual: 'manual',
    Auto: 'auto',
    Disabled: 'disabled',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorJobPromptControlModeEnum = typeof GeneratorJobPromptControlModeEnum[keyof typeof GeneratorJobPromptControlModeEnum];

/**
 * @export
 */
export const GeneratorJobPromptControlSourceEnum = {
    Explicit: 'explicit',
    Auto: 'auto',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorJobPromptControlSourceEnum = typeof GeneratorJobPromptControlSourceEnum[keyof typeof GeneratorJobPromptControlSourceEnum];


/**
 * Check if a given object implements the GeneratorJobPromptControl interface.
 */
export function instanceOfGeneratorJobPromptControl(value: object): value is GeneratorJobPromptControl {
    return true;
}

export function GeneratorJobPromptControlFromJSON(json: any): GeneratorJobPromptControl {
    return GeneratorJobPromptControlFromJSONTyped(json, false);
}

export function GeneratorJobPromptControlFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobPromptControl {
    if (json == null) {
        return json;
    }
    return {

        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function GeneratorJobPromptControlToJSON(json: any): GeneratorJobPromptControl {
    return GeneratorJobPromptControlToJSONTyped(json, false);
}

export function GeneratorJobPromptControlToJSONTyped(value?: GeneratorJobPromptControl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'enabled': value['enabled'],
        'mode': value['mode'],
        'source': value['source'],
    };
}
