/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Adetailer Bridge accepted or returned by this contract.
 * @export
 * @interface GeneratorJobDiagnosticsAdetailerBridge
 */
export interface GeneratorJobDiagnosticsAdetailerBridge {
    /**
     * Failed accepted or returned by this contract.
     * @type {boolean}
     * @memberof GeneratorJobDiagnosticsAdetailerBridge
     */
    failed?: boolean;
    /**
     * Reason accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorJobDiagnosticsAdetailerBridge
     */
    reason?: string | null;
    /**
     * Unix epoch timestamp in milliseconds.
     * @type {number}
     * @memberof GeneratorJobDiagnosticsAdetailerBridge
     */
    updatedAt?: number | null;
}

/**
 * Check if a given object implements the GeneratorJobDiagnosticsAdetailerBridge interface.
 */
export function instanceOfGeneratorJobDiagnosticsAdetailerBridge(value: object): value is GeneratorJobDiagnosticsAdetailerBridge {
    return true;
}

export function GeneratorJobDiagnosticsAdetailerBridgeFromJSON(json: any): GeneratorJobDiagnosticsAdetailerBridge {
    return GeneratorJobDiagnosticsAdetailerBridgeFromJSONTyped(json, false);
}

export function GeneratorJobDiagnosticsAdetailerBridgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobDiagnosticsAdetailerBridge {
    if (json == null) {
        return json;
    }
    return {

        'failed': json['failed'] == null ? undefined : json['failed'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
        'updatedAt': json['updatedAt'] === undefined ? undefined : json['updatedAt'] === null ? null : json['updatedAt'],
    };
}

export function GeneratorJobDiagnosticsAdetailerBridgeToJSON(json: any): GeneratorJobDiagnosticsAdetailerBridge {
    return GeneratorJobDiagnosticsAdetailerBridgeToJSONTyped(json, false);
}

export function GeneratorJobDiagnosticsAdetailerBridgeToJSONTyped(value?: GeneratorJobDiagnosticsAdetailerBridge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'failed': value['failed'],
        'reason': value['reason'],
        'updatedAt': value['updatedAt'],
    };
}
