/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Structured loras item details for this loras.
 * @export
 * @interface GeneratorJobLorasInner
 */
export interface GeneratorJobLorasInner {
    /**
     * Human-readable name for this loras item; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorJobLorasInner
     */
    name: string;
    /**
     * Numeric weight reported for this loras item.
     * @type {number}
     * @memberof GeneratorJobLorasInner
     */
    weight?: number | null;
}

/**
 * Check if a given object implements the GeneratorJobLorasInner interface.
 */
export function instanceOfGeneratorJobLorasInner(value: object): value is GeneratorJobLorasInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GeneratorJobLorasInnerFromJSON(json: any): GeneratorJobLorasInner {
    return GeneratorJobLorasInnerFromJSONTyped(json, false);
}

export function GeneratorJobLorasInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobLorasInner {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'weight': json['weight'] === undefined ? undefined : json['weight'] === null ? null : json['weight'],
    };
}

export function GeneratorJobLorasInnerToJSON(json: any): GeneratorJobLorasInner {
    return GeneratorJobLorasInnerToJSONTyped(json, false);
}

export function GeneratorJobLorasInnerToJSONTyped(value?: GeneratorJobLorasInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'weight': value['weight'],
    };
}
