/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Structured limits details for this generator options response.
 * @export
 * @interface GeneratorOptionsResponseLimits
 */
export interface GeneratorOptionsResponseLimits {
    /**
     * Ordered adetailer attention couple policies entries included with this limits; an empty list means none are available.
     * @type {Array<GeneratorOptionsResponseLimitsAdetailerAttentionCouplePoliciesEnum>}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerAttentionCouplePolicies: Array<GeneratorOptionsResponseLimitsAdetailerAttentionCouplePoliciesEnum>;
    /**
     * Adetailer Attention Couple Policy Default associated with this limits; preserve server-returned values when passing them to another operation. Supported values: `strict-face-bbox`, `prefer-face`, `passthrough`.
     * @type {GeneratorOptionsResponseLimitsAdetailerAttentionCouplePolicyDefaultEnum}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerAttentionCouplePolicyDefault: GeneratorOptionsResponseLimitsAdetailerAttentionCouplePolicyDefaultEnum;
    /**
     * Adetailer Detection Order Default associated with this limits; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerDetectionOrderDefault: string;
    /**
     * Ordered adetailer detection orders entries included with this limits; an empty list means none are available.
     * @type {Array<string>}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerDetectionOrders: Array<string>;
    /**
     * Ordered adetailer detectors entries included with this limits; an empty list means none are available.
     * @type {Array<string>}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerDetectors: Array<string>;
    /**
     * Whether adetailer enabled applies to this limits.
     * @type {boolean}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerEnabled: boolean;
    /**
     * Adetailer Mask Mode Default associated with this limits; preserve server-returned values when passing them to another operation. Supported values: `bbox-only`, `segmentation`.
     * @type {GeneratorOptionsResponseLimitsAdetailerMaskModeDefaultEnum}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerMaskModeDefault: GeneratorOptionsResponseLimitsAdetailerMaskModeDefaultEnum;
    /**
     * Ordered adetailer mask modes entries included with this limits; an empty list means none are available.
     * @type {Array<GeneratorOptionsResponseLimitsAdetailerMaskModesEnum>}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerMaskModes: Array<GeneratorOptionsResponseLimitsAdetailerMaskModesEnum>;
    /**
     * Ordered adetailer models entries included with this limits; an empty list means none are available.
     * @type {Array<string>}
     * @memberof GeneratorOptionsResponseLimits
     */
    adetailerModels: Array<string>;
    /**
     * Whether compare enabled applies to this limits.
     * @type {boolean}
     * @memberof GeneratorOptionsResponseLimits
     */
    compareEnabled: boolean;
    /**
     * Numeric max batch size reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxBatchSize: number;
    /**
     * Numeric max cfg reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxCfg: number;
    /**
     * Numeric max compare targets reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxCompareTargets: number;
    /**
     * Numeric max pixels reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxPixels: number;
    /**
     * Numeric max resolution reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxResolution: number;
    /**
     * Numeric max scale factor reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxScaleFactor: number;
    /**
     * Numeric max steps reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxSteps: number;
    /**
     * Numeric max upscale profiles reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxUpscaleProfiles: number;
    /**
     * Numeric max weight reported for this limits.
     * @type {number}
     * @memberof GeneratorOptionsResponseLimits
     */
    maxWeight: number;
    /**
     * Ordered samplers entries included with this limits; an empty list means none are available.
     * @type {Array<string>}
     * @memberof GeneratorOptionsResponseLimits
     */
    samplers: Array<string>;
    /**
     * Ordered schedulers entries included with this limits; an empty list means none are available.
     * @type {Array<string>}
     * @memberof GeneratorOptionsResponseLimits
     */
    schedulers: Array<string>;
}


/**
 * @export
 */
export const GeneratorOptionsResponseLimitsAdetailerAttentionCouplePoliciesEnum = {
    StrictFaceBbox: 'strict-face-bbox',
    PreferFace: 'prefer-face',
    Passthrough: 'passthrough',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorOptionsResponseLimitsAdetailerAttentionCouplePoliciesEnum = typeof GeneratorOptionsResponseLimitsAdetailerAttentionCouplePoliciesEnum[keyof typeof GeneratorOptionsResponseLimitsAdetailerAttentionCouplePoliciesEnum];

/**
 * @export
 */
export const GeneratorOptionsResponseLimitsAdetailerAttentionCouplePolicyDefaultEnum = {
    StrictFaceBbox: 'strict-face-bbox',
    PreferFace: 'prefer-face',
    Passthrough: 'passthrough',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorOptionsResponseLimitsAdetailerAttentionCouplePolicyDefaultEnum = typeof GeneratorOptionsResponseLimitsAdetailerAttentionCouplePolicyDefaultEnum[keyof typeof GeneratorOptionsResponseLimitsAdetailerAttentionCouplePolicyDefaultEnum];

/**
 * @export
 */
export const GeneratorOptionsResponseLimitsAdetailerMaskModeDefaultEnum = {
    BboxOnly: 'bbox-only',
    Segmentation: 'segmentation',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorOptionsResponseLimitsAdetailerMaskModeDefaultEnum = typeof GeneratorOptionsResponseLimitsAdetailerMaskModeDefaultEnum[keyof typeof GeneratorOptionsResponseLimitsAdetailerMaskModeDefaultEnum];

/**
 * @export
 */
export const GeneratorOptionsResponseLimitsAdetailerMaskModesEnum = {
    BboxOnly: 'bbox-only',
    Segmentation: 'segmentation',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type GeneratorOptionsResponseLimitsAdetailerMaskModesEnum = typeof GeneratorOptionsResponseLimitsAdetailerMaskModesEnum[keyof typeof GeneratorOptionsResponseLimitsAdetailerMaskModesEnum];


/**
 * Check if a given object implements the GeneratorOptionsResponseLimits interface.
 */
export function instanceOfGeneratorOptionsResponseLimits(value: object): value is GeneratorOptionsResponseLimits {
    if (!('adetailerAttentionCouplePolicies' in value) || value['adetailerAttentionCouplePolicies'] === undefined) return false;
    if (!('adetailerAttentionCouplePolicyDefault' in value) || value['adetailerAttentionCouplePolicyDefault'] === undefined) return false;
    if (!('adetailerDetectionOrderDefault' in value) || value['adetailerDetectionOrderDefault'] === undefined) return false;
    if (!('adetailerDetectionOrders' in value) || value['adetailerDetectionOrders'] === undefined) return false;
    if (!('adetailerDetectors' in value) || value['adetailerDetectors'] === undefined) return false;
    if (!('adetailerEnabled' in value) || value['adetailerEnabled'] === undefined) return false;
    if (!('adetailerMaskModeDefault' in value) || value['adetailerMaskModeDefault'] === undefined) return false;
    if (!('adetailerMaskModes' in value) || value['adetailerMaskModes'] === undefined) return false;
    if (!('adetailerModels' in value) || value['adetailerModels'] === undefined) return false;
    if (!('compareEnabled' in value) || value['compareEnabled'] === undefined) return false;
    if (!('maxBatchSize' in value) || value['maxBatchSize'] === undefined) return false;
    if (!('maxCfg' in value) || value['maxCfg'] === undefined) return false;
    if (!('maxCompareTargets' in value) || value['maxCompareTargets'] === undefined) return false;
    if (!('maxPixels' in value) || value['maxPixels'] === undefined) return false;
    if (!('maxResolution' in value) || value['maxResolution'] === undefined) return false;
    if (!('maxScaleFactor' in value) || value['maxScaleFactor'] === undefined) return false;
    if (!('maxSteps' in value) || value['maxSteps'] === undefined) return false;
    if (!('maxUpscaleProfiles' in value) || value['maxUpscaleProfiles'] === undefined) return false;
    if (!('maxWeight' in value) || value['maxWeight'] === undefined) return false;
    if (!('samplers' in value) || value['samplers'] === undefined) return false;
    if (!('schedulers' in value) || value['schedulers'] === undefined) return false;
    return true;
}

export function GeneratorOptionsResponseLimitsFromJSON(json: any): GeneratorOptionsResponseLimits {
    return GeneratorOptionsResponseLimitsFromJSONTyped(json, false);
}

export function GeneratorOptionsResponseLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorOptionsResponseLimits {
    if (json == null) {
        return json;
    }
    return {

        'adetailerAttentionCouplePolicies': json['adetailerAttentionCouplePolicies'],
        'adetailerAttentionCouplePolicyDefault': json['adetailerAttentionCouplePolicyDefault'],
        'adetailerDetectionOrderDefault': json['adetailerDetectionOrderDefault'],
        'adetailerDetectionOrders': json['adetailerDetectionOrders'],
        'adetailerDetectors': json['adetailerDetectors'],
        'adetailerEnabled': json['adetailerEnabled'],
        'adetailerMaskModeDefault': json['adetailerMaskModeDefault'],
        'adetailerMaskModes': json['adetailerMaskModes'],
        'adetailerModels': json['adetailerModels'],
        'compareEnabled': json['compareEnabled'],
        'maxBatchSize': json['maxBatchSize'],
        'maxCfg': json['maxCfg'],
        'maxCompareTargets': json['maxCompareTargets'],
        'maxPixels': json['maxPixels'],
        'maxResolution': json['maxResolution'],
        'maxScaleFactor': json['maxScaleFactor'],
        'maxSteps': json['maxSteps'],
        'maxUpscaleProfiles': json['maxUpscaleProfiles'],
        'maxWeight': json['maxWeight'],
        'samplers': json['samplers'],
        'schedulers': json['schedulers'],
    };
}

export function GeneratorOptionsResponseLimitsToJSON(json: any): GeneratorOptionsResponseLimits {
    return GeneratorOptionsResponseLimitsToJSONTyped(json, false);
}

export function GeneratorOptionsResponseLimitsToJSONTyped(value?: GeneratorOptionsResponseLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'adetailerAttentionCouplePolicies': value['adetailerAttentionCouplePolicies'],
        'adetailerAttentionCouplePolicyDefault': value['adetailerAttentionCouplePolicyDefault'],
        'adetailerDetectionOrderDefault': value['adetailerDetectionOrderDefault'],
        'adetailerDetectionOrders': value['adetailerDetectionOrders'],
        'adetailerDetectors': value['adetailerDetectors'],
        'adetailerEnabled': value['adetailerEnabled'],
        'adetailerMaskModeDefault': value['adetailerMaskModeDefault'],
        'adetailerMaskModes': value['adetailerMaskModes'],
        'adetailerModels': value['adetailerModels'],
        'compareEnabled': value['compareEnabled'],
        'maxBatchSize': value['maxBatchSize'],
        'maxCfg': value['maxCfg'],
        'maxCompareTargets': value['maxCompareTargets'],
        'maxPixels': value['maxPixels'],
        'maxResolution': value['maxResolution'],
        'maxScaleFactor': value['maxScaleFactor'],
        'maxSteps': value['maxSteps'],
        'maxUpscaleProfiles': value['maxUpscaleProfiles'],
        'maxWeight': value['maxWeight'],
        'samplers': value['samplers'],
        'schedulers': value['schedulers'],
    };
}
