/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorJobListItem } from './GeneratorJobListItem.js';
import {
    GeneratorJobListItemFromJSON,
    GeneratorJobListItemFromJSONTyped,
    GeneratorJobListItemToJSON,
    GeneratorJobListItemToJSONTyped,
} from './GeneratorJobListItem.js';

/**
 * Fields describing generator job list response in Developer API requests and responses.
 * @export
 * @interface GeneratorJobListResponse
 */
export interface GeneratorJobListResponse {
    /**
     * Ordered jobs entries included with this generator job list response; an empty list means none are available.
     * @type {Array<GeneratorJobListItem>}
     * @memberof GeneratorJobListResponse
     */
    jobs: Array<GeneratorJobListItem>;
    /**
     * Opaque continuation token for the next page of this generator job list response; absent or null means iteration is complete.
     * @type {string}
     * @memberof GeneratorJobListResponse
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the GeneratorJobListResponse interface.
 */
export function instanceOfGeneratorJobListResponse(value: object): value is GeneratorJobListResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function GeneratorJobListResponseFromJSON(json: any): GeneratorJobListResponse {
    return GeneratorJobListResponseFromJSONTyped(json, false);
}

export function GeneratorJobListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobListResponse {
    if (json == null) {
        return json;
    }
    return {

        'jobs': ((json['jobs'] as Array<any>).map(GeneratorJobListItemFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function GeneratorJobListResponseToJSON(json: any): GeneratorJobListResponse {
    return GeneratorJobListResponseToJSONTyped(json, false);
}

export function GeneratorJobListResponseToJSONTyped(value?: GeneratorJobListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'jobs': ((value['jobs'] as Array<any>).map(GeneratorJobListItemToJSON)),
        'nextCursor': value['nextCursor'],
    };
}
