/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Comfy accepted or returned by this contract.
 * @export
 * @interface GeneratorJobComfy
 */
export interface GeneratorJobComfy {
    /**
     * Messages accepted or returned by this contract.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GeneratorJobComfy
     */
    messages?: Array<{ [key: string]: any; }>;
    /**
     * Node Errors accepted or returned by this contract.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GeneratorJobComfy
     */
    nodeErrors?: Array<{ [key: string]: any; }>;
    /**
     * Status accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorJobComfy
     */
    status?: string | null;
}

/**
 * Check if a given object implements the GeneratorJobComfy interface.
 */
export function instanceOfGeneratorJobComfy(value: object): value is GeneratorJobComfy {
    return true;
}

export function GeneratorJobComfyFromJSON(json: any): GeneratorJobComfy {
    return GeneratorJobComfyFromJSONTyped(json, false);
}

export function GeneratorJobComfyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorJobComfy {
    if (json == null) {
        return json;
    }
    return {

        'messages': json['messages'] == null ? undefined : json['messages'],
        'nodeErrors': json['nodeErrors'] == null ? undefined : json['nodeErrors'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
    };
}

export function GeneratorJobComfyToJSON(json: any): GeneratorJobComfy {
    return GeneratorJobComfyToJSONTyped(json, false);
}

export function GeneratorJobComfyToJSONTyped(value?: GeneratorJobComfy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'messages': value['messages'],
        'nodeErrors': value['nodeErrors'],
        'status': value['status'],
    };
}
