/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing generator video legacy resolution in Developer API requests and responses.
 * @export
 * @interface GeneratorVideoLegacyResolution
 */
export interface GeneratorVideoLegacyResolution {
    /**
     * Legacy canvas height.
     * @type {number}
     * @memberof GeneratorVideoLegacyResolution
     */
    height: number;
    /**
     * Legacy preset identifier.
     * @type {string}
     * @memberof GeneratorVideoLegacyResolution
     */
    id: string;
    /**
     * Legacy preset label.
     * @type {string}
     * @memberof GeneratorVideoLegacyResolution
     */
    label: string;
    /**
     * Legacy canvas width.
     * @type {number}
     * @memberof GeneratorVideoLegacyResolution
     */
    width: number;
}

/**
 * Check if a given object implements the GeneratorVideoLegacyResolution interface.
 */
export function instanceOfGeneratorVideoLegacyResolution(value: object): value is GeneratorVideoLegacyResolution {
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function GeneratorVideoLegacyResolutionFromJSON(json: any): GeneratorVideoLegacyResolution {
    return GeneratorVideoLegacyResolutionFromJSONTyped(json, false);
}

export function GeneratorVideoLegacyResolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoLegacyResolution {
    if (json == null) {
        return json;
    }
    return {

        'height': json['height'],
        'id': json['id'],
        'label': json['label'],
        'width': json['width'],
    };
}

export function GeneratorVideoLegacyResolutionToJSON(json: any): GeneratorVideoLegacyResolution {
    return GeneratorVideoLegacyResolutionToJSONTyped(json, false);
}

export function GeneratorVideoLegacyResolutionToJSONTyped(value?: GeneratorVideoLegacyResolution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'height': value['height'],
        'id': value['id'],
        'label': value['label'],
        'width': value['width'],
    };
}
