/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorVideoJob } from './GeneratorVideoJob.js';
import {
    GeneratorVideoJobFromJSON,
    GeneratorVideoJobFromJSONTyped,
    GeneratorVideoJobToJSON,
    GeneratorVideoJobToJSONTyped,
} from './GeneratorVideoJob.js';

/**
 * Generator Video Job Envelope used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorVideoJobEnvelope
 */
export interface GeneratorVideoJobEnvelope {
    /**
     *
     * @type {GeneratorVideoJob}
     * @memberof GeneratorVideoJobEnvelope
     */
    job: GeneratorVideoJob;
}

/**
 * Check if a given object implements the GeneratorVideoJobEnvelope interface.
 */
export function instanceOfGeneratorVideoJobEnvelope(value: object): value is GeneratorVideoJobEnvelope {
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function GeneratorVideoJobEnvelopeFromJSON(json: any): GeneratorVideoJobEnvelope {
    return GeneratorVideoJobEnvelopeFromJSONTyped(json, false);
}

export function GeneratorVideoJobEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoJobEnvelope {
    if (json == null) {
        return json;
    }
    return {

        'job': GeneratorVideoJobFromJSON(json['job']),
    };
}

export function GeneratorVideoJobEnvelopeToJSON(json: any): GeneratorVideoJobEnvelope {
    return GeneratorVideoJobEnvelopeToJSONTyped(json, false);
}

export function GeneratorVideoJobEnvelopeToJSONTyped(value?: GeneratorVideoJobEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'job': GeneratorVideoJobToJSON(value['job']),
    };
}
