/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Structured controlnets item details for this controlnets.
 * @export
 * @interface GeneratorOptionsResponseModelDetailsControlnetsInner
 */
export interface GeneratorOptionsResponseModelDetailsControlnetsInner {
    /**
     * Base Model associated with this controlnets item; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsControlnetsInner
     */
    baseModel?: string | null;
    /**
     * Human-readable display name for this controlnets item; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsControlnetsInner
     */
    displayName?: string | null;
    /**
     * Human-readable name for this controlnets item; it is not a stable identifier.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsControlnetsInner
     */
    name: string;
    /**
     * Precision associated with this controlnets item; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof GeneratorOptionsResponseModelDetailsControlnetsInner
     */
    precision?: string | null;
}

/**
 * Check if a given object implements the GeneratorOptionsResponseModelDetailsControlnetsInner interface.
 */
export function instanceOfGeneratorOptionsResponseModelDetailsControlnetsInner(value: object): value is GeneratorOptionsResponseModelDetailsControlnetsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GeneratorOptionsResponseModelDetailsControlnetsInnerFromJSON(json: any): GeneratorOptionsResponseModelDetailsControlnetsInner {
    return GeneratorOptionsResponseModelDetailsControlnetsInnerFromJSONTyped(json, false);
}

export function GeneratorOptionsResponseModelDetailsControlnetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorOptionsResponseModelDetailsControlnetsInner {
    if (json == null) {
        return json;
    }
    return {

        'baseModel': json['baseModel'] === undefined ? undefined : json['baseModel'] === null ? null : json['baseModel'],
        'displayName': json['displayName'] === undefined ? undefined : json['displayName'] === null ? null : json['displayName'],
        'name': json['name'],
        'precision': json['precision'] === undefined ? undefined : json['precision'] === null ? null : json['precision'],
    };
}

export function GeneratorOptionsResponseModelDetailsControlnetsInnerToJSON(json: any): GeneratorOptionsResponseModelDetailsControlnetsInner {
    return GeneratorOptionsResponseModelDetailsControlnetsInnerToJSONTyped(json, false);
}

export function GeneratorOptionsResponseModelDetailsControlnetsInnerToJSONTyped(value?: GeneratorOptionsResponseModelDetailsControlnetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'baseModel': value['baseModel'],
        'displayName': value['displayName'],
        'name': value['name'],
        'precision': value['precision'],
    };
}
