/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorStorageStatusErrorsInner } from './GeneratorStorageStatusErrorsInner.js';
import {
    GeneratorStorageStatusErrorsInnerFromJSON,
    GeneratorStorageStatusErrorsInnerFromJSONTyped,
    GeneratorStorageStatusErrorsInnerToJSON,
    GeneratorStorageStatusErrorsInnerToJSONTyped,
} from './GeneratorStorageStatusErrorsInner.js';

/**
 * Generator Storage Status used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorStorageStatus
 */
export interface GeneratorStorageStatus {
    /**
     * Errors accepted or returned by this contract.
     * @type {Array<GeneratorStorageStatusErrorsInner>}
     * @memberof GeneratorStorageStatus
     */
    errors: Array<GeneratorStorageStatusErrorsInner>;
    /**
     * Status accepted or returned by this contract.
     * @type {string}
     * @memberof GeneratorStorageStatus
     */
    status: string | null;
    /**
     * Unix epoch timestamp in milliseconds.
     * @type {number}
     * @memberof GeneratorStorageStatus
     */
    storedAt: number | null;
}

/**
 * Check if a given object implements the GeneratorStorageStatus interface.
 */
export function instanceOfGeneratorStorageStatus(value: object): value is GeneratorStorageStatus {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('storedAt' in value) || value['storedAt'] === undefined) return false;
    return true;
}

export function GeneratorStorageStatusFromJSON(json: any): GeneratorStorageStatus {
    return GeneratorStorageStatusFromJSONTyped(json, false);
}

export function GeneratorStorageStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorStorageStatus {
    if (json == null) {
        return json;
    }
    return {

        'errors': ((json['errors'] as Array<any>).map(GeneratorStorageStatusErrorsInnerFromJSON)),
        'status': json['status'],
        'storedAt': json['storedAt'],
    };
}

export function GeneratorStorageStatusToJSON(json: any): GeneratorStorageStatus {
    return GeneratorStorageStatusToJSONTyped(json, false);
}

export function GeneratorStorageStatusToJSONTyped(value?: GeneratorStorageStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'errors': ((value['errors'] as Array<any>).map(GeneratorStorageStatusErrorsInnerToJSON)),
        'status': value['status'],
        'storedAt': value['storedAt'],
    };
}
