/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.6.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Generator Video Limits used by the Arc en Ciel API contract.
 * @export
 * @interface GeneratorVideoLimits
 */
export interface GeneratorVideoLimits {
    /**
     * Server-owned guidance value.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    cfg: number;
    /**
     * Output frames per second.
     * @type {GeneratorVideoLimitsFpsEnum}
     * @memberof GeneratorVideoLimits
     */
    fps: GeneratorVideoLimitsFpsEnum;
    /**
     * Supported frame counts.
     * @type {Array<GeneratorVideoLimitsFramesEnum>}
     * @memberof GeneratorVideoLimits
     */
    frames: Array<GeneratorVideoLimitsFramesEnum>;
    /**
     * Maximum accepted generated-video size.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    maxOutputBytes: number;
    /**
     * Maximum resolved canvas area in pixels.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    maxPixels: number;
    /**
     * Maximum bytes per source frame image.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    maxSourceBytes: number;
    /**
     * Maximum decoded pixels per source frame image.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    maxSourcePixels: number;
    /**
     * Maximum accepted sampling step count.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    maxSteps: number;
    /**
     * Minimum accepted sampling step count.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    minSteps: number;
    /**
     * Maximum negative-prompt length in characters.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    negativePromptChars: number;
    /**
     * Maximum prompt length in characters.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    promptChars: number;
    /**
     * Generated-output retention period in days.
     * @type {number}
     * @memberof GeneratorVideoLimits
     */
    retentionDays: number;
}


/**
 * @export
 */
export const GeneratorVideoLimitsFpsEnum = {
    NUMBER_24: 24,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type GeneratorVideoLimitsFpsEnum = typeof GeneratorVideoLimitsFpsEnum[keyof typeof GeneratorVideoLimitsFpsEnum];

/**
 * @export
 */
export const GeneratorVideoLimitsFramesEnum = {
    NUMBER_124: 124,
    NUMBER_243: 243,
    NUMBER_unknown_default_open_api: 11184809
} as const;
export type GeneratorVideoLimitsFramesEnum = typeof GeneratorVideoLimitsFramesEnum[keyof typeof GeneratorVideoLimitsFramesEnum];


/**
 * Check if a given object implements the GeneratorVideoLimits interface.
 */
export function instanceOfGeneratorVideoLimits(value: object): value is GeneratorVideoLimits {
    if (!('cfg' in value) || value['cfg'] === undefined) return false;
    if (!('fps' in value) || value['fps'] === undefined) return false;

    if (value['fps'] !== 24) return false;
    if (!('frames' in value) || value['frames'] === undefined) return false;
    if (!('maxOutputBytes' in value) || value['maxOutputBytes'] === undefined) return false;
    if (!('maxPixels' in value) || value['maxPixels'] === undefined) return false;
    if (!('maxSourceBytes' in value) || value['maxSourceBytes'] === undefined) return false;
    if (!('maxSourcePixels' in value) || value['maxSourcePixels'] === undefined) return false;
    if (!('maxSteps' in value) || value['maxSteps'] === undefined) return false;
    if (!('minSteps' in value) || value['minSteps'] === undefined) return false;
    if (!('negativePromptChars' in value) || value['negativePromptChars'] === undefined) return false;
    if (!('promptChars' in value) || value['promptChars'] === undefined) return false;
    if (!('retentionDays' in value) || value['retentionDays'] === undefined) return false;
    return true;
}

export function GeneratorVideoLimitsFromJSON(json: any): GeneratorVideoLimits {
    return GeneratorVideoLimitsFromJSONTyped(json, false);
}

export function GeneratorVideoLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratorVideoLimits {
    if (json == null) {
        return json;
    }
    return {

        'cfg': json['cfg'],
        'fps': json['fps'],
        'frames': json['frames'],
        'maxOutputBytes': json['maxOutputBytes'],
        'maxPixels': json['maxPixels'],
        'maxSourceBytes': json['maxSourceBytes'],
        'maxSourcePixels': json['maxSourcePixels'],
        'maxSteps': json['maxSteps'],
        'minSteps': json['minSteps'],
        'negativePromptChars': json['negativePromptChars'],
        'promptChars': json['promptChars'],
        'retentionDays': json['retentionDays'],
    };
}

export function GeneratorVideoLimitsToJSON(json: any): GeneratorVideoLimits {
    return GeneratorVideoLimitsToJSONTyped(json, false);
}

export function GeneratorVideoLimitsToJSONTyped(value?: GeneratorVideoLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cfg': value['cfg'],
        'fps': value['fps'],
        'frames': value['frames'],
        'maxOutputBytes': value['maxOutputBytes'],
        'maxPixels': value['maxPixels'],
        'maxSourceBytes': value['maxSourceBytes'],
        'maxSourcePixels': value['maxSourcePixels'],
        'maxSteps': value['maxSteps'],
        'minSteps': value['minSteps'],
        'negativePromptChars': value['negativePromptChars'],
        'promptChars': value['promptChars'],
        'retentionDays': value['retentionDays'],
    };
}
