/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for public model discovery and safe model downloads. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Images item used by the Arc en Ciel API contract.
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * Cfg accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    cfg?: number;
    /**
     * Created At accepted or returned by this contract.
     * @type {Date}
     * @memberof Image
     */
    createdAt?: Date;
    /**
     * Description accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    description?: string;
    /**
     * Dislike Count accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    dislikeCount?: number;
    /**
     * File Name accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    fileName?: string;
    /**
     * File Path accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    filePath?: string;
    /**
     * Heart Count accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    heartCount?: number;
    /**
     * Id accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    id?: number;
    /**
     * Like Count accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    likeCount?: number;
    /**
     * Metadata accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    metadata?: string;
    /**
     * Negative Prompt accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    negativePrompt?: string;
    /**
     * Prompt accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    prompt?: string;
    /**
     * Rating accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    rating?: string;
    /**
     * Sampler accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    sampler?: string;
    /**
     * Seed accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    seed?: number;
    /**
     * Steps accepted or returned by this contract.
     * @type {number}
     * @memberof Image
     */
    steps?: number;
    /**
     * Title accepted or returned by this contract.
     * @type {string}
     * @memberof Image
     */
    title?: string;
    /**
     * Updated At accepted or returned by this contract.
     * @type {Date}
     * @memberof Image
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): value is Image {
    return true;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if (json == null) {
        return json;
    }
    return {
        
        'cfg': json['cfg'] == null ? undefined : json['cfg'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'description': json['description'] == null ? undefined : json['description'],
        'dislikeCount': json['dislikeCount'] == null ? undefined : json['dislikeCount'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'heartCount': json['heartCount'] == null ? undefined : json['heartCount'],
        'id': json['id'] == null ? undefined : json['id'],
        'likeCount': json['likeCount'] == null ? undefined : json['likeCount'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'negativePrompt': json['negativePrompt'] == null ? undefined : json['negativePrompt'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'sampler': json['sampler'] == null ? undefined : json['sampler'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ImageToJSON(json: any): Image {
    return ImageToJSONTyped(json, false);
}

export function ImageToJSONTyped(value?: Image | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cfg': value['cfg'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'description': value['description'],
        'dislikeCount': value['dislikeCount'],
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'heartCount': value['heartCount'],
        'id': value['id'],
        'likeCount': value['likeCount'],
        'metadata': value['metadata'],
        'negativePrompt': value['negativePrompt'],
        'prompt': value['prompt'],
        'rating': value['rating'],
        'sampler': value['sampler'],
        'seed': value['seed'],
        'steps': value['steps'],
        'title': value['title'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

