/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface InviteChatParticipantsRequest
 */
export interface InviteChatParticipantsRequest {
    /**
     * Existing users to invite or re-invite to the group.
     * @type {Set<number>}
     * @memberof InviteChatParticipantsRequest
     */
    userIds: Set<number>;
}

/**
 * Check if a given object implements the InviteChatParticipantsRequest interface.
 */
export function instanceOfInviteChatParticipantsRequest(value: object): value is InviteChatParticipantsRequest {
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function InviteChatParticipantsRequestFromJSON(json: any): InviteChatParticipantsRequest {
    return InviteChatParticipantsRequestFromJSONTyped(json, false);
}

export function InviteChatParticipantsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteChatParticipantsRequest {
    if (json == null) {
        return json;
    }
    return {

        'userIds': new Set(json['userIds']),
    };
}

export function InviteChatParticipantsRequestToJSON(json: any): InviteChatParticipantsRequest {
    return InviteChatParticipantsRequestToJSONTyped(json, false);
}

export function InviteChatParticipantsRequestToJSONTyped(value?: InviteChatParticipantsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'userIds': Array.from(value['userIds'] as Set<any>),
    };
}
