/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, public and personal profiles, visible media, social interactions, notifications, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request payload used by the Arc en Ciel API contract.
 * @export
 * @interface MarkAllNotificationsReadRequest
 */
export interface MarkAllNotificationsReadRequest {
    /**
     * Optional category scope. Defaults to `all`.
     * @type {MarkAllNotificationsReadRequestCategoryEnum}
     * @memberof MarkAllNotificationsReadRequest
     */
    category?: MarkAllNotificationsReadRequestCategoryEnum;
    /**
     * Optional flag for clients that only want unread scope.
     * @type {boolean}
     * @memberof MarkAllNotificationsReadRequest
     */
    unreadOnly?: boolean;
}


/**
 * @export
 */
export const MarkAllNotificationsReadRequestCategoryEnum = {
    All: 'all',
    Unread: 'unread',
    Following: 'following',
    Comments: 'comments',
    Reactions: 'reactions',
    Updates: 'updates',
    Collections: 'collections',
    Collabs: 'collabs',
    System: 'system',
    Moderation: 'moderation',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type MarkAllNotificationsReadRequestCategoryEnum = typeof MarkAllNotificationsReadRequestCategoryEnum[keyof typeof MarkAllNotificationsReadRequestCategoryEnum];


/**
 * Check if a given object implements the MarkAllNotificationsReadRequest interface.
 */
export function instanceOfMarkAllNotificationsReadRequest(value: object): value is MarkAllNotificationsReadRequest {
    return true;
}

export function MarkAllNotificationsReadRequestFromJSON(json: any): MarkAllNotificationsReadRequest {
    return MarkAllNotificationsReadRequestFromJSONTyped(json, false);
}

export function MarkAllNotificationsReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkAllNotificationsReadRequest {
    if (json == null) {
        return json;
    }
    return {

        'category': json['category'] == null ? undefined : json['category'],
        'unreadOnly': json['unreadOnly'] == null ? undefined : json['unreadOnly'],
    };
}

export function MarkAllNotificationsReadRequestToJSON(json: any): MarkAllNotificationsReadRequest {
    return MarkAllNotificationsReadRequestToJSONTyped(json, false);
}

export function MarkAllNotificationsReadRequestToJSONTyped(value?: MarkAllNotificationsReadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'category': value['category'],
        'unreadOnly': value['unreadOnly'],
    };
}
