/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Image } from './Image.js';
import {
    instanceOfImage,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image.js';
import type { Video } from './Video.js';
import {
    instanceOfVideo,
    VideoFromJSON,
    VideoFromJSONTyped,
    VideoToJSON,
} from './Video.js';

/**
 * @type ModelGalleryMediaEntryData
 * Image or video metadata for this gallery entry.
 * @export
 */
export type ModelGalleryMediaEntryData = Image | Video;

export function ModelGalleryMediaEntryDataFromJSON(json: any): ModelGalleryMediaEntryData {
    return ModelGalleryMediaEntryDataFromJSONTyped(json, false);
}

export function ModelGalleryMediaEntryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelGalleryMediaEntryData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfImage(json)) {
        return ImageFromJSONTyped(json, true);
    }
    if (instanceOfVideo(json)) {
        return VideoFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ModelGalleryMediaEntryDataToJSON(json: any): any {
    return ModelGalleryMediaEntryDataToJSONTyped(json, false);
}

export function ModelGalleryMediaEntryDataToJSONTyped(value?: ModelGalleryMediaEntryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfImage(value)) {
        return ImageToJSON(value as Image);
    }
    if (instanceOfVideo(value)) {
        return VideoToJSON(value as Video);
    }
    return {};
}
