/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ModelVersionMediaPreviewResponseVersionsInner } from './ModelVersionMediaPreviewResponseVersionsInner.js';
import {
    ModelVersionMediaPreviewResponseVersionsInnerFromJSON,
    ModelVersionMediaPreviewResponseVersionsInnerFromJSONTyped,
    ModelVersionMediaPreviewResponseVersionsInnerToJSON,
    ModelVersionMediaPreviewResponseVersionsInnerToJSONTyped,
} from './ModelVersionMediaPreviewResponseVersionsInner.js';

/**
 * Lightweight visible media grouped by model version for carousel and picker integrations.
 * @export
 * @interface ModelVersionMediaPreviewResponse
 */
export interface ModelVersionMediaPreviewResponse {
    /**
     * Maximum entries returned per version after server clamping.
     * @type {number}
     * @memberof ModelVersionMediaPreviewResponse
     */
    limit: number;
    /**
     * Model whose versions were queried.
     * @type {number}
     * @memberof ModelVersionMediaPreviewResponse
     */
    modelId: number;
    /**
     * Ordered versions entries included with this model version media preview response; an empty list means none are available.
     * @type {Array<ModelVersionMediaPreviewResponseVersionsInner>}
     * @memberof ModelVersionMediaPreviewResponse
     */
    versions: Array<ModelVersionMediaPreviewResponseVersionsInner>;
}

/**
 * Check if a given object implements the ModelVersionMediaPreviewResponse interface.
 */
export function instanceOfModelVersionMediaPreviewResponse(value: object): value is ModelVersionMediaPreviewResponse {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function ModelVersionMediaPreviewResponseFromJSON(json: any): ModelVersionMediaPreviewResponse {
    return ModelVersionMediaPreviewResponseFromJSONTyped(json, false);
}

export function ModelVersionMediaPreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelVersionMediaPreviewResponse {
    if (json == null) {
        return json;
    }
    return {

        'limit': json['limit'],
        'modelId': json['modelId'],
        'versions': ((json['versions'] as Array<any>).map(ModelVersionMediaPreviewResponseVersionsInnerFromJSON)),
    };
}

export function ModelVersionMediaPreviewResponseToJSON(json: any): ModelVersionMediaPreviewResponse {
    return ModelVersionMediaPreviewResponseToJSONTyped(json, false);
}

export function ModelVersionMediaPreviewResponseToJSONTyped(value?: ModelVersionMediaPreviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'limit': value['limit'],
        'modelId': value['modelId'],
        'versions': ((value['versions'] as Array<any>).map(ModelVersionMediaPreviewResponseVersionsInnerToJSON)),
    };
}
