/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `created` has no valid chunks; `uploading` has at least one; `processing` is assembling/creating the version; `completed`, `error`, and `cancelled` are terminal for polling.
 * @export
 */
export const ModelVersionChunkUploadStatus = {
    Created: 'created',
    Uploading: 'uploading',
    Processing: 'processing',
    Completed: 'completed',
    Error: 'error',
    Cancelled: 'cancelled',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ModelVersionChunkUploadStatus = typeof ModelVersionChunkUploadStatus[keyof typeof ModelVersionChunkUploadStatus];


export function instanceOfModelVersionChunkUploadStatus(value: any): boolean {
    for (const key in ModelVersionChunkUploadStatus) {
        if (Object.prototype.hasOwnProperty.call(ModelVersionChunkUploadStatus, key)) {
            if (ModelVersionChunkUploadStatus[key as keyof typeof ModelVersionChunkUploadStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModelVersionChunkUploadStatusFromJSON(json: any): ModelVersionChunkUploadStatus {
    return ModelVersionChunkUploadStatusFromJSONTyped(json, false);
}

export function ModelVersionChunkUploadStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelVersionChunkUploadStatus {
    return json as ModelVersionChunkUploadStatus;
}

export function ModelVersionChunkUploadStatusToJSON(value?: ModelVersionChunkUploadStatus | null): any {
    return value as any;
}

export function ModelVersionChunkUploadStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ModelVersionChunkUploadStatus {
    return value as ModelVersionChunkUploadStatus;
}
