/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ModelVersionResourceGraphResponseCounts } from './ModelVersionResourceGraphResponseCounts.js';
import {
    ModelVersionResourceGraphResponseCountsFromJSON,
    ModelVersionResourceGraphResponseCountsFromJSONTyped,
    ModelVersionResourceGraphResponseCountsToJSON,
    ModelVersionResourceGraphResponseCountsToJSONTyped,
} from './ModelVersionResourceGraphResponseCounts.js';
import type { ModelVersionResourceGraphResponseGroups } from './ModelVersionResourceGraphResponseGroups.js';
import {
    ModelVersionResourceGraphResponseGroupsFromJSON,
    ModelVersionResourceGraphResponseGroupsFromJSONTyped,
    ModelVersionResourceGraphResponseGroupsToJSON,
    ModelVersionResourceGraphResponseGroupsToJSONTyped,
} from './ModelVersionResourceGraphResponseGroups.js';

/**
 * Visible local and external dependencies associated with one model version.
 * @export
 * @interface ModelVersionResourceGraphResponse
 */
export interface ModelVersionResourceGraphResponse {
    /**
     * Whether the current caller may see hidden edges and management metadata.
     * @type {boolean}
     * @memberof ModelVersionResourceGraphResponse
     */
    canManage: boolean;
    /**
     *
     * @type {ModelVersionResourceGraphResponseCounts}
     * @memberof ModelVersionResourceGraphResponse
     */
    counts: ModelVersionResourceGraphResponseCounts;
    /**
     *
     * @type {ModelVersionResourceGraphResponseGroups}
     * @memberof ModelVersionResourceGraphResponse
     */
    groups: ModelVersionResourceGraphResponseGroups;
    /**
     * Stable identifier for the source version; use it in subsequent API calls instead of a display name.
     * @type {number}
     * @memberof ModelVersionResourceGraphResponse
     */
    sourceVersionId: number;
}

/**
 * Check if a given object implements the ModelVersionResourceGraphResponse interface.
 */
export function instanceOfModelVersionResourceGraphResponse(value: object): value is ModelVersionResourceGraphResponse {
    if (!('canManage' in value) || value['canManage'] === undefined) return false;
    if (!('counts' in value) || value['counts'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if (!('sourceVersionId' in value) || value['sourceVersionId'] === undefined) return false;
    return true;
}

export function ModelVersionResourceGraphResponseFromJSON(json: any): ModelVersionResourceGraphResponse {
    return ModelVersionResourceGraphResponseFromJSONTyped(json, false);
}

export function ModelVersionResourceGraphResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelVersionResourceGraphResponse {
    if (json == null) {
        return json;
    }
    return {

        'canManage': json['canManage'],
        'counts': ModelVersionResourceGraphResponseCountsFromJSON(json['counts']),
        'groups': ModelVersionResourceGraphResponseGroupsFromJSON(json['groups']),
        'sourceVersionId': json['sourceVersionId'],
    };
}

export function ModelVersionResourceGraphResponseToJSON(json: any): ModelVersionResourceGraphResponse {
    return ModelVersionResourceGraphResponseToJSONTyped(json, false);
}

export function ModelVersionResourceGraphResponseToJSONTyped(value?: ModelVersionResourceGraphResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'canManage': value['canManage'],
        'counts': ModelVersionResourceGraphResponseCountsToJSON(value['counts']),
        'groups': ModelVersionResourceGraphResponseGroupsToJSON(value['groups']),
        'sourceVersionId': value['sourceVersionId'],
    };
}
