/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing oauth introspection in Developer API requests and responses.
 * @export
 * @interface OAuthIntrospection
 */
export interface OAuthIntrospection {
    /**
     * Whether active applies to this oauth introspection.
     * @type {boolean}
     * @memberof OAuthIntrospection
     */
    active: boolean;
    /**
     * Stable identifier for the client; use it in subsequent API calls instead of a display name.
     * @type {string}
     * @memberof OAuthIntrospection
     */
    clientId?: string;
    /**
     * Expiry as Unix seconds.
     * @type {number}
     * @memberof OAuthIntrospection
     */
    exp?: number;
    /**
     * Issue time as Unix seconds.
     * @type {number}
     * @memberof OAuthIntrospection
     */
    iat?: number;
    /**
     * Iss associated with this oauth introspection; preserve server-returned values when passing them to another operation. Format: uri.
     * @type {string}
     * @memberof OAuthIntrospection
     */
    iss?: string;
    /**
     * Scope associated with this oauth introspection; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof OAuthIntrospection
     */
    scope?: string;
    /**
     * Stable Arc en Ciel user identifier.
     * @type {string}
     * @memberof OAuthIntrospection
     */
    sub?: string;
    /**
     * Discriminator identifying the kind of oauth introspection; clients should tolerate future values. Supported values: `Bearer`.
     * @type {OAuthIntrospectionTokenTypeEnum}
     * @memberof OAuthIntrospection
     */
    tokenType?: OAuthIntrospectionTokenTypeEnum;
    /**
     * Username associated with this oauth introspection; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof OAuthIntrospection
     */
    username?: string;
}


/**
 * @export
 */
export const OAuthIntrospectionTokenTypeEnum = {
    Bearer: 'Bearer',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type OAuthIntrospectionTokenTypeEnum = typeof OAuthIntrospectionTokenTypeEnum[keyof typeof OAuthIntrospectionTokenTypeEnum];


/**
 * Check if a given object implements the OAuthIntrospection interface.
 */
export function instanceOfOAuthIntrospection(value: object): value is OAuthIntrospection {
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function OAuthIntrospectionFromJSON(json: any): OAuthIntrospection {
    return OAuthIntrospectionFromJSONTyped(json, false);
}

export function OAuthIntrospectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthIntrospection {
    if (json == null) {
        return json;
    }
    return {

        'active': json['active'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'exp': json['exp'] == null ? undefined : json['exp'],
        'iat': json['iat'] == null ? undefined : json['iat'],
        'iss': json['iss'] == null ? undefined : json['iss'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'sub': json['sub'] == null ? undefined : json['sub'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function OAuthIntrospectionToJSON(json: any): OAuthIntrospection {
    return OAuthIntrospectionToJSONTyped(json, false);
}

export function OAuthIntrospectionToJSONTyped(value?: OAuthIntrospection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'active': value['active'],
        'client_id': value['clientId'],
        'exp': value['exp'],
        'iat': value['iat'],
        'iss': value['iss'],
        'scope': value['scope'],
        'sub': value['sub'],
        'token_type': value['tokenType'],
        'username': value['username'],
    };
}
