/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing oauth scope in Developer API requests and responses.
 * @export
 * @interface OAuthScope
 */
export interface OAuthScope {
    /**
     * User-facing explanation of what the application may do.
     * @type {string}
     * @memberof OAuthScope
     */
    description: string;
    /**
     * Stable scope name sent in authorization requests and returned by token endpoints.
     * @type {string}
     * @memberof OAuthScope
     */
    name: string;
    /**
     * Consent-screen risk category; clients must tolerate future categories.
     * @type {OAuthScopeRiskEnum}
     * @memberof OAuthScope
     */
    risk: OAuthScopeRiskEnum;
    /**
     * Short consent-screen label for the permission.
     * @type {string}
     * @memberof OAuthScope
     */
    title: string;
    /**
     * Internal permission bit used for resource scopes; null for offline_access.
     * @type {number}
     * @memberof OAuthScope
     */
    value?: number | null;
}


/**
 * @export
 */
export const OAuthScopeRiskEnum = {
    Read: 'read',
    Write: 'write',
    Delete: 'delete',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type OAuthScopeRiskEnum = typeof OAuthScopeRiskEnum[keyof typeof OAuthScopeRiskEnum];


/**
 * Check if a given object implements the OAuthScope interface.
 */
export function instanceOfOAuthScope(value: object): value is OAuthScope {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('risk' in value) || value['risk'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function OAuthScopeFromJSON(json: any): OAuthScope {
    return OAuthScopeFromJSONTyped(json, false);
}

export function OAuthScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthScope {
    if (json == null) {
        return json;
    }
    return {

        'description': json['description'],
        'name': json['name'],
        'risk': json['risk'],
        'title': json['title'],
        'value': json['value'] === undefined ? undefined : json['value'] === null ? null : json['value'],
    };
}

export function OAuthScopeToJSON(json: any): OAuthScope {
    return OAuthScopeToJSONTyped(json, false);
}

export function OAuthScopeToJSONTyped(value?: OAuthScope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'description': value['description'],
        'name': value['name'],
        'risk': value['risk'],
        'title': value['title'],
        'value': value['value'],
    };
}
