/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Structured order item details for this order.
 * @export
 * @interface ReorderCollectionItemsRequestOrderInner
 */
export interface ReorderCollectionItemsRequestOrderInner {
    /**
     * Stable identifier for the order item; use it in subsequent API calls instead of a display name.
     * @type {number}
     * @memberof ReorderCollectionItemsRequestOrderInner
     */
    id: number;
    /**
     * Numeric order reported for this order item.
     * @type {number}
     * @memberof ReorderCollectionItemsRequestOrderInner
     */
    order: number;
}

/**
 * Check if a given object implements the ReorderCollectionItemsRequestOrderInner interface.
 */
export function instanceOfReorderCollectionItemsRequestOrderInner(value: object): value is ReorderCollectionItemsRequestOrderInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ReorderCollectionItemsRequestOrderInnerFromJSON(json: any): ReorderCollectionItemsRequestOrderInner {
    return ReorderCollectionItemsRequestOrderInnerFromJSONTyped(json, false);
}

export function ReorderCollectionItemsRequestOrderInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderCollectionItemsRequestOrderInner {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'order': json['order'],
    };
}

export function ReorderCollectionItemsRequestOrderInnerToJSON(json: any): ReorderCollectionItemsRequestOrderInner {
    return ReorderCollectionItemsRequestOrderInnerToJSONTyped(json, false);
}

export function ReorderCollectionItemsRequestOrderInnerToJSONTyped(value?: ReorderCollectionItemsRequestOrderInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'order': value['order'],
    };
}
