/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing request payload in Developer API requests and responses.
 * @export
 * @interface ResequenceCollectionItemsRequest
 */
export interface ResequenceCollectionItemsRequest {
    /**
     * Manually override the resequencing mode. Defaults to the collection preference.
     * @type {ResequenceCollectionItemsRequestModeEnum}
     * @memberof ResequenceCollectionItemsRequest
     */
    mode?: ResequenceCollectionItemsRequestModeEnum;
}


/**
 * @export
 */
export const ResequenceCollectionItemsRequestModeEnum = {
    Newest: 'newest',
    Oldest: 'oldest',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ResequenceCollectionItemsRequestModeEnum = typeof ResequenceCollectionItemsRequestModeEnum[keyof typeof ResequenceCollectionItemsRequestModeEnum];


/**
 * Check if a given object implements the ResequenceCollectionItemsRequest interface.
 */
export function instanceOfResequenceCollectionItemsRequest(value: object): value is ResequenceCollectionItemsRequest {
    return true;
}

export function ResequenceCollectionItemsRequestFromJSON(json: any): ResequenceCollectionItemsRequest {
    return ResequenceCollectionItemsRequestFromJSONTyped(json, false);
}

export function ResequenceCollectionItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResequenceCollectionItemsRequest {
    if (json == null) {
        return json;
    }
    return {

        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function ResequenceCollectionItemsRequestToJSON(json: any): ResequenceCollectionItemsRequest {
    return ResequenceCollectionItemsRequestToJSONTyped(json, false);
}

export function ResequenceCollectionItemsRequestToJSONTyped(value?: ResequenceCollectionItemsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'mode': value['mode'],
    };
}
