/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request payload used by the Arc en Ciel API contract.
 * @export
 * @interface ScheduleVideoRequest
 */
export interface ScheduleVideoRequest {
    /**
     * Timestamp when the video should be published.
     * @type {Date}
     * @memberof ScheduleVideoRequest
     */
    publishAt: Date;
}

/**
 * Check if a given object implements the ScheduleVideoRequest interface.
 */
export function instanceOfScheduleVideoRequest(value: object): value is ScheduleVideoRequest {
    if (!('publishAt' in value) || value['publishAt'] === undefined) return false;
    return true;
}

export function ScheduleVideoRequestFromJSON(json: any): ScheduleVideoRequest {
    return ScheduleVideoRequestFromJSONTyped(json, false);
}

export function ScheduleVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleVideoRequest {
    if (json == null) {
        return json;
    }
    return {

        'publishAt': (new Date(json['publishAt'])),
    };
}

export function ScheduleVideoRequestToJSON(json: any): ScheduleVideoRequest {
    return ScheduleVideoRequestToJSONTyped(json, false);
}

export function ScheduleVideoRequestToJSONTyped(value?: ScheduleVideoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'publishAt': value['publishAt'].toISOString(),
    };
}
