/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GeneratorModelCatalogEntry } from './GeneratorModelCatalogEntry.js';
import {
    GeneratorModelCatalogEntryFromJSON,
    GeneratorModelCatalogEntryFromJSONTyped,
    GeneratorModelCatalogEntryToJSON,
    GeneratorModelCatalogEntryToJSONTyped,
} from './GeneratorModelCatalogEntry.js';

/**
 * Fields describing 200 response for api generator models checkpoints in Developer API requests and responses.
 * @export
 * @interface SearchGeneratorCheckpoints200Response
 */
export interface SearchGeneratorCheckpoints200Response {
    /**
     * Base Model associated with this 200 response for api generator models checkpoints; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof SearchGeneratorCheckpoints200Response
     */
    baseModel: string | null;
    /**
     * Ordered entries entries included with this 200 response for api generator models checkpoints; an empty list means none are available.
     * @type {Array<GeneratorModelCatalogEntry>}
     * @memberof SearchGeneratorCheckpoints200Response
     */
    entries: Array<GeneratorModelCatalogEntry>;
    /**
     * Maximum number of records requested or returned in one page of this 200 response for api generator models checkpoints.
     * @type {number}
     * @memberof SearchGeneratorCheckpoints200Response
     */
    limit: number;
    /**
     * Query associated with this 200 response for api generator models checkpoints; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof SearchGeneratorCheckpoints200Response
     */
    query: string;
}

/**
 * Check if a given object implements the SearchGeneratorCheckpoints200Response interface.
 */
export function instanceOfSearchGeneratorCheckpoints200Response(value: object): value is SearchGeneratorCheckpoints200Response {
    if (!('baseModel' in value) || value['baseModel'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function SearchGeneratorCheckpoints200ResponseFromJSON(json: any): SearchGeneratorCheckpoints200Response {
    return SearchGeneratorCheckpoints200ResponseFromJSONTyped(json, false);
}

export function SearchGeneratorCheckpoints200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGeneratorCheckpoints200Response {
    if (json == null) {
        return json;
    }
    return {

        'baseModel': json['baseModel'],
        'entries': ((json['entries'] as Array<any>).map(GeneratorModelCatalogEntryFromJSON)),
        'limit': json['limit'],
        'query': json['query'],
    };
}

export function SearchGeneratorCheckpoints200ResponseToJSON(json: any): SearchGeneratorCheckpoints200Response {
    return SearchGeneratorCheckpoints200ResponseToJSONTyped(json, false);
}

export function SearchGeneratorCheckpoints200ResponseToJSONTyped(value?: SearchGeneratorCheckpoints200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'baseModel': value['baseModel'],
        'entries': ((value['entries'] as Array<any>).map(GeneratorModelCatalogEntryToJSON)),
        'limit': value['limit'],
        'query': value['query'],
    };
}
