/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, generation, private chat, feedback, privacy-filtered trust and safety cases, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.  Runtime resource URLs deliberately remain under `/api/...`; v1 is versioned by this immutable contract rather than a `/api/v1/...` path prefix. Additive releases preserve existing v1 requests and responses, while a future breaking v2 will use a parallel migration surface and the published deprecation policy.
 *
 * The version of the OpenAPI document: 1.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Fields describing request payload in Developer API requests and responses.
 * @export
 * @interface UpdateVideoRequest
 */
export interface UpdateVideoRequest {
    /**
     * Numeric cfg reported for this request payload.
     * @type {number}
     * @memberof UpdateVideoRequest
     */
    cfg?: number;
    /**
     * User-facing description of this request payload; it may contain an empty string when no description was supplied.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    description?: string;
    /**
     * Negative Prompt text associated with generation of this request payload; availability depends on visibility and privacy rules.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    negativePrompt?: string;
    /**
     * Prompt text associated with generation of this request payload; availability depends on visibility and privacy rules.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    prompt?: string;
    /**
     * safe, questionable, sensitive or explicit
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    rating?: string;
    /**
     * Sampler associated with this request payload; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    sampler?: string;
    /**
     * Seed associated with this request payload; preserve server-returned values when passing them to another operation.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    seed?: string;
    /**
     * Numeric steps reported for this request payload.
     * @type {number}
     * @memberof UpdateVideoRequest
     */
    steps?: number;
    /**
     * Comma-separated list of tags.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    tags?: string;
    /**
     * Display title shown to users for this request payload.
     * @type {string}
     * @memberof UpdateVideoRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the UpdateVideoRequest interface.
 */
export function instanceOfUpdateVideoRequest(value: object): value is UpdateVideoRequest {
    return true;
}

export function UpdateVideoRequestFromJSON(json: any): UpdateVideoRequest {
    return UpdateVideoRequestFromJSONTyped(json, false);
}

export function UpdateVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVideoRequest {
    if (json == null) {
        return json;
    }
    return {

        'cfg': json['cfg'] == null ? undefined : json['cfg'],
        'description': json['description'] == null ? undefined : json['description'],
        'negativePrompt': json['negativePrompt'] == null ? undefined : json['negativePrompt'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'sampler': json['sampler'] == null ? undefined : json['sampler'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function UpdateVideoRequestToJSON(json: any): UpdateVideoRequest {
    return UpdateVideoRequestToJSONTyped(json, false);
}

export function UpdateVideoRequestToJSONTyped(value?: UpdateVideoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cfg': value['cfg'],
        'description': value['description'],
        'negativePrompt': value['negativePrompt'],
        'prompt': value['prompt'],
        'rating': value['rating'],
        'sampler': value['sampler'],
        'seed': value['seed'],
        'steps': value['steps'],
        'tags': value['tags'],
        'title': value['title'],
    };
}
