/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 200 response for api users me profile picture used by the Arc en Ciel API contract.
 * @export
 * @interface UpdateMyProfilePicture200Response
 */
export interface UpdateMyProfilePicture200Response {
    /**
     * Message accepted or returned by this contract.
     * @type {string}
     * @memberof UpdateMyProfilePicture200Response
     */
    message?: string;
    /**
     * Profile Picture accepted or returned by this contract.
     * @type {string}
     * @memberof UpdateMyProfilePicture200Response
     */
    profilePicture?: string;
}

/**
 * Check if a given object implements the UpdateMyProfilePicture200Response interface.
 */
export function instanceOfUpdateMyProfilePicture200Response(value: object): value is UpdateMyProfilePicture200Response {
    return true;
}

export function UpdateMyProfilePicture200ResponseFromJSON(json: any): UpdateMyProfilePicture200Response {
    return UpdateMyProfilePicture200ResponseFromJSONTyped(json, false);
}

export function UpdateMyProfilePicture200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyProfilePicture200Response {
    if (json == null) {
        return json;
    }
    return {

        'message': json['message'] == null ? undefined : json['message'],
        'profilePicture': json['profilePicture'] == null ? undefined : json['profilePicture'],
    };
}

export function UpdateMyProfilePicture200ResponseToJSON(json: any): UpdateMyProfilePicture200Response {
    return UpdateMyProfilePicture200ResponseToJSONTyped(json, false);
}

export function UpdateMyProfilePicture200ResponseToJSONTyped(value?: UpdateMyProfilePicture200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'message': value['message'],
        'profilePicture': value['profilePicture'],
    };
}
