/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, public creator profiles, visible media metadata, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Social Links item used by the Arc en Ciel API contract.
 * @export
 * @interface UserProfileSocialLinksInner
 */
export interface UserProfileSocialLinksInner {
    /**
     * Icon accepted or returned by this contract.
     * @type {string}
     * @memberof UserProfileSocialLinksInner
     */
    icon?: string;
    /**
     * Id accepted or returned by this contract.
     * @type {number}
     * @memberof UserProfileSocialLinksInner
     */
    id?: number;
    /**
     * Order accepted or returned by this contract.
     * @type {number}
     * @memberof UserProfileSocialLinksInner
     */
    order?: number;
    /**
     * Url accepted or returned by this contract.
     * @type {string}
     * @memberof UserProfileSocialLinksInner
     */
    url?: string;
}

/**
 * Check if a given object implements the UserProfileSocialLinksInner interface.
 */
export function instanceOfUserProfileSocialLinksInner(value: object): value is UserProfileSocialLinksInner {
    return true;
}

export function UserProfileSocialLinksInnerFromJSON(json: any): UserProfileSocialLinksInner {
    return UserProfileSocialLinksInnerFromJSONTyped(json, false);
}

export function UserProfileSocialLinksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileSocialLinksInner {
    if (json == null) {
        return json;
    }
    return {

        'icon': json['icon'] == null ? undefined : json['icon'],
        'id': json['id'] == null ? undefined : json['id'],
        'order': json['order'] == null ? undefined : json['order'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function UserProfileSocialLinksInnerToJSON(json: any): UserProfileSocialLinksInner {
    return UserProfileSocialLinksInnerToJSONTyped(json, false);
}

export function UserProfileSocialLinksInnerToJSONTyped(value?: UserProfileSocialLinksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'icon': value['icon'],
        'id': value['id'],
        'order': value['order'],
        'url': value['url'],
    };
}
