/* tslint:disable */
/* eslint-disable */
/**
 * Arc en Ciel Developer API
 * Stable, SDK-oriented Arc en Ciel API v1 contract for catalogue discovery, personal and social workflows, creator publishing, image and video generation, private chat workflows, managed media, collections, and safe binary transfers. The complete public API reference contains additional evolving operations outside this compatibility profile.
 *
 * The version of the OpenAPI document: 1.7.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Run accepted or returned by this contract.
 * @export
 * @interface VersionTrainingMetadataSummaryRun
 */
export interface VersionTrainingMetadataSummaryRun {
    /**
     * Batch Size accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    batchSize?: number;
    /**
     * Epoch accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    epoch?: number;
    /**
     * Learning Rate accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    learningRate?: number;
    /**
     * Optimizer accepted or returned by this contract.
     * @type {string}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    optimizer?: string;
    /**
     * Resolution accepted or returned by this contract.
     * @type {string}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    resolution?: string;
    /**
     * Scheduler accepted or returned by this contract.
     * @type {string}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    scheduler?: string;
    /**
     * Steps accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    steps?: number;
    /**
     * Text Encoder Learning Rate accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    textEncoderLearningRate?: number;
    /**
     * Total Epochs accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    totalEpochs?: number;
    /**
     * Unet Learning Rate accepted or returned by this contract.
     * @type {number}
     * @memberof VersionTrainingMetadataSummaryRun
     */
    unetLearningRate?: number;
}

/**
 * Check if a given object implements the VersionTrainingMetadataSummaryRun interface.
 */
export function instanceOfVersionTrainingMetadataSummaryRun(value: object): value is VersionTrainingMetadataSummaryRun {
    return true;
}

export function VersionTrainingMetadataSummaryRunFromJSON(json: any): VersionTrainingMetadataSummaryRun {
    return VersionTrainingMetadataSummaryRunFromJSONTyped(json, false);
}

export function VersionTrainingMetadataSummaryRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionTrainingMetadataSummaryRun {
    if (json == null) {
        return json;
    }
    return {

        'batchSize': json['batchSize'] == null ? undefined : json['batchSize'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'learningRate': json['learningRate'] == null ? undefined : json['learningRate'],
        'optimizer': json['optimizer'] == null ? undefined : json['optimizer'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'scheduler': json['scheduler'] == null ? undefined : json['scheduler'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'textEncoderLearningRate': json['textEncoderLearningRate'] == null ? undefined : json['textEncoderLearningRate'],
        'totalEpochs': json['totalEpochs'] == null ? undefined : json['totalEpochs'],
        'unetLearningRate': json['unetLearningRate'] == null ? undefined : json['unetLearningRate'],
    };
}

export function VersionTrainingMetadataSummaryRunToJSON(json: any): VersionTrainingMetadataSummaryRun {
    return VersionTrainingMetadataSummaryRunToJSONTyped(json, false);
}

export function VersionTrainingMetadataSummaryRunToJSONTyped(value?: VersionTrainingMetadataSummaryRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'batchSize': value['batchSize'],
        'epoch': value['epoch'],
        'learningRate': value['learningRate'],
        'optimizer': value['optimizer'],
        'resolution': value['resolution'],
        'scheduler': value['scheduler'],
        'steps': value['steps'],
        'textEncoderLearningRate': value['textEncoderLearningRate'],
        'totalEpochs': value['totalEpochs'],
        'unetLearningRate': value['unetLearningRate'],
    };
}
